// KvízParty kérdésbázis – 2/5 darab (kategóriák: 6–10)

// ---------- 6. Gasztronómia 🌶️ ----------
// – 1 a 4-ből (30 db) –
{cat:6,type:'mc',d:1,q:"Melyik város híres a csabai kolbászról?",
 o:["Békéscsaba","Eger","Szekszárd","Villány"], c:0},
{cat:6,type:'mc',d:1,q:"Melyik városból származik a Pick szalámi?",
 o:["Szeged","Budapest","Debrecen","Kecskemét"], c:0},
{cat:6,type:'mc',d:1,q:"Melyik család nevéhez fűződik az Unicum?",
 o:["Zwack","Gundel","Törley","Richter"], c:0},
{cat:6,type:'mc',d:2,q:"Melyik két város híres leginkább a halászléjéről?",
 o:["Baja és Szeged","Debrecen és Gyula","Kalocsa és Szentes","Eger és Tokaj"], c:0},
{cat:6,type:'mc',d:2,q:"Melyik szőlőfajta a tokaji aszú legfontosabb alapanyaga?",
 o:["Furmint","Kékfrankos","Olaszrizling","Cserszegi fűszeres"], c:0},
{cat:6,type:'mc',d:2,q:"Melyik desszert fűződik Gundel Károly nevéhez?",
 o:["Gundel-palacsinta","Somlói galuska","Dobos-torta","Rákóczi-túrós"], c:0},
{cat:6,type:'mc',d:2,q:"Melyik három alapanyag adja a klasszikus lecsó alapját?",
 o:["Paprika, paradicsom, hagyma","Cukkini, padlizsán, paradicsom","Burgonya, hagyma, gomba","Paprika, káposzta, répa"], c:0},
{cat:6,type:'mc',d:2,q:"Mit jelentett eredetileg a „gulyás” szó?",
 o:["Marhapásztort","Bográcsot","Fűszeres levest","Vándorszakácsot"], c:0},
{cat:6,type:'mc',d:2,q:"Hogyan sütik hagyományosan a kürtőskalácsot?",
 o:["Fahengerre tekert tésztát parázs fölött forgatva","Kemencében, agyagformában","Bő olajban kisütve","Vastag palacsintasütőben"], c:0},
{cat:6,type:'mc',d:3,q:"Mivel töltik a hortobágyi húsos palacsintát?",
 o:["Paprikás húsraguval","Túróval és kaporral","Gombás rizzsel","Sonkás sajtkrémmel"], c:0},
{cat:6,type:'mc',d:3,q:"Eger mellett melyik borvidék készíthet eredetvédett bikavért?",
 o:["Szekszárd","Villány","Badacsony","Somló"], c:0},
{cat:6,type:'mc',d:3,q:"Kiről kapta a nevét a Rigó Jancsi nevű csokoládés-tejszínes sütemény?",
 o:["Egy híres cigányprímásról","Egy pesti cukrászmesterről","Egy operettszínészről","Egy huszárkapitányról"], c:0},
{cat:6,type:'mc',d:3,q:"Mi a mangalica?",
 o:["Göndör szőrű magyar sertésfajta","Ősi magyar szarvasmarhafajta","Magyar pásztorkutyafajta","Régi magyar tyúkfajta"], c:0},
{cat:6,type:'mc',d:3,q:"Melyik magyar város világhírű a hagymatermesztéséről?",
 o:["Makó","Gyula","Cegléd","Szentes"], c:0},
{cat:6,type:'mc',d:3,q:"Melyik két magyar város környéke a fűszerpaprika-őrlemény leghíresebb termőtája?",
 o:["Kalocsa és Szeged","Baja és Mohács","Debrecen és Gyula","Eger és Tokaj"], c:0},
{cat:6,type:'mc',d:3,q:"Mi a tarhonya?",
 o:["Apró, gömbölyded szemekre morzsolt tojásos száraztészta","Kukoricadarából főzött sűrű kása","Burgonyából sütött lepény","Savanyított káposztaféle"], c:0},
{cat:6,type:'mc',d:3,q:"Melyik magyar íróról nevezték el a füstölt csülökkel készülő, gazdag bablevest?",
 o:["Jókai Mórról","Mikszáth Kálmánról","Móricz Zsigmondról","Krúdy Gyuláról"], c:0},
{cat:6,type:'mc',d:3,q:"Mi kerül a zserbószelet tésztarétegei közé?",
 o:["Diós töltelék baracklekvárral","Gesztenyekrém rummal","Mákos guba","Vaníliás túrókrém"], c:0},
{cat:6,type:'mc',d:3,q:"Melyik városhoz kötődik a busójárás, a hungarikumként is elismert télűző népszokás?",
 o:["Mohács","Baja","Szekszárd","Siklós"], c:0},
{cat:6,type:'mc',d:3,q:"Melyik településről kapta a nevét a hungarikum halasi csipke?",
 o:["Kiskunhalas","Hajdúszoboszló","Kiskunfélegyháza","Hódmezővásárhely"], c:0},
{cat:6,type:'mc',d:3,q:"Melyik városban működik a hungarikumként számon tartott Zsolnay porcelánmanufaktúra?",
 o:["Pécs","Herend","Hollóháza","Kecskemét"], c:0},
{cat:6,type:'mc',d:4,q:"Kiről nevezték el az Újházi tyúkhúslevest?",
 o:["Újházi Ede színművészről","Egy pesti fogadósról","Újházi Pál szakácsmesterről","Egy debreceni csárdatulajdonosról"], c:0},
{cat:6,type:'mc',d:4,q:"Melyik borvidék jellegzetes fehér szőlőfajtája a juhfark?",
 o:["Somló","Villány","Szekszárd","Kunság"], c:0},
{cat:6,type:'mc',d:4,q:"Melyik magvas alapanyag jellemzi hagyományosan az Esterházy-torta lapjait és krémjét?",
 o:["Dió","Mák","Gesztenye","Kókusz"], c:0},
{cat:6,type:'mc',d:4,q:"Mi a fő különbség a paprikás és a pörkölt között?",
 o:["A paprikást tejföllel vagy tejszínnel készítik","A pörköltbe nem kerül hagyma","A paprikás mindig halból készül","A pörköltet sütőben készítik"], c:0},
{cat:6,type:'mc',d:4,q:"Melyik város híres a matyó hímzésről, amely az UNESCO szellemi kulturális örökség listáján is szerepel?",
 o:["Mezőkövesd","Kalocsa","Karcag","Hollókő"], c:0},
{cat:6,type:'mc',d:4,q:"Mi a zalai-göcseji dödölle két fő alapanyaga?",
 o:["Burgonya és liszt","Kukorica és tejföl","Káposzta és tészta","Bab és árpagyöngy"], c:0},
{cat:6,type:'mc',d:5,q:"Melyik cukrásztól vette át Gerbeaud Emil a mai Vörösmarty téren működő híres pesti cukrászdát?",
 o:["Kugler Henriktől","Ruszwurm Vilmostól","Auguszt Elektől","Hauer Rezsőtől"], c:0},
{cat:6,type:'mc',d:5,q:"A hagyomány szerint kiről kapta a nevét a székelykáposzta?",
 o:["Székely József levéltárosról","Az erdélyi székelyekről","Székely Bertalan festőről","Egy székelyudvarhelyi fogadósról"], c:0},
{cat:6,type:'mc',d:5,q:"Ki írta a két világháború közötti korszak klasszikus gasztronómiai művét, „Az ínyesmester szakácskönyvét”?",
 o:["Magyar Elek","Gundel Károly","Váncza József","Horváth Ilona"], c:0},
// – tippelős (20 db) –
{cat:6,type:'tip',d:1,q:"Hány centiliteres egy hagyományos „feles” pálinka?",a:5,unit:"cl",note:"A neve a fél deciliterre utal."},
{cat:6,type:'tip',d:1,q:"Augusztus hányadikán ünnepeljük az új kenyér ünnepét?",a:20,unit:"",note:"Az államalapítás ünnepén hagyomány az új búzából sütött kenyér megszegése."},
{cat:6,type:'tip',d:2,q:"Hány deciliter bor kerül a nagyfröccsbe?",a:2,unit:"dl",note:"A nagyfröccs 2 dl borból és 1 dl szódából áll."},
{cat:6,type:'tip',d:2,q:"November hányadikán van Márton-nap, amikor a hagyomány szerint libát illik enni?",a:11,unit:"",note:"„Aki Márton napján libát nem eszik, egész éven át éhezik.”"},
{cat:6,type:'tip',d:2,q:"Hány milliliteres a szabványos borospalack?",a:750,unit:"ml",note:"Ez a világszerte elterjedt 0,75 literes űrtartalom."},
{cat:6,type:'tip',d:2,q:"Hányféle klasszikus töltelékkel készül hagyományosan a karácsonyi bejgli?",a:2,unit:"féle",note:"Mákos és diós változatban."},
{cat:6,type:'tip',d:3,q:"Hány féle gyógynövényből készül az Unicum?",a:40,unit:"féle",note:"a pontos recept titkos"},
{cat:6,type:'tip',d:3,q:"Legfeljebb hány puttonyos lehetett a tokaji aszú a klasszikus skálán?",a:6,unit:"puttonyos",note:""},
{cat:6,type:'tip',d:3,q:"Melyik évben került piacra Magyarországon a Túró Rudi?",a:1968,unit:"",note:"A pöttyös csomagolás azóta is védjegye."},
{cat:6,type:'tip',d:3,q:"Melyik évben vették fel a tokaji történelmi borvidéket az UNESCO világörökségi listájára?",a:2002,unit:"",note:"Kultúrtáj kategóriában nyerte el a címet."},
{cat:6,type:'tip',d:3,q:"Melyik évben nyitotta meg kapuit a budapesti New York kávéház?",a:1894,unit:"",note:"A legenda szerint Molnár Ferenc a Dunába dobta a kulcsát, hogy sose zárjon be."},
{cat:6,type:'tip',d:3,q:"Melyik évben alapította Törley József pezsgőpincészetét Budafokon?",a:1882,unit:"",note:"A Törley máig a legismertebb magyar pezsgőmárka."},
{cat:6,type:'tip',d:3,q:"Melyik évben alapították a herendi porcelánmanufaktúrát?",a:1826,unit:"",note:"A herendi porcelán a hungarikumok egyike."},
{cat:6,type:'tip',d:3,q:"Melyik évben vette át Gundel Károly a városligeti éttermet, a mai Gundel elődjét?",a:1910,unit:"",note:"Korábban Wampetics-vendéglőként működött."},
{cat:6,type:'tip',d:4,q:"Melyik évben mutatták be a Dobos-tortát a budapesti Országos Kiállításon?",a:1885,unit:"",note:"Dobos C. József cukrászmester alkotása"},
{cat:6,type:'tip',d:4,q:"Hány liter bor fér egy hagyományos gönci hordóba?",a:136,unit:"liter",note:"a tokaji aszú klasszikus hordója"},
{cat:6,type:'tip',d:4,q:"Melyik évben aratott díjnyertes sikert a somlói galuska a brüsszeli világkiállításon?",a:1958,unit:"",note:"A desszert a Gundel étterem munkatársainak ötletéből született."},
{cat:6,type:'tip',d:4,q:"A világ libamájtermelésének körülbelül hány százalékát adja Magyarország?",a:80,unit:"%",note:"A libamáj (hízott lúdmáj) terén Magyarország világelső; a kacsamájat is beszámítva Franciaország vezet"},
{cat:6,type:'tip',d:5,q:"Melyik évben jelent meg az első magyar nyelvű nyomtatott szakácskönyv, a „Szakáts mesterségnek könyvetskéje”?",a:1695,unit:"",note:"Misztótfalusi Kis Miklós adta ki Kolozsváron."},
{cat:6,type:'tip',d:5,q:"Legalább hány gramm természetes cukrot kell literenként tartalmaznia a tokaji eszenciának?",a:450,unit:"g",note:"Ezért inkább sűrű, nektárszerű különlegesség, mint hagyományos bor."},

// ---------- 7. Világtörténelem ⚔️ ----------
// – 1 a 4-ből (30 db) –
{cat:7,type:'mc',d:1,q:"Ki volt az Amerikai Egyesült Államok első elnöke?",
 o:["George Washington","Thomas Jefferson","Abraham Lincoln","Benjamin Franklin"], c:0},
{cat:7,type:'mc',d:1,q:"Ki koronáztatta magát Franciaország császárává 1804-ben?",
 o:["Bonaparte Napóleon","XIV. Lajos","III. Napóleon","Robespierre"], c:0},
{cat:7,type:'mc',d:1,q:"Ki vezette a Szovjetuniót a második világháború idején?",
 o:["Sztálin","Lenin","Hruscsov","Brezsnyev"], c:0},
{cat:7,type:'mc',d:2,q:"Melyik ország uralkodója volt VIII. Henrik, a hat feleségéről is híres király?",
 o:["Anglia","Franciaország","Spanyolország","Skócia"], c:0},
{cat:7,type:'mc',d:2,q:"Hol szállt partra a szövetséges haderő 1944. június 6-án, a D-napon?",
 o:["Normandiában","Szicíliában","Provence-ban","Hollandiában"], c:0},
{cat:7,type:'mc',d:2,q:"Melyik városban gyilkolták meg Ferenc Ferdinánd trónörököst 1914-ben?",
 o:["Szarajevóban","Belgrádban","Bécsben","Zágrábban"], c:0},
{cat:7,type:'mc',d:2,q:"Melyik ország uralkodója volt XIV. Lajos, a „Napkirály”?",
 o:["Franciaország","Spanyolország","Anglia","Ausztria"], c:0},
{cat:7,type:'mc',d:2,q:"Melyik egyiptomi királynő volt Julius Caesar, majd Marcus Antonius szövetségese?",
 o:["VII. Kleopátra","Nofertiti","Hatsepszut","Nefertari"], c:0},
{cat:7,type:'mc',d:2,q:"Melyik római hadvezér mondta állítólag a Rubicon átlépésekor: „A kocka el van vetve”?",
 o:["Julius Caesar","Augustus","Pompeius","Marcus Antonius"], c:0},
{cat:7,type:'mc',d:3,q:"Melyik csatában szenvedett végső vereséget Napóleon 1815-ben?",
 o:["a waterlooi csatában","az austerlitzi csatában","a lipcsei csatában","a borogyinói csatában"], c:0},
{cat:7,type:'mc',d:3,q:"Melyik ókori városban voltak a világ hét csodája közé sorolt függőkertek?",
 o:["Babilonban","Alexandriában","Epheszoszban","Rodoszon"], c:0},
{cat:7,type:'mc',d:3,q:"Ki ült Anglia trónján a spanyol Armada 1588-as legyőzésekor?",
 o:["I. Erzsébet","Viktória","I. (Véres) Mária","Stuart Mária"], c:0},
{cat:7,type:'mc',d:3,q:"Kinek a nevéhez kötik elsősorban a jakobinus terrort a francia forradalomban?",
 o:["Robespierre-éhez","Dantonéhoz","Marat-éhoz","Mirabeau-éhoz"], c:0},
{cat:7,type:'mc',d:3,q:"Melyik indián birodalmat igázta le Hernán Cortés?",
 o:["az aztékot","az inkát","a maját","a toltéket"], c:0},
{cat:7,type:'mc',d:3,q:"Melyik karthágói hadvezér kelt át i. e. 218-ban elefántjaival az Alpokon, hogy megtámadja Rómát?",
 o:["Hannibál","Hasdrubal","Hamilkar Barkasz","Mago"], c:0},
{cat:7,type:'mc',d:3,q:"Melyik szovjet vezető mondta el 1956-ban a Sztálin bűneit feltáró „titkos beszédet”?",
 o:["Hruscsov","Brezsnyev","Malenkov","Bulganyin"], c:0},
{cat:7,type:'mc',d:3,q:"Melyik országban vívták a rózsák háborúját a 15. században?",
 o:["Angliában","Franciaországban","Spanyolországban","Skóciában"], c:0},
{cat:7,type:'mc',d:3,q:"Ki volt az Egyesült Államok elnöke az amerikai polgárháború idején?",
 o:["Abraham Lincoln","Ulysses S. Grant","Andrew Jackson","Thomas Jefferson"], c:0},
{cat:7,type:'mc',d:3,q:"Melyik békeszerződés zárta le az első világháborút a győztesek és Németország között?",
 o:["a versailles-i béke","a saint-germaini béke","a sèvres-i béke","a breszt-litovszki béke"], c:0},
{cat:7,type:'mc',d:3,q:"Melyik orosz uralkodó alapította Szentpétervárt?",
 o:["I. (Nagy) Péter","Rettegett Iván","II. (Nagy) Katalin","I. Sándor"], c:0},
{cat:7,type:'mc',d:3,q:"Melyik hajós érte el elsőként tengeri úton Indiát Afrika megkerülésével?",
 o:["Vasco da Gama","Bartolomeu Dias","Kolumbusz Kristóf","Amerigo Vespucci"], c:0},
{cat:7,type:'mc',d:4,q:"Ki volt Kína első császára, aki egyesítette az országot és megkezdte a Nagy Fal kiépítését?",
 o:["Csin Si Huang-ti","Kubiláj kán","Liu Pang","Han Vu-ti"], c:0},
{cat:7,type:'mc',d:4,q:"Melyik államférfi nevéhez kötődik az athéni demokrácia fénykora az i. e. 5. században?",
 o:["Periklész","Szolón","Themisztoklész","Kleiszthenész"], c:0},
{cat:7,type:'mc',d:4,q:"Melyik szerződésben osztotta fel egymás között Spanyolország és Portugália az Európán kívüli világot 1494-ben?",
 o:["a tordesillasi szerződésben","a zaragozai szerződésben","az utrechti békében","a cateau-cambrésis-i békében"], c:0},
{cat:7,type:'mc',d:4,q:"Ki volt a Nyugatrómai Birodalom utolsó császára?",
 o:["Romulus Augustulus","Honorius","III. Valentinianus","Theodosius"], c:0},
{cat:7,type:'mc',d:4,q:"Melyik uralkodóházból származott XVI. Lajos, a francia forradalom idején kivégzett király?",
 o:["a Bourbon-házból","a Valois-házból","az Orléans-i házból","a Habsburg-házból"], c:0},
{cat:7,type:'mc',d:4,q:"Melyik dinasztia utolsó uralkodója volt II. Miklós orosz cár?",
 o:["a Romanov-dinasztiáé","a Rurik-dinasztiáé","a Godunov-dinasztiáé","a Jagelló-dinasztiáé"], c:0},
{cat:7,type:'mc',d:5,q:"Melyik amerikai elnök hivatali ideje alatt vásárolta meg az USA Alaszkát Oroszországtól?",
 o:["Andrew Johnson","Abraham Lincoln","Ulysses S. Grant","James Buchanan"], c:0},
{cat:7,type:'mc',d:5,q:"Melyik pápa hirdette meg az első keresztes hadjáratot 1095-ben?",
 o:["II. Orbán","VII. Gergely","III. Ince","II. Paszkál"], c:0},
{cat:7,type:'mc',d:5,q:"Mi volt a neve a Hirosimára atombombát ledobó amerikai bombázónak?",
 o:["Enola Gay","Bockscar","Memphis Belle","Spirit of St. Louis"], c:0},
// – tippelős (40 db) –
{cat:7,type:'tip',d:1,q:"Melyik évben fedezte fel Kolumbusz Amerikát?",a:1492,unit:"",note:""},
{cat:7,type:'tip',d:1,q:"Melyik évben ért véget a második világháború?",a:1945,unit:"",note:"Európában májusban, Ázsiában szeptemberben fejeződtek be a harcok."},
{cat:7,type:'tip',d:1,q:"Melyik évben tört ki a második világháború?",a:1939,unit:"",note:"Szeptember 1-jén Németország megtámadta Lengyelországot."},
{cat:7,type:'tip',d:1,q:"Melyik évben tört ki a francia forradalom?",a:1789,unit:"",note:"Július 14-én a párizsi nép elfoglalta a Bastille erődjét."},
{cat:7,type:'tip',d:2,q:"Melyik évben omlott le a berlini fal?",a:1989,unit:"",note:"november 9-én"},
{cat:7,type:'tip',d:2,q:"Melyik évben tört ki az első világháború?",a:1914,unit:"",note:"A négyéves háború végére négy birodalom omlott össze."},
{cat:7,type:'tip',d:2,q:"Melyik évben süllyedt el a Titanic?",a:1912,unit:"",note:"Az óceánjáró az első útján, jéghegynek ütközve süllyedt el az Atlanti-óceánon."},
{cat:7,type:'tip',d:2,q:"Időszámításunk előtt melyik évben gyilkolták meg Julius Caesart a római szenátusban?",a:44,unit:"",note:"Március idusán, azaz március 15-én történt a merénylet."},
{cat:7,type:'tip',d:2,q:"Melyik évben ért véget az első világháború?",a:1918,unit:"",note:"November 11-én írták alá a fegyverszünetet Compiègne-nél."},
{cat:7,type:'tip',d:2,q:"Melyik évben tette közzé Luther Márton a 95 tételét, elindítva a reformációt?",a:1517,unit:"",note:"A hagyomány szerint a wittenbergi vártemplom kapujára szegezte ki."},
{cat:7,type:'tip',d:2,q:"Melyik évben kezdték el építeni a berlini falat?",a:1961,unit:"",note:"Egyetlen éjszaka alatt zárták le a határt Kelet- és Nyugat-Berlin között."},
{cat:7,type:'tip',d:2,q:"Melyik évben végezték ki XVI. Lajos francia királyt?",a:1793,unit:"",note:"A forradalom alatt guillotine-nal végezték ki Párizsban."},
{cat:7,type:'tip',d:3,q:"Melyik évben koronázták császárrá Nagy Károlyt Rómában?",a:800,unit:"",note:"karácsony napján"},
{cat:7,type:'tip',d:3,q:"Melyik évben foglalták el az oszmánok Konstantinápolyt?",a:1453,unit:"",note:"Az eseményt sok történész a középkor végének egyik jelképes dátumaként tartja számon."},
{cat:7,type:'tip',d:3,q:"Hány éves korában halt meg Nagy Sándor?",a:32,unit:"év",note:"Babilonban érte a halál i. e. 323-ban, birodalma hamarosan felbomlott."},
{cat:7,type:'tip',d:3,q:"Melyik évben ragadták magukhoz a hatalmat a bolsevikok Oroszországban?",a:1917,unit:"",note:"A régi orosz naptár szerint októberi forradalomként emlegetik, bár a Gergely-naptár szerint novemberben történt."},
{cat:7,type:'tip',d:3,q:"Melyik évben győzött Hódító Vilmos a hastingsi csatában?",a:1066,unit:"",note:"A normann hódítás alapjaiban formálta át Angliát és az angol nyelvet."},
{cat:7,type:'tip',d:3,q:"Melyik évben nyitották meg a Szuezi-csatornát?",a:1869,unit:"",note:"A csatorna több ezer kilométerrel rövidítette le az Európa és Ázsia közötti hajóutat."},
{cat:7,type:'tip',d:3,q:"Melyik évben fogadták el az amerikai Függetlenségi nyilatkozatot?",a:1776,unit:"",note:"Július 4-e azóta az Egyesült Államok nemzeti ünnepe."},
{cat:7,type:'tip',d:3,q:"Melyik évben adta ki Földnélküli János angol király a Magna Cartát?",a:1215,unit:"",note:"A királyi hatalmat korlátozó oklevél a jogállamiság egyik alapdokumentuma."},
{cat:7,type:'tip',d:3,q:"Melyik évben bukott meg a Nyugatrómai Birodalom?",a:476,unit:"",note:"Odoaker ekkor mondatta le az utolsó császárt, Romulus Augustulust."},
{cat:7,type:'tip',d:3,q:"Melyik évben tört ki a nagy gazdasági világválság a New York-i tőzsdekrachhal?",a:1929,unit:"",note:"Az összeomlás napját „fekete csütörtökként” emlegetik."},
{cat:7,type:'tip',d:3,q:"Melyik évben gyilkolták meg John F. Kennedy amerikai elnököt?",a:1963,unit:"",note:"A merénylet a texasi Dallasban történt, nyílt utcán."},
{cat:7,type:'tip',d:3,q:"Melyik évben írták alá az első világháborút lezáró versailles-i békeszerződést?",a:1919,unit:"",note:"A tükörteremben írták alá, ahol 1871-ben a Német Császárságot kikiáltották."},
{cat:7,type:'tip',d:3,q:"Melyik évben pusztította el egy vulkánkitörés Pompeji városát?",a:79,unit:"",note:"A várost méteres hamuréteg temette be, ez őrizte meg az utókornak."},
{cat:7,type:'tip',d:3,q:"Melyik évben kötött ki Amerikában a Mayflower a zarándok atyákkal?",a:1620,unit:"",note:"Utasaik alapították Plymouth kolóniáját a mai Massachusetts területén."},
{cat:7,type:'tip',d:3,q:"Melyik évben törölték el az Egyesült Államokban a rabszolgaságot?",a:1865,unit:"",note:"A 13. alkotmánykiegészítés mondta ki, a polgárháború végén."},
{cat:7,type:'tip',d:3,q:"Melyik évben bomlott fel a Szovjetunió?",a:1991,unit:"",note:"December 25-én Gorbacsov lemondott, és bevonták a vörös zászlót a Kreml felett."},
{cat:7,type:'tip',d:4,q:"Valójában hány évig tartott a „százéves háború”?",a:116,unit:"év",note:"1337–1453"},
{cat:7,type:'tip',d:4,q:"Melyik évben kezdődött a harmincéves háború?",a:1618,unit:"",note:"A prágai defenesztráció, vagyis a királyi helytartók ablakon való kihajítása robbantotta ki."},
{cat:7,type:'tip',d:4,q:"Hány napig tartott 1962-ben a kubai rakétaválság?",a:13,unit:"nap",note:"A hidegháború alatt ekkor állt a világ a legközelebb az atomháborúhoz."},
{cat:7,type:'tip',d:4,q:"Hány évig uralkodott Viktória brit királynő?",a:63,unit:"év",note:"1837-től 1901-ig ült a trónon; uralkodása alatt lett Nagy-Britannia a világ vezető nagyhatalma."},
{cat:7,type:'tip',d:4,q:"Melyik évben választották nagykánná Dzsingisz kánt?",a:1206,unit:"",note:"Innen számítjuk a Mongol Birodalom megszületését."},
{cat:7,type:'tip',d:4,q:"Melyik évben zárta le a vesztfáliai béke a harmincéves háborút?",a:1648,unit:"",note:"A béke rajzolta újra Európa vallási és politikai térképét."},
{cat:7,type:'tip',d:4,q:"Melyik évben győzte le a keresztény flotta az oszmánt a lepantói tengeri csatában?",a:1571,unit:"",note:"A csatában harcolt a Don Quijote írója, Cervantes is, és megsebesült."},
{cat:7,type:'tip',d:4,q:"Melyik évben ismerte el Nagy-Britannia az Egyesült Államok függetlenségét a párizsi békében?",a:1783,unit:"",note:"Ezzel ért véget az amerikai függetlenségi háború."},
{cat:7,type:'tip',d:5,q:"Melyik évben indult el Magellán flottája az első Föld körüli hajóútra?",a:1519,unit:"",note:"Magellán maga nem élte túl az utat; a Victoria nevű hajó 1522-ben tért vissza Spanyolországba."},
{cat:7,type:'tip',d:5,q:"Melyik évben zajlottak a salemi boszorkányperek Új-Angliában?",a:1692,unit:"",note:"A vádaskodási hullámnak húsz halálos áldozata volt."},
{cat:7,type:'tip',d:5,q:"Melyik évben osztotta három részre a verduni szerződés a Frank Birodalmat?",a:843,unit:"",note:"A felosztásból formálódott ki a későbbi Franciaország és Németország."},
{cat:7,type:'tip',d:5,q:"Melyik évben állította meg Martell Károly az arab előrenyomulást a poitiers-i csatában?",a:732,unit:"",note:"A győzelem után Nyugat-Európában megállt az arab terjeszkedés."},

// ---------- 8. Világföldrajz 🌍 ----------
// – 1 a 4-ből (30 db) –
{cat:8,type:'mc',d:1,q:"Melyik a Föld legnagyobb óceánja?",
 o:["Csendes-óceán","Atlanti-óceán","Indiai-óceán","Jeges-tenger"], c:0},
{cat:8,type:'mc',d:1,q:"Melyik a világ legnagyobb területű országa?",
 o:["Oroszország","Kanada","Kína","Amerikai Egyesült Államok"], c:0},
{cat:8,type:'mc',d:1,q:"Melyik a világ legnagyobb forró sivataga?",
 o:["Szahara","Góbi","Kalahári","Atacama"], c:0},
{cat:8,type:'mc',d:1,q:"Mely kontinensek határán fekszik Isztambul?",
 o:["Európa és Ázsia","Ázsia és Afrika","Európa és Afrika","Egyik határán sem"], c:0},
{cat:8,type:'mc',d:2,q:"Melyik ország fővárosa Canberra?",
 o:["Ausztrália","Kanada","Új-Zéland","Ausztria"], c:0},
{cat:8,type:'mc',d:2,q:"Melyik kontinensen folyik az Amazonas?",
 o:["Dél-Amerika","Afrika","Ázsia","Észak-Amerika"], c:0},
{cat:8,type:'mc',d:2,q:"Melyik országban található a Vezúv?",
 o:["Olaszország","Görögország","Spanyolország","Törökország"], c:0},
{cat:8,type:'mc',d:2,q:"Melyik óceán választja el Európát Észak-Amerikától?",
 o:["Atlanti-óceán","Csendes-óceán","Indiai-óceán","Jeges-tenger"], c:0},
{cat:8,type:'mc',d:2,q:"Melyik folyó folyik keresztül Párizson?",
 o:["Szajna","Loire","Rajna","Temze"], c:0},
{cat:8,type:'mc',d:3,q:"Melyik országban található a Kilimandzsáró?",
 o:["Tanzánia","Kenya","Etiópia","Uganda"], c:0},
{cat:8,type:'mc',d:3,q:"Melyik ország fővárosa Ottawa?",
 o:["Kanada","Ausztrália","Új-Zéland","Dél-afrikai Köztársaság"], c:0},
{cat:8,type:'mc',d:3,q:"Melyik a Föld legmélyebb tava?",
 o:["Bajkál-tó","Tanganyika-tó","Kaszpi-tenger","Felső-tó"], c:0},
{cat:8,type:'mc',d:3,q:"Melyik hegység alkotja a hagyományos határt Európa és Ázsia között?",
 o:["Urál","Himalája","Altaj","Tien-san"], c:0},
{cat:8,type:'mc',d:3,q:"Melyik országban ered a Duna?",
 o:["Németország","Ausztria","Svájc","Csehország"], c:0},
{cat:8,type:'mc',d:3,q:"Melyik tengerszoros választja el Európát Afrikától?",
 o:["Gibraltári-szoros","Boszporusz","Dardanellák","Messinai-szoros"], c:0},
{cat:8,type:'mc',d:3,q:"Melyik ország fővárosa Wellington?",
 o:["Új-Zéland","Ausztrália","Fidzsi","Pápua Új-Guinea"], c:0},
{cat:8,type:'mc',d:3,q:"Melyik országban található az Atacama-sivatag?",
 o:["Chile","Peru","Argentína","Mexikó"], c:0},
{cat:8,type:'mc',d:3,q:"Melyik folyó vájta ki a Grand Canyont?",
 o:["Colorado","Mississippi","Rio Grande","Columbia"], c:0},
{cat:8,type:'mc',d:3,q:"Melyik országhoz tartozik Grönland?",
 o:["Dánia","Norvégia","Kanada","Izland"], c:0},
{cat:8,type:'mc',d:3,q:"Melyik országban található a Machu Picchu?",
 o:["Peru","Bolívia","Ecuador","Mexikó"], c:0},
{cat:8,type:'mc',d:3,q:"Melyik tengerbe torkollik a Nílus?",
 o:["Földközi-tenger","Vörös-tenger","Fekete-tenger","Arab-tenger"], c:0},
{cat:8,type:'mc',d:4,q:"Melyik ország fővárosa Najpjidó (Naypyidaw)?",
 o:["Mianmar","Laosz","Kambodzsa","Banglades"], c:0},
{cat:8,type:'mc',d:4,q:"Melyik két ország határán fekszik a Titicaca-tó?",
 o:["Peru és Bolívia","Chile és Argentína","Ecuador és Kolumbia","Brazília és Paraguay"], c:0},
{cat:8,type:'mc',d:4,q:"Mi Ausztrália szárazföldjének legmagasabb csúcsa?",
 o:["Mount Kosciuszko","Mount Bogong","Uluru","Mount Cook"], c:0},
{cat:8,type:'mc',d:4,q:"Melyik a világ legmagasabb vízesése?",
 o:["Angel-vízesés","Viktória-vízesés","Niagara-vízesés","Iguazú-vízesés"], c:0},
{cat:8,type:'mc',d:4,q:"Melyik országban emelkedik az Atlasz-hegység legmagasabb csúcsa, a Toubkal?",
 o:["Marokkó","Algéria","Tunézia","Egyiptom"], c:0},
{cat:8,type:'mc',d:4,q:"Melyik tó partvidéke a Föld legalacsonyabban fekvő szárazföldi területe?",
 o:["Holt-tenger","Kaszpi-tenger","Asszál-tó","Aral-tó"], c:0},
{cat:8,type:'mc',d:5,q:"Melyik a Föld második legnagyobb szigete?",
 o:["Új-Guinea","Borneó","Madagaszkár","Baffin-sziget"], c:0},
{cat:8,type:'mc',d:5,q:"Mi Kanada legmagasabb hegycsúcsa?",
 o:["Mount Logan","Denali","Mount Robson","Mount Columbia"], c:0},
{cat:8,type:'mc',d:5,q:"Melyik nagy folyó szeli át kétszer is az Egyenlítőt?",
 o:["Kongó","Nílus","Amazonas","Niger"], c:0},
// – tippelős (21 db) –
{cat:8,type:'tip',d:1,q:"Hány tagállamból áll az Amerikai Egyesült Államok?",a:50,unit:"db",note:""},
{cat:8,type:'tip',d:1,q:"Hány tagországa maradt az Európai Uniónak az Egyesült Királyság 2020-as kilépése (brexit) után?",a:27,unit:"db",note:"Az Egyesült Királyság 2020-as kilépése óta."},
{cat:8,type:'tip',d:2,q:"Hány méter magas a Mount Everest?",a:8849,unit:"m",note:"a 2020-as hivatalos mérés szerint 8848,86 m"},
{cat:8,type:'tip',d:2,q:"Hány független ország található Dél-Amerikában?",a:12,unit:"db",note:"Francia Guyana nem önálló állam, hanem Franciaország tengerentúli megyéje."},
{cat:8,type:'tip',d:2,q:"Milyen széles a La Manche csatorna a legkeskenyebb pontján?",a:34,unit:"km",note:"A Doveri-szorosnál, Dover és Calais között."},
{cat:8,type:'tip',d:2,q:"Hány országgal határos Németország?",a:9,unit:"db",note:"Ezzel az európai élmezőnybe tartozik."},
{cat:8,type:'tip',d:3,q:"Hány ország található Afrikában?",a:54,unit:"",note:""},
{cat:8,type:'tip',d:3,q:"Hány kilométer hosszú az Egyenlítő?",a:40075,unit:"km",note:"kb. 40 075 km"},
{cat:8,type:'tip',d:3,q:"Hány időzóna van Oroszországban?",a:11,unit:"",note:""},
{cat:8,type:'tip',d:3,q:"Milyen hosszú a Nílus?",a:6650,unit:"km",note:""},
{cat:8,type:'tip',d:3,q:"Hány méter magas a Mont Blanc?",a:4808,unit:"m",note:"A csúcs jégsapkája miatt a hivatalos érték néhány métert ingadozik."},
{cat:8,type:'tip',d:3,q:"Mekkora Ausztrália területe?",a:7692000,unit:"km²",note:"A Föld hatodik legnagyobb országa."},
{cat:8,type:'tip',d:3,q:"Hány méter magas a Kilimandzsáró?",a:5895,unit:"m",note:"Afrika legmagasabb hegye."},
{cat:8,type:'tip',d:3,q:"Hány méter magas a Fudzsi, Japán legmagasabb hegye?",a:3776,unit:"m",note:""},
{cat:8,type:'tip',d:3,q:"Melyik évben nyílt meg a La Manche csatorna alatti Csalagút?",a:1994,unit:"",note:"Nagy-Britanniát és Franciaországot köti össze a tenger alatt."},
{cat:8,type:'tip',d:4,q:"Hány méter mély az óceánok legmélyebb pontja, a Mariana-árokban található Challenger-szakadék?",a:10935,unit:"m",note:"A modern mérések 10 900 méter körüli értékeket adnak."},
{cat:8,type:'tip',d:4,q:"Milyen hosszú a Volga?",a:3531,unit:"km",note:"Európa leghosszabb folyója."},
{cat:8,type:'tip',d:4,q:"Mekkora a Kaszpi-tenger területe?",a:371000,unit:"km²",note:"A Föld legnagyobb tava, bár tengernek nevezik."},
{cat:8,type:'tip',d:4,q:"Hány méter magas az Aconcagua, Dél-Amerika legmagasabb csúcsa?",a:6961,unit:"m",note:"Egyben a legmagasabb Ázsián kívüli hegycsúcs."},
{cat:8,type:'tip',d:5,q:"Hány méter mély a Tanganyika-tó legmélyebb pontja?",a:1470,unit:"m",note:"Afrika legmélyebb tava."},
{cat:8,type:'tip',d:5,q:"Hány méter magas az Angel-vízesés, a világ legmagasabb vízesése?",a:979,unit:"m",note:"Venezuelában, a Canaima Nemzeti Parkban zuhog alá"},

// ---------- 9. Világirodalom 📖 ----------
// – 1 a 4-ből (13 db) –
{cat:9,type:'mc',d:2,q:"Ki írta a Bűn és bűnhődést?",
 o:["Fjodor Dosztojevszkij","Lev Tolsztoj","Anton Csehov","Nyikolaj Gogol"], c:0},
{cat:9,type:'mc',d:2,q:"Ki írta a Faust című drámai költeményt?",
 o:["Johann Wolfgang von Goethe","Friedrich Schiller","Heinrich Heine","Thomas Mann"], c:0},
{cat:9,type:'mc',d:2,q:"Ki írta A kis herceg című könyvet?",
 o:["Antoine de Saint-Exupéry","Albert Camus","Jules Verne","Romain Rolland"], c:0},
{cat:9,type:'mc',d:2,q:"Ki írta az Anna Karenina című regényt?",
 o:["Lev Tolsztoj","Fjodor Dosztojevszkij","Anton Csehov","Ivan Turgenyev"], c:0},
{cat:9,type:'mc',d:3,q:"Ki írta a Száz év magány című regényt?",
 o:["Gabriel García Márquez","Jorge Luis Borges","Mario Vargas Llosa","Pablo Neruda"], c:0},
{cat:9,type:'mc',d:3,q:"Ki írta az 1984 című regényt?",
 o:["George Orwell","Aldous Huxley","Ray Bradbury","Arthur Koestler"], c:0},
{cat:9,type:'mc',d:3,q:"Ki írta Az öreg halász és a tenger című kisregényt?",
 o:["Ernest Hemingway","John Steinbeck","William Faulkner","F. Scott Fitzgerald"], c:0},
{cat:9,type:'mc',d:3,q:"Ki írta A nyomorultak című regényt?",
 o:["Victor Hugo","Émile Zola","Honoré de Balzac","Stendhal"], c:0},
{cat:9,type:'mc',d:3,q:"Ki írta a Don Quijote című regényt?",
 o:["Miguel de Cervantes","Lope de Vega","Calderón de la Barca","Federico García Lorca"], c:0},
{cat:9,type:'mc',d:3,q:"Ki írta a Twist Olivér című regényt?",
 o:["Charles Dickens","Mark Twain","Robert Louis Stevenson","Jonathan Swift"], c:0},
{cat:9,type:'mc',d:4,q:"Ki írta az Ulysses című regényt?",
 o:["James Joyce","Virginia Woolf","Samuel Beckett","D. H. Lawrence"], c:0},
{cat:9,type:'mc',d:4,q:"Ki írta A Mester és Margarita című regényt?",
 o:["Mihail Bulgakov","Borisz Paszternak","Vlagyimir Nabokov","Mihail Solohov"], c:0},
{cat:9,type:'mc',d:4,q:"Ki írta Az eltűnt idő nyomában című regényfolyamot?",
 o:["Marcel Proust","André Gide","Anatole France","Paul Valéry"], c:0},
// – tippelős (7 db) –
{cat:9,type:'tip',d:1,q:"Hány kötetből áll a Harry Potter-regénysorozat?",a:7,unit:"kötet",note:"Az utolsó kötet 2007-ben jelent meg."},
{cat:9,type:'tip',d:2,q:"Hány sorból áll egy klasszikus szonett?",a:14,unit:"sor",note:"A formát Petrarca tette világhírűvé."},
{cat:9,type:'tip',d:2,q:"Hány fő részből áll Dante Isteni színjátéka?",a:3,unit:"rész",note:"Pokol, Purgatórium, Paradicsom."},
{cat:9,type:'tip',d:3,q:"Melyik évben született William Shakespeare?",a:1564,unit:"",note:"Stratford-upon-Avonban"},
{cat:9,type:'tip',d:3,q:"Melyik évben halt meg William Shakespeare?",a:1616,unit:"",note:"A hagyomány szerint április 23-án, épp a születésnapján hunyt el."},
{cat:9,type:'tip',d:4,q:"Hány szonettet írt Shakespeare?",a:154,unit:"db",note:""},
{cat:9,type:'tip',d:4,q:"Hány énekből áll Homérosz Odüsszeiája?",a:24,unit:"ének",note:"Az Iliász szintén 24 énekből áll."},

// ---------- 10. Képzőművészet 🖼️ ----------
// – 1 a 4-ből (15 db) –
{cat:10,type:'mc',d:1,q:"Ki festette a Mona Lisát?",
 o:["Leonardo da Vinci","Michelangelo","Raffaello","Botticelli"], c:0},
{cat:10,type:'mc',d:2,q:"Ki festette a Csillagos éj című képet?",
 o:["Vincent van Gogh","Claude Monet","Pablo Picasso","Salvador Dalí"], c:0},
{cat:10,type:'mc',d:2,q:"Melyik művészeti irányzat fő képviselője volt Salvador Dalí?",
 o:["Szürrealizmus","Kubizmus","Impresszionizmus","Expresszionizmus"], c:0},
{cat:10,type:'mc',d:2,q:"Ki festette a Sixtus-kápolna mennyezetfreskóit?",
 o:["Michelangelo","Leonardo da Vinci","Raffaello","Botticelli"], c:0},
{cat:10,type:'mc',d:3,q:"Melyik városban áll Michelangelo Dávid-szobra?",
 o:["Firenze","Róma","Velence","Milánó"], c:0},
{cat:10,type:'mc',d:3,q:"Ki festette a Guernica című képet?",
 o:["Pablo Picasso","Salvador Dalí","Joan Miró","Francisco Goya"], c:0},
{cat:10,type:'mc',d:3,q:"Ki festette a Vénusz születése című képet?",
 o:["Sandro Botticelli","Tiziano","Raffaello","Caravaggio"], c:0},
{cat:10,type:'mc',d:3,q:"Ki festette a Sikoly című képet?",
 o:["Edvard Munch","Gustav Klimt","Egon Schiele","Vaszilij Kandinszkij"], c:0},
{cat:10,type:'mc',d:3,q:"Melyik művészeti irányzat képviselője volt Claude Monet?",
 o:["impresszionizmus","expresszionizmus","kubizmus","szürrealizmus"], c:0},
{cat:10,type:'mc',d:3,q:"Ki festette az Éjjeli őrjárat című képet?",
 o:["Rembrandt","Jan Vermeer","Frans Hals","Peter Paul Rubens"], c:0},
{cat:10,type:'mc',d:4,q:"Ki festette Az Arnolfini házaspár című képet?",
 o:["Jan van Eyck","Rogier van der Weyden","Hieronymus Bosch","Albrecht Dürer"], c:0},
{cat:10,type:'mc',d:4,q:"Melyik szobrász alkotta az Apolló és Daphné című barokk szoborcsoportot?",
 o:["Gian Lorenzo Bernini","Antonio Canova","Donatello","Benvenuto Cellini"], c:0},
{cat:10,type:'mc',d:5,q:"Mi volt Michelangelo, a reneszánsz mester vezetékneve?",
 o:["Buonarroti","Vecellio","Sanzio","Merisi"], c:0},
{cat:10,type:'mc',d:5,q:"Ki festette a pipát ábrázoló, \"Ez nem pipa\" feliratú képet (A képek árulása)?",
 o:["René Magritte","Salvador Dalí","Max Ernst","Giorgio de Chirico"], c:0},
{cat:10,type:'mc',d:5,q:"Melyik művész állította ki Forrás címmel a művészettörténet leghíresebb piszoárját?",
 o:["Marcel Duchamp","Man Ray","Andy Warhol","Joseph Beuys"], c:0},
// – tippelős (10 db) –
{cat:10,type:'tip',d:1,q:"Hány apostol szerepel Leonardo da Vinci Az utolsó vacsora című freskóján Jézus mellett?",a:12,unit:"fő",note:"A freskó a milánói Santa Maria delle Grazie kolostor falán látható."},
{cat:10,type:'tip',d:2,q:"Melyik évben égett le a párizsi Notre-Dame székesegyház tetőszerkezete?",a:2019,unit:"",note:"A huszártorony a lángok között omlott össze."},
{cat:10,type:'tip',d:3,q:"Melyik évben kezdte el festeni Leonardo a Mona Lisát?",a:1503,unit:"",note:""},
{cat:10,type:'tip',d:3,q:"Melyik évben halt meg Vincent van Gogh?",a:1890,unit:"",note:"37 évesen"},
{cat:10,type:'tip',d:3,q:"Melyik évben született Leonardo da Vinci?",a:1452,unit:"",note:"A toszkánai Vinci település közelében született."},
{cat:10,type:'tip',d:3,q:"Melyik évben halt meg Pablo Picasso?",a:1973,unit:"",note:"91 évet élt."},
{cat:10,type:'tip',d:3,q:"Melyik évben halt meg Michelangelo?",a:1564,unit:"",note:"Rómában hunyt el, 88 évesen."},
{cat:10,type:'tip',d:4,q:"Melyik évben nyílt meg múzeumként a párizsi Louvre?",a:1793,unit:"",note:"A francia forradalom idején nyitották meg a nagyközönség előtt."},
{cat:10,type:'tip',d:4,q:"Melyik évben kezdték építeni a barcelonai Sagrada Famíliát?",a:1882,unit:"",note:"Antoni Gaudí egy évvel később vette át a tervezést."},
{cat:10,type:'tip',d:5,q:"Melyik évben született Rembrandt?",a:1606,unit:"",note:"Leidenben született, egy molnár fiaként."},
