// KvízParty kérdésbázis – 4/5 darab (kategóriák: 13–16)
// ---------- 13. Magyar tévé és média ----------
{cat:13,type:'mc',d:1,q:"Ki vezette a Legyen Ön is milliomos! című vetélkedőt?",
 o:["Vágó István","Friderikusz Sándor","Fábry Sándor","Rózsa György"], c:0},
{cat:13,type:'mc',d:2,q:"Melyik csatornán indult el a Való Világ első szériája 2002-ben?",
 o:["RTL Klub","TV2","Viasat3","ATV"], c:0},
{cat:13,type:'mc',d:2,q:"Az alábbiak közül ki volt a Heti Hetes állandó szereplője?",
 o:["Gálvölgyi János","Fábry Sándor","Hajós András","Sebestyén Balázs"], c:0},
{cat:13,type:'mc',d:2,q:"Melyik rádióban fut a Balázsék című reggeli műsor 2016 óta?",
 o:["Rádió 1","Class FM","Petőfi Rádió","Kossuth Rádió"], c:0},
{cat:13,type:'mc',d:2,q:"Ki alakítja Besenyő Pista bácsit?",
 o:["Laár András","Galla Miklós","Dolák-Saly Róbert","Szászi Móni"], c:0},
{cat:13,type:'mc',d:2,q:"Melyik műsor előtt jelent meg esténként a TV Maci a Magyar Televízióban?",
 o:["Az Esti mese előtt","A Híradó előtt","A reggeli torna előtt","A délutáni matiné előtt"], c:0},
{cat:13,type:'mc',d:2,q:"Milyen állat volt Mazsola, aki Manócskával lakott a tökházban a legendás bábfilmsorozatban?",
 o:["Kismalac","Nyuszi","Kiskutya","Egérke"], c:0},
{cat:13,type:'mc',d:2,q:"Melyik bábsorozatban szerepelt Böbe baba és Cicamica?",
 o:["Futrinka utca","Mazsola és Tádé","Süsü, a sárkány","A Mézga család"], c:0},
{cat:13,type:'mc',d:3,q:"Melyik vetélkedő fűződik Rózsa György nevéhez?",
 o:["Kapcsoltam","Szerencsekerék","Játék határok nélkül","Telemázli"], c:0},
{cat:13,type:'mc',d:3,q:"Melyik budapesti lakótelepen játszódott a Szomszédok című teleregény?",
 o:["Gazdagrét","Békásmegyer","Havanna-lakótelep","Káposztásmegyer"], c:0},
{cat:13,type:'mc',d:3,q:"Mi volt a Magyar Televízió legendás tudományos híradójának a neve?",
 o:["Delta","Gamma","Omega","Szigma"], c:0},
{cat:13,type:'mc',d:3,q:"Ki vezette az Esti Showder című szórakoztató műsort?",
 o:["Fábry Sándor","Hajós András","Sebestyén Balázs","Majoros Péter (Majka)"], c:0},
{cat:13,type:'mc',d:3,q:"Ki volt a Csak ülök és mesélek című legendás beszélgetőműsor házigazdája?",
 o:["Vitray Tamás","Friderikusz Sándor","Antal Imre","Vágó István"], c:0},
{cat:13,type:'mc',d:3,q:"Ki nyerte meg a Megasztár legelső szériáját?",
 o:["Tóth Vera","Rúzsa Magdolna","Molnár Ferenc Caramel","Oláh Ibolya"], c:0},
{cat:13,type:'mc',d:3,q:"Melyik csatorna sugározta a Mónika show című délutáni talkshow-t?",
 o:["RTL Klub","TV2","Viasat3","ATV"], c:0},
{cat:13,type:'mc',d:3,q:"Melyik csatornán futott 2002-ben a Big Brother első magyar szériája?",
 o:["TV2","RTL Klub","Viasat3","MTV"], c:0},
{cat:13,type:'mc',d:3,q:"Ki írta a Pom Pom meséi és A nagy ho-ho-ho-horgász figuráit életre hívó meséket?",
 o:["Csukás István","Lázár Ervin","Janikovszky Éva","Marék Veronika"], c:0},
{cat:13,type:'mc',d:3,q:"Ki írta a Frédi és Béni, avagy a két kőkorszaki szaki rímes magyar szinkronszövegét?",
 o:["Romhányi József","Devecseri Gábor","Örkény István","Heltai Jenő"], c:0},
{cat:13,type:'mc',d:3,q:"Melyik tanár vált országosan híressé a Magyar Televízióban bemutatott látványos fizikai kísérleteivel?",
 o:["Öveges József","Marx György","Simonyi Károly","Szent-Györgyi Albert"], c:0},
{cat:13,type:'mc',d:3,q:"Ki játszotta a címszerepet a Linda című akció-vígjátéksorozatban?",
 o:["Görbe Nóra","Esztergályos Cecília","Bánsági Ildikó","Pécsi Ildikó"], c:0},
{cat:13,type:'mc',d:3,q:"Melyik színész kölcsönözte Süsü, a sárkány hangját?",
 o:["Bodrogi Gyula","Márkus László","Sinkovits Imre","Csákányi László"], c:0},
{cat:13,type:'mc',d:4,q:"Ki volt a Magyar népmesék rajzfilmsorozat sorozatrendezője és tervezője?",
 o:["Jankovics Marcell","Dargay Attila","Nepp József","Foky Ottó"], c:0},
{cat:13,type:'mc',d:4,q:"Ki volt a Kék fény című bűnügyi magazinműsor legendás műsorvezetője évtizedeken át?",
 o:["Szabó László","Juszt László","Kepes András","Frei Tamás"], c:0},
{cat:13,type:'mc',d:4,q:"Melyik budapesti téren állt a Magyar Televízió egykori, tőzsdepalotából átalakított székháza?",
 o:["Szabadság tér","Kossuth tér","Blaha Lujza tér","Hősök tere"], c:0},
{cat:13,type:'mc',d:4,q:"Milyen nyelven kezdte meg adását 1986-ban a Danubius Rádió, elsősorban a balatoni turistáknak szánva?",
 o:["Németül","Angolul","Oroszul","Olaszul"], c:0},
{cat:13,type:'mc',d:4,q:"Ki nyerte meg a magyar X-Faktor legelső évadát?",
 o:["Vastag Csaba","Kocsis Tibor","Király Viktor","Muri Enikő"], c:0},
{cat:13,type:'mc',d:4,q:"Ki vezette a TV2 Áll az alku című vetélkedőjét?",
 o:["Gundel Takács Gábor","Palik László","Rókusfalvy Pál","Stohl András"], c:0},
{cat:13,type:'mc',d:5,q:"Milyen művészi végzettséggel rendelkezett Antal Imre, a Szeszélyes évszakok legendás műsorvezetője?",
 o:["Zongoraművész volt","Operaénekes volt","Balett-táncos volt","Hegedűművész volt"], c:0},
{cat:13,type:'mc',d:5,q:"Melyik utcában állt a Magyar Rádió történelmi székháza Budapesten?",
 o:["Bródy Sándor utca","Krúdy Gyula utca","Múzeum utca","Puskin utca"], c:0},
{cat:13,type:'mc',d:5,q:"Mi volt a hivatalos jelzése Köbükinek, a Mézga család 30. századi rokonának?",
 o:["MZ/X","XM/2","ZM/K","MX/Y"], c:0},
{cat:13,type:'tip',d:1,q:"Hány állandó szereplő ült egyszerre a Heti Hetes asztalánál?",a:7,unit:"fő",note:"Innen a műsor címe: heti hét ember a hét híreiről."},
{cat:13,type:'tip',d:1,q:"Hány válaszlehetőség közül választhatott a játékos egy-egy kérdésnél a Legyen Ön is milliomos! című vetélkedőben?",a:4,unit:"válaszlehetőség",note:"A, B, C vagy D — a nagy kérdés mindig ez volt."},
{cat:13,type:'tip',d:2,q:"Melyik évben indult el az RTL Klubon a Barátok közt?",a:1998,unit:"",note:"Több mint két évtizeden át, 2021-ig futott."},
{cat:13,type:'tip',d:2,q:"Hány országos csatornája volt a Magyar Televíziónak a rendszerváltás idején?",a:2,unit:"csatorna",note:"Az MTV1 és az MTV2."},
{cat:13,type:'tip',d:2,q:"Melyik évben startolt el a Való Világ legelső szériája?",a:2002,unit:"",note:"Az első széria győztese VV Szabolcs lett."},
{cat:13,type:'tip',d:2,q:"Hány mentor ült a zsűriben a magyar X-Faktor egy-egy évadában?",a:4,unit:"mentor",note:""},
{cat:13,type:'tip',d:3,q:"Melyik évben indult el az RTL Klub és a TV2?",a:1997,unit:"",note:"mindkettő 1997 októberében"},
{cat:13,type:'tip',d:3,q:"Melyik évben indult el a magyar X-Faktor első évada?",a:2010,unit:"",note:""},
{cat:13,type:'tip',d:3,q:"Melyik évben rendezték meg az első Ki mit tud? tehetségkutató vetélkedőt a Magyar Televízióban?",a:1962,unit:"",note:"Évtizedekig ez volt az ország legnézettebb műsora."},
{cat:13,type:'tip',d:3,q:"Melyik évben kezdte meg adását a Duna Televízió?",a:1992,unit:"",note:"Szenteste indult, elsősorban a határon túli magyarokhoz szólva."},
{cat:13,type:'tip',d:3,q:"Melyik évben jelent meg először a Nők Lapja?",a:1949,unit:"",note:"Máig az egyik legnagyobb példányszámú magyar hetilap"},
{cat:13,type:'tip',d:3,q:"Hány kérdésből állt a nyereménylétra a Legyen Ön is milliomos! című vetélkedőben?",a:15,unit:"kérdés",note:"A brit eredetihez hasonlóan 15 fokozatú volt a létra a főnyereményig"},
{cat:13,type:'tip',d:3,q:"Melyik évben kapcsolták le véglegesen az analóg földi televíziós sugárzást Magyarországon?",a:2013,unit:"",note:"Ezután a földi adás már csak digitálisan volt fogható."},
{cat:13,type:'tip',d:3,q:"Melyik évben indult a TV2 Jóban Rosszban című napi sorozata?",a:2005,unit:"",note:"A csillagkúti történet 17 éven át futott."},
{cat:13,type:'tip',d:4,q:"Melyik évben indult el a Magyar Televízió rendszeres adása?",a:1957,unit:"",note:""},
{cat:13,type:'tip',d:4,q:"Hány éven át volt képernyőn a Heti Hetes?",a:17,unit:"év",note:"1999–2016"},
{cat:13,type:'tip',d:4,q:"Melyik évben kezdte meg rendszeres adását a Magyar Rádió?",a:1925,unit:"",note:"December 1-jén szólalt meg először a budapesti rádió."},
{cat:13,type:'tip',d:4,q:"Melyik évben indult a Kossuth Rádió legendás sorozata, A Szabó család?",a:1959,unit:"",note:"Közel fél évszázadon át hallgathatták a rádiózók."},
{cat:13,type:'tip',d:5,q:"Melyik évben indult el Budapesten a Telefonhírmondó, a világ első „beszélő újságja”?",a:1893,unit:"",note:"Telefonvonalon közvetített híreket és műsorokat az előfizetőknek"},
{cat:13,type:'tip',d:5,q:"Melyik évben sugározta legelső színes adását a Magyar Televízió?",a:1969,unit:"",note:"A színes adások csak a hetvenes években váltak megszokottá."},

// ---------- 14. Magyar sport és sportolók ----------
{cat:14,type:'mc',d:1,q:"Ki volt az Aranycsapat csapatkapitánya?",
 o:["Puskás Ferenc","Hidegkuti Nándor","Kocsis Sándor","Grosics Gyula"], c:0},
{cat:14,type:'mc',d:1,q:"Melyik sportágban lett olimpiai bajnok Egerszegi Krisztina?",
 o:["Úszás","Torna","Vívás","Kajak-kenu"], c:0},
{cat:14,type:'mc',d:1,q:"Mi Hosszú Katinka beceneve?",
 o:["Iron Lady","Golden Girl","Lady Shark","Aqua Queen"], c:0},
{cat:14,type:'mc',d:2,q:"Melyik sportágban lett olimpiai bajnok Liu Shaolin Sándor?",
 o:["Rövidpályás gyorskorcsolya","Műkorcsolya","Jégtánc","Síakrobatika"], c:0},
{cat:14,type:'mc',d:2,q:"Melyik klub otthona a Groupama Aréna?",
 o:["Ferencváros","Újpest","MTK","Honvéd"], c:0},
{cat:14,type:'mc',d:2,q:"Melyik település mellett található a Hungaroring, a Formula–1 Magyar Nagydíj helyszíne?",
 o:["Mogyoród","Etyek","Kakucs","Tordas"], c:0},
{cat:14,type:'mc',d:2,q:"Melyik sportágban lett háromszoros olimpiai bajnok Kásás Tamás?",
 o:["vízilabda","úszás","kézilabda","vívás"], c:0},
{cat:14,type:'mc',d:2,q:"Melyik sportágban lett többszörös olimpiai bajnok Kovács Katalin?",
 o:["kajak-kenu","evezés","úszás","vitorlázás"], c:0},
{cat:14,type:'mc',d:2,q:"Melyik sportágban nyert olimpiai aranyérmeket Szilágyi Áron?",
 o:["vívás","öttusa","cselgáncs","birkózás"], c:0},
{cat:14,type:'mc',d:3,q:"Ki minden idők legeredményesebb magyar olimpikonja 7 aranyéremmel?",
 o:["Gerevich Aladár (vívás)","Papp László (ökölvívás)","Egerszegi Krisztina (úszás)","Kárpáti Rudolf (vívás)"], c:0},
{cat:14,type:'mc',d:3,q:"Melyik poszton játszott az Aranycsapatban Grosics Gyula, a \"Fekete Párduc\"?",
 o:["kapus","középcsatár","fedezet","balszélső"], c:0},
{cat:14,type:'mc',d:3,q:"Melyik spanyol klubban futballozott Puskás Ferenc 1958-tól?",
 o:["Real Madrid","FC Barcelona","Atlético Madrid","Valencia"], c:0},
{cat:14,type:'mc',d:3,q:"Melyik sportág legendája a háromszoros olimpiai bajnok Balczó András?",
 o:["öttusa","tízpróba","vívás","sportlövészet"], c:0},
{cat:14,type:'mc',d:3,q:"Melyik sportágban lett olimpiai bajnok Földi Imre 1972-ben, Münchenben?",
 o:["súlyemelés","birkózás","ökölvívás","cselgáncs"], c:0},
{cat:14,type:'mc',d:3,q:"Ki lett a gólkirály az 1954-es labdarúgó-világbajnokságon 11 góllal?",
 o:["Kocsis Sándor","Puskás Ferenc","Hidegkuti Nándor","Czibor Zoltán"], c:0},
{cat:14,type:'mc',d:3,q:"Melyik sportágban lett kétszeres olimpiai bajnok Magyar Zoltán?",
 o:["torna","birkózás","cselgáncs","atlétika"], c:0},
{cat:14,type:'mc',d:3,q:"Melyik stadionban győzte le a magyar labdarúgó-válogatott Angliát 6:3-ra?",
 o:["Wembley","Hampden Park","Highbury","Maracana"], c:0},
{cat:14,type:'mc',d:3,q:"Melyik úszásnemben nyert olimpiai aranyat Gyurta Dániel 2012-ben, Londonban?",
 o:["mellúszás","pillangóúszás","hátúszás","gyorsúszás"], c:0},
{cat:14,type:'mc',d:3,q:"Melyik válogatott ellen vívta a magyar vízilabda-válogatott az 1956-os, \"melbourne-i vérfürdő\" néven elhíresült mérkőzést?",
 o:["Szovjetunió","Jugoszlávia","Olaszország","Egyesült Államok"], c:0},
{cat:14,type:'mc',d:3,q:"Ki volt a magyar férfi vízilabda-válogatott szövetségi kapitánya a 2000-es, 2004-es és 2008-as olimpiai győzelmek idején?",
 o:["Kemény Dénes","Benedek Tibor","Faragó Tamás","Horkai György"], c:0},
{cat:14,type:'mc',d:3,q:"Melyik sportágban lett Hajós Alfréd az első magyar olimpiai bajnok?",
 o:["úszás","torna","vívás","atlétika"], c:0},
{cat:14,type:'mc',d:4,q:"Melyik spanyol klub legendás támadója volt Kubala László az 1950-es években?",
 o:["FC Barcelona","Real Madrid","Sevilla","Athletic Bilbao"], c:0},
{cat:14,type:'mc',d:4,q:"Melyik sportágban lett világbajnok Monspart Sarolta 1972-ben?",
 o:["tájékozódási futás","maratoni futás","sífutás","gyaloglás"], c:0},
{cat:14,type:'mc',d:4,q:"Ki volt az első magyar női olimpiai bajnok, aki 1936-ban tőrvívásban győzött?",
 o:["Elek Ilona","Székely Éva","Gyarmati Olga","Keleti Ágnes"], c:0},
{cat:14,type:'mc',d:4,q:"Melyik atlétikai számban nyert olimpiai aranyat Németh Angéla 1968-ban?",
 o:["gerelyhajítás","diszkoszvetés","súlylökés","magasugrás"], c:0},
{cat:14,type:'mc',d:4,q:"Melyik magyar teniszezőnő nyerte meg a Roland Garros női egyesét 1958-ban?",
 o:["Körmöczy Zsuzsa","Temesvári Andrea","Babos Tímea","Sávolt Anikó"], c:0},
{cat:14,type:'mc',d:4,q:"Melyik számban nyert olimpiai aranyat Gyarmati Olga az 1948-as londoni olimpián?",
 o:["távolugrás","magasugrás","100 méteres síkfutás","ötpróba"], c:0},
{cat:14,type:'mc',d:5,q:"Melyik súlycsoportban nyerte Papp László az 1952-es és 1956-os olimpiai aranyérmeit?",
 o:["nagyváltósúly","középsúly","váltósúly","félnehézsúly"], c:0},
{cat:14,type:'mc',d:5,q:"Melyik olasz csapatot győzte le a Ferencváros az 1965-ös Vásárvárosok Kupája-döntőben?",
 o:["Juventus","Internazionale","AC Milan","AS Roma"], c:0},
{cat:14,type:'mc',d:5,q:"Melyik csapatban mutatkozott be Dávid Kornél, az első magyar NBA-játékos?",
 o:["Chicago Bulls","Los Angeles Lakers","New York Knicks","Boston Celtics"], c:0},
{cat:14,type:'tip',d:1,q:"Hány olimpiai aranyérmet nyert Papp László ökölvívó?",a:3,unit:"db",note:"1948-ban, 1952-ben és 1956-ban győzött – elsőként nyert három olimpiát a boksz történetében."},
{cat:14,type:'tip',d:1,q:"Hány versenyző ül egy kajak négyesben?",a:4,unit:"fő",note:"A magyar női kajak négyes több olimpián is aranyérmet szerzett."},
{cat:14,type:'tip',d:2,q:"Melyik évben győzte le a magyar válogatott Angliát 6:3-ra a Wembley-ben?",a:1953,unit:"",note:"az évszázad mérkőzése"},
{cat:14,type:'tip',d:2,q:"Melyik évben veszítette el a magyar válogatott a berni vb-döntőt az NSZK ellen?",a:1954,unit:"",note:"a berni csoda"},
{cat:14,type:'tip',d:2,q:"Hány olimpiai aranyérmet nyert Darnyi Tamás úszó?",a:4,unit:"db",note:"1988-ban és 1992-ben is megnyerte a 200 és a 400 méteres vegyesúszást."},
{cat:14,type:'tip',d:2,q:"Hány aranyérmet nyert a magyar csapat a 2021-ben megrendezett tokiói olimpián?",a:6,unit:"db",note:"Emellett 7 ezüst- és 7 bronzérem is született."},
{cat:14,type:'tip',d:3,q:"Hány olimpiai aranyérmet nyert Egerszegi Krisztina?",a:5,unit:"db",note:"1988, 1992 (×3), 1996"},
{cat:14,type:'tip',d:3,q:"Hány aranyérmet nyert Magyarország a 2016-os riói olimpián?",a:8,unit:"db",note:""},
{cat:14,type:'tip',d:3,q:"Melyik évben rendezték meg az első Formula–1-es Magyar Nagydíjat?",a:1986,unit:"",note:"Ez volt az első F1-es futam a vasfüggöny mögött."},
{cat:14,type:'tip',d:3,q:"Melyik évben nyerte Magyarország az első téli olimpiai aranyérmét?",a:2018,unit:"",note:"A férfi rövidpályás gyorskorcsolya-váltó győzött Phjongcshangban."},
{cat:14,type:'tip',d:3,q:"Hány évesen nyerte Egerszegi Krisztina az első olimpiai aranyérmét?",a:14,unit:"év",note:"1988-ban, Szöulban győzött 200 méter hátúszásban."},
{cat:14,type:'tip',d:3,q:"Hány gólt szerzett Puskás Ferenc a magyar válogatottban?",a:84,unit:"gól",note:"Mindössze 85 válogatott mérkőzésen érte el ezt."},
{cat:14,type:'tip',d:3,q:"Hány olimpiai aranyérmet nyert Keleti Ágnes tornász?",a:5,unit:"db",note:"Összesen tíz olimpiai érmet szerzett, és 103 évet élt."},
{cat:14,type:'tip',d:3,q:"Melyik évben játszott először világbajnoki döntőt a magyar labdarúgó-válogatott?",a:1938,unit:"",note:"A párizsi döntőben Olaszország nyert 4:2-re."},
{cat:14,type:'tip',d:4,q:"Melyik évben jutott a Videoton az UEFA-kupa döntőjébe?",a:1985,unit:"",note:"A döntőben a Real Madrid bizonyult jobbnak."},
{cat:14,type:'tip',d:4,q:"Hány aranyérmet nyert a magyar csapat az 1952-es helsinki olimpián?",a:16,unit:"db",note:"Ezzel Magyarország az éremtáblázat harmadik helyén végzett."},
{cat:14,type:'tip',d:4,q:"Hány olimpiai aranyérmet nyert Kárpáti Rudolf kardvívó?",a:6,unit:"db",note:"Kétszer egyéniben, négyszer a kardcsapattal győzött."},
{cat:14,type:'tip',d:4,q:"Melyik évben rendezett először vizes világbajnokságot Budapest?",a:2017,unit:"",note:"A Duna Aréna volt az úszóversenyek helyszíne."},
{cat:14,type:'tip',d:5,q:"Hányszor nyert olimpiai aranyérmet a magyar labdarúgó-válogatott?",a:3,unit:"db",note:"1952-ben, 1964-ben és 1968-ban állhatott a dobogó tetejére."},
{cat:14,type:'tip',d:5,q:"Melyik évben nyert olimpiai aranyat Csík Ferenc 100 méteres gyorsúszásban?",a:1936,unit:"",note:"Nagy meglepetésre, külső pályáról úszva győzte le a japán esélyeseket."},

// ---------- 15. Magyar gasztronómia és hungarikumok ----------
{cat:15,type:'mc',d:1,q:"Melyik város híres a csabai kolbászról?",
 o:["Békéscsaba","Eger","Szekszárd","Villány"], c:0},
{cat:15,type:'mc',d:1,q:"Melyik városból származik a Pick szalámi?",
 o:["Szeged","Budapest","Debrecen","Kecskemét"], c:0},
{cat:15,type:'mc',d:1,q:"Melyik család nevéhez fűződik az Unicum?",
 o:["Zwack","Gundel","Törley","Richter"], c:0},
{cat:15,type:'mc',d:2,q:"Melyik két város híres leginkább a halászléjéről?",
 o:["Baja és Szeged","Debrecen és Gyula","Kalocsa és Szentes","Eger és Tokaj"], c:0},
{cat:15,type:'mc',d:2,q:"Melyik szőlőfajta a tokaji aszú legfontosabb alapanyaga?",
 o:["Furmint","Kékfrankos","Olaszrizling","Cserszegi fűszeres"], c:0},
{cat:15,type:'mc',d:2,q:"Melyik desszert fűződik Gundel Károly nevéhez?",
 o:["Gundel-palacsinta","Somlói galuska","Dobos-torta","Rákóczi-túrós"], c:0},
{cat:15,type:'mc',d:2,q:"Melyik három alapanyag adja a klasszikus lecsó alapját?",
 o:["Paprika, paradicsom, hagyma","Cukkini, padlizsán, paradicsom","Burgonya, hagyma, gomba","Paprika, káposzta, répa"], c:0},
{cat:15,type:'mc',d:2,q:"Mit jelentett eredetileg a „gulyás” szó?",
 o:["Marhapásztort","Bográcsot","Fűszeres levest","Vándorszakácsot"], c:0},
{cat:15,type:'mc',d:2,q:"Hogyan sütik hagyományosan a kürtőskalácsot?",
 o:["Fahengerre tekert tésztát parázs fölött forgatva","Kemencében, agyagformában","Bő olajban kisütve","Vastag palacsintasütőben"], c:0},
{cat:15,type:'mc',d:3,q:"Mivel töltik a hortobágyi húsos palacsintát?",
 o:["Paprikás húsraguval","Túróval és kaporral","Gombás rizzsel","Sonkás sajtkrémmel"], c:0},
{cat:15,type:'mc',d:3,q:"Eger mellett melyik borvidék készíthet eredetvédett bikavért?",
 o:["Szekszárd","Villány","Badacsony","Somló"], c:0},
{cat:15,type:'mc',d:3,q:"Kiről kapta a nevét a Rigó Jancsi nevű csokoládés-tejszínes sütemény?",
 o:["Egy híres cigányprímásról","Egy pesti cukrászmesterről","Egy operettszínészről","Egy huszárkapitányról"], c:0},
{cat:15,type:'mc',d:3,q:"Mi a mangalica?",
 o:["Göndör szőrű magyar sertésfajta","Ősi magyar szarvasmarhafajta","Magyar pásztorkutyafajta","Régi magyar tyúkfajta"], c:0},
{cat:15,type:'mc',d:3,q:"Melyik magyar város világhírű a hagymatermesztéséről?",
 o:["Makó","Gyula","Cegléd","Szentes"], c:0},
{cat:15,type:'mc',d:3,q:"Melyik két magyar város környéke a fűszerpaprika-őrlemény leghíresebb termőtája?",
 o:["Kalocsa és Szeged","Baja és Mohács","Debrecen és Gyula","Eger és Tokaj"], c:0},
{cat:15,type:'mc',d:3,q:"Mi a tarhonya?",
 o:["Apró, gömbölyded szemekre morzsolt tojásos száraztészta","Kukoricadarából főzött sűrű kása","Burgonyából sütött lepény","Savanyított káposztaféle"], c:0},
{cat:15,type:'mc',d:3,q:"Melyik magyar íróról nevezték el a füstölt csülökkel készülő, gazdag bablevest?",
 o:["Jókai Mórról","Mikszáth Kálmánról","Móricz Zsigmondról","Krúdy Gyuláról"], c:0},
{cat:15,type:'mc',d:3,q:"Mi kerül a zserbószelet tésztarétegei közé?",
 o:["Diós töltelék baracklekvárral","Gesztenyekrém rummal","Mákos guba","Vaníliás túrókrém"], c:0},
{cat:15,type:'mc',d:3,q:"Melyik városhoz kötődik a busójárás, a hungarikumként is elismert télűző népszokás?",
 o:["Mohács","Baja","Szekszárd","Siklós"], c:0},
{cat:15,type:'mc',d:3,q:"Melyik településről kapta a nevét a hungarikum halasi csipke?",
 o:["Kiskunhalas","Hajdúszoboszló","Kiskunfélegyháza","Hódmezővásárhely"], c:0},
{cat:15,type:'mc',d:3,q:"Melyik városban működik a hungarikumként számon tartott Zsolnay porcelánmanufaktúra?",
 o:["Pécs","Herend","Hollóháza","Kecskemét"], c:0},
{cat:15,type:'mc',d:4,q:"Kiről nevezték el az Újházi tyúkhúslevest?",
 o:["Újházi Ede színművészről","Egy pesti fogadósról","Újházi Pál szakácsmesterről","Egy debreceni csárdatulajdonosról"], c:0},
{cat:15,type:'mc',d:4,q:"Melyik borvidék jellegzetes fehér szőlőfajtája a juhfark?",
 o:["Somló","Villány","Szekszárd","Kunság"], c:0},
{cat:15,type:'mc',d:4,q:"Melyik magvas alapanyag jellemzi hagyományosan az Esterházy-torta lapjait és krémjét?",
 o:["Dió","Mák","Gesztenye","Kókusz"], c:0},
{cat:15,type:'mc',d:4,q:"Mi a fő különbség a paprikás és a pörkölt között?",
 o:["A paprikást tejföllel vagy tejszínnel készítik","A pörköltbe nem kerül hagyma","A paprikás mindig halból készül","A pörköltet sütőben készítik"], c:0},
{cat:15,type:'mc',d:4,q:"Melyik város híres a matyó hímzésről, amely az UNESCO szellemi kulturális örökség listáján is szerepel?",
 o:["Mezőkövesd","Kalocsa","Karcag","Hollókő"], c:0},
{cat:15,type:'mc',d:4,q:"Mi a zalai-göcseji dödölle két fő alapanyaga?",
 o:["Burgonya és liszt","Kukorica és tejföl","Káposzta és tészta","Bab és árpagyöngy"], c:0},
{cat:15,type:'mc',d:5,q:"Melyik cukrásztól vette át Gerbeaud Emil a mai Vörösmarty téren működő híres pesti cukrászdát?",
 o:["Kugler Henriktől","Ruszwurm Vilmostól","Auguszt Elektől","Hauer Rezsőtől"], c:0},
{cat:15,type:'mc',d:5,q:"A hagyomány szerint kiről kapta a nevét a székelykáposzta?",
 o:["Székely József levéltárosról","Az erdélyi székelyekről","Székely Bertalan festőről","Egy székelyudvarhelyi fogadósról"], c:0},
{cat:15,type:'mc',d:5,q:"Ki írta a két világháború közötti korszak klasszikus gasztronómiai művét, „Az ínyesmester szakácskönyvét”?",
 o:["Magyar Elek","Gundel Károly","Váncza József","Horváth Ilona"], c:0},
{cat:15,type:'tip',d:1,q:"Hány centiliteres egy hagyományos „feles” pálinka?",a:5,unit:"cl",note:"A neve a fél deciliterre utal."},
{cat:15,type:'tip',d:1,q:"Augusztus hányadikán ünnepeljük az új kenyér ünnepét?",a:20,unit:"",note:"Az államalapítás ünnepén hagyomány az új búzából sütött kenyér megszegése."},
{cat:15,type:'tip',d:2,q:"Hány deciliter bor kerül a nagyfröccsbe?",a:2,unit:"dl",note:"A nagyfröccs 2 dl borból és 1 dl szódából áll."},
{cat:15,type:'tip',d:2,q:"November hányadikán van Márton-nap, amikor a hagyomány szerint libát illik enni?",a:11,unit:"",note:"„Aki Márton napján libát nem eszik, egész éven át éhezik.”"},
{cat:15,type:'tip',d:2,q:"Hány milliliteres a szabványos borospalack?",a:750,unit:"ml",note:"Ez a világszerte elterjedt 0,75 literes űrtartalom."},
{cat:15,type:'tip',d:2,q:"Hányféle klasszikus töltelékkel készül hagyományosan a karácsonyi bejgli?",a:2,unit:"féle",note:"Mákos és diós változatban."},
{cat:15,type:'tip',d:3,q:"Hány féle gyógynövényből készül az Unicum?",a:40,unit:"féle",note:"a pontos recept titkos"},
{cat:15,type:'tip',d:3,q:"Legfeljebb hány puttonyos lehetett a tokaji aszú a klasszikus skálán?",a:6,unit:"puttonyos",note:""},
{cat:15,type:'tip',d:3,q:"Melyik évben került piacra Magyarországon a Túró Rudi?",a:1968,unit:"",note:"A pöttyös csomagolás azóta is védjegye."},
{cat:15,type:'tip',d:3,q:"Melyik évben vették fel a tokaji történelmi borvidéket az UNESCO világörökségi listájára?",a:2002,unit:"",note:"Kultúrtáj kategóriában nyerte el a címet."},
{cat:15,type:'tip',d:3,q:"Melyik évben nyitotta meg kapuit a budapesti New York kávéház?",a:1894,unit:"",note:"A legenda szerint Molnár Ferenc a Dunába dobta a kulcsát, hogy sose zárjon be."},
{cat:15,type:'tip',d:3,q:"Melyik évben alapította Törley József pezsgőpincészetét Budafokon?",a:1882,unit:"",note:"A Törley máig a legismertebb magyar pezsgőmárka."},
{cat:15,type:'tip',d:3,q:"Melyik évben alapították a herendi porcelánmanufaktúrát?",a:1826,unit:"",note:"A herendi porcelán a hungarikumok egyike."},
{cat:15,type:'tip',d:3,q:"Melyik évben vette át Gundel Károly a városligeti éttermet, a mai Gundel elődjét?",a:1910,unit:"",note:"Korábban Wampetics-vendéglőként működött."},
{cat:15,type:'tip',d:4,q:"Melyik évben mutatták be a Dobos-tortát a budapesti Országos Kiállításon?",a:1885,unit:"",note:"Dobos C. József cukrászmester alkotása"},
{cat:15,type:'tip',d:4,q:"Hány liter bor fér egy hagyományos gönci hordóba?",a:136,unit:"liter",note:"a tokaji aszú klasszikus hordója"},
{cat:15,type:'tip',d:4,q:"Melyik évben aratott díjnyertes sikert a somlói galuska a brüsszeli világkiállításon?",a:1958,unit:"",note:"A desszert a Gundel étterem munkatársainak ötletéből született."},
{cat:15,type:'tip',d:4,q:"A világ libamájtermelésének körülbelül hány százalékát adja Magyarország?",a:80,unit:"%",note:"A libamáj (hízott lúdmáj) terén Magyarország világelső; a kacsamájat is beszámítva Franciaország vezet"},
{cat:15,type:'tip',d:5,q:"Melyik évben jelent meg az első magyar nyelvű nyomtatott szakácskönyv, a „Szakáts mesterségnek könyvetskéje”?",a:1695,unit:"",note:"Misztótfalusi Kis Miklós adta ki Kolozsváron."},
{cat:15,type:'tip',d:5,q:"Legalább hány gramm természetes cukrot kell literenként tartalmaznia a tokaji eszenciának?",a:450,unit:"g",note:"Ezért inkább sűrű, nektárszerű különlegesség, mint hagyományos bor."},

// ---------- 16. Nemzetközi filmek és sorozatok ----------
{cat:16,type:'mc',d:1,q:"Ki rendezte a Titanic című filmet?",
 o:["James Cameron","Steven Spielberg","Christopher Nolan","Martin Scorsese"], c:0},
{cat:16,type:'mc',d:1,q:"Melyik sorozat főszereplője Walter White kémiatanár?",
 o:["Breaking Bad – Totál szívás","Dexter","A drót","Narcos"], c:0},
{cat:16,type:'mc',d:1,q:"Ki alakította Jack Sparrow kapitányt A Karib-tenger kalózaiban?",
 o:["Johnny Depp","Orlando Bloom","Brad Pitt","Russell Crowe"], c:0},
{cat:16,type:'mc',d:1,q:"Melyik fantasy-sorozat játszódik Westeros földjén?",
 o:["Trónok harca","A hatalom gyűrűi","Vaják (The Witcher)","Vikingek"], c:0},
{cat:16,type:'mc',d:1,q:"Melyik országból indult világhódító útjára a Squid Game (Nyerd meg az életed)?",
 o:["Dél-Korea","Japán","Kína","Thaiföld"], c:0},
{cat:16,type:'mc',d:2,q:"Ki rendezte a Ponyvaregényt?",
 o:["Quentin Tarantino","David Fincher","A Coen testvérek","Guy Ritchie"], c:0},
{cat:16,type:'mc',d:2,q:"Ki alakította Forrest Gumpot az azonos című filmben?",
 o:["Tom Hanks","Tom Cruise","Kevin Costner","Brad Pitt"], c:0},
{cat:16,type:'mc',d:2,q:"Melyik rajzfilm főhőse Simba, az oroszlánkölyök?",
 o:["Az oroszlánkirály","A dzsungel könyve","Madagaszkár","Kung Fu Panda"], c:0},
{cat:16,type:'mc',d:2,q:"Ki rendezte az E.T. – A földönkívüli és a Cápa című filmeket?",
 o:["Steven Spielberg","George Lucas","Robert Zemeckis","John Carpenter"], c:0},
{cat:16,type:'mc',d:2,q:"Melyik varázslóiskolában tanul Harry Potter?",
 o:["Roxfort","Durmstrang","Beauxbatons","Ilvermorny"], c:0},
{cat:16,type:'mc',d:3,q:"Ki rendezte A keresztapa című filmet?",
 o:["Francis Ford Coppola","Martin Scorsese","Brian De Palma","Sergio Leone"], c:0},
{cat:16,type:'mc',d:3,q:"Melyik sorozat főszereplője Tony Soprano maffiafőnök?",
 o:["Maffiózók","Boardwalk Empire – Gengszterkorzó","Peaky Blinders","A drót"], c:0},
{cat:16,type:'mc',d:3,q:"Ki rendezte a Hátsó ablak és A madarak című klasszikus thrillereket?",
 o:["Alfred Hitchcock","Stanley Kubrick","Orson Welles","Fritz Lang"], c:0},
{cat:16,type:'mc',d:3,q:"Ki rendezte az Oscar-díjas Élősködők című dél-koreai filmet?",
 o:["Bong Joon-ho","Park Chan-wook","Kim Ki-duk","Kore-eda Hirokazu"], c:0},
{cat:16,type:'mc',d:3,q:"Ki alakítja Sherlock Holmest a BBC Sherlock című sorozatában?",
 o:["Benedict Cumberbatch","Martin Freeman","Tom Hiddleston","Jonny Lee Miller"], c:0},
{cat:16,type:'mc',d:3,q:"Ki alakította Hannibal Lectert A bárányok hallgatnak című filmben?",
 o:["Anthony Hopkins","Jeremy Irons","Gary Oldman","Ben Kingsley"], c:0},
{cat:16,type:'mc',d:3,q:"Ki alakítja Elevent (Tizit) a Stranger Things című sorozatban?",
 o:["Millie Bobby Brown","Sadie Sink","Maya Hawke","Natalia Dyer"], c:0},
{cat:16,type:'mc',d:3,q:"Ki rendezte és játszotta a főszerepet Az élet szép című olasz filmben?",
 o:["Roberto Benigni","Giuseppe Tornatore","Nanni Moretti","Paolo Sorrentino"], c:0},
{cat:16,type:'mc',d:3,q:"Melyik sorozat helyszíne a Dunder Mifflin papírkereskedő cég?",
 o:["A hivatal (The Office)","Parks and Recreation","Agymenők","Brooklyn 99"], c:0},
{cat:16,type:'mc',d:3,q:"Ki írta és rendezte az Eredet (Inception) című filmet?",
 o:["Christopher Nolan","Denis Villeneuve","David Fincher","Ridley Scott"], c:0},
{cat:16,type:'mc',d:3,q:"Ki alakította a címszerepet az Amélie csodálatos élete című francia filmben?",
 o:["Audrey Tautou","Marion Cotillard","Léa Seydoux","Juliette Binoche"], c:0},
{cat:16,type:'mc',d:4,q:"Ki rendezte A hetedik pecsét című svéd filmklasszikust?",
 o:["Ingmar Bergman","Andrej Tarkovszkij","Carl Theodor Dreyer","Lars von Trier"], c:0},
{cat:16,type:'mc',d:4,q:"Ki rendezte a Chihiro Szellemországban című Oscar-díjas animét?",
 o:["Miyazaki Hayao","Takahata Isao","Kon Satoshi","Shinkai Makoto"], c:0},
{cat:16,type:'mc',d:4,q:"Melyik sorozat követi a Roy család médiabirodalmának hatalmi harcait?",
 o:["Utódlás (Succession)","Milliárdok nyomában","Dinasztia","Mad Men – Reklámőrültek"], c:0},
{cat:16,type:'mc',d:4,q:"Ki rendezte A hét szamuráj című japán klasszikust?",
 o:["Kurosawa Akira","Ozu Yasujiro","Mizoguchi Kenji","Kitano Takeshi"], c:0},
{cat:16,type:'mc',d:4,q:"Ki rendezte a Casablanca című klasszikust?",
 o:["Michael Curtiz (Kertész Mihály)","Billy Wilder","Howard Hawks","John Huston"], c:0},
{cat:16,type:'mc',d:4,q:"Ki alakította Norman Batest Hitchcock Psycho című filmjében?",
 o:["Anthony Perkins","James Stewart","Cary Grant","Rod Taylor"], c:0},
{cat:16,type:'mc',d:5,q:"Melyik filmért kapta meg Ennio Morricone első verseny-Oscarját a legjobb filmzenéért?",
 o:["Aljas nyolcas","Django elszabadul","A jó, a rossz és a csúf","Volt egyszer egy vadnyugat"], c:0},
{cat:16,type:'mc',d:5,q:"Mi a neve a szállodának Stanley Kubrick Ragyogás című filmjében?",
 o:["Overlook Hotel","Timberline Lodge","Dolphin Hotel","Grand Northern Hotel"], c:0},
{cat:16,type:'mc',d:5,q:"Melyik film nyerte el a legelső Oscar-gálán a legjobb film díját?",
 o:["Szárnyak (Wings)","A dzsesszénekes","Aranypolgár","Elfújta a szél"], c:0},
{cat:16,type:'tip',d:1,q:"Hány törpe él Hófehérkével a Disney-rajzfilmben?",a:7,unit:"törpe",note:""},
{cat:16,type:'tip',d:1,q:"Hány filmből áll Peter Jackson A Gyűrűk Ura-trilógiája?",a:3,unit:"film",note:"A gyűrű szövetsége, A két torony és A király visszatér."},
{cat:16,type:'tip',d:2,q:"Melyik évben mutatták be az első Star Wars filmet?",a:1977,unit:"",note:"Egy új remény"},
{cat:16,type:'tip',d:2,q:"Hány film készült a Harry Potter-könyvsorozatból?",a:8,unit:"film",note:"Az utolsó kötetből két film készült."},
{cat:16,type:'tip',d:2,q:"Melyik évben mutatták be az Avatar című filmet?",a:2009,unit:"",note:"Sokáig minden idők legnagyobb bevételű filmje volt."},
{cat:16,type:'tip',d:2,q:"Hány évadot élt meg a Trónok harca című sorozat?",a:8,unit:"évad",note:"A sorozat 2019-ben ért véget."},
{cat:16,type:'tip',d:3,q:"Hány Oscar-díjat nyert a Titanic?",a:11,unit:"db",note:"rekordbeállítás a Ben-Hurral holtversenyben"},
{cat:16,type:'tip',d:3,q:"Melyik évben indult el a Netflix online streaming szolgáltatása?",a:2007,unit:"",note:"korábban DVD-kölcsönző volt"},
{cat:16,type:'tip',d:3,q:"Melyik évben mutatták be a Mátrix első részét?",a:1999,unit:"",note:"A Wachowski testvérek rendezték."},
{cat:16,type:'tip',d:3,q:"Melyik évben mutatták be a Jurassic Park című filmet?",a:1993,unit:"",note:"Steven Spielberg rendezte."},
{cat:16,type:'tip',d:3,q:"Hány évadból áll a Breaking Bad című sorozat?",a:5,unit:"évad",note:"2008 és 2013 között futott."},
{cat:16,type:'tip',d:3,q:"Melyik évben mutatták be az Elfújta a szél című filmet?",a:1939,unit:"",note:"Inflációval számolva máig a legnagyobb bevételű film."},
{cat:16,type:'tip',d:3,q:"Melyik évben indult a Simpson család című animációs sorozat?",a:1989,unit:"",note:"Máig ez a leghosszabb ideje futó amerikai főműsoridős, forgatókönyves sorozat."},
{cat:16,type:'tip',d:3,q:"Melyik évben mutatták be a Vissza a jövőbe első részét?",a:1985,unit:"",note:"Marty McFly 1955-be utazik vissza benne."},
{cat:16,type:'tip',d:4,q:"Hány epizódból áll a Jóbarátok (Friends)?",a:236,unit:"epizód",note:"10 évad alatt"},
{cat:16,type:'tip',d:4,q:"Melyik évben mutatták be az Aranypolgár című filmet?",a:1941,unit:"",note:"Orson Welles mindössze 25 évesen rendezte."},
{cat:16,type:'tip',d:4,q:"Melyik évben mutatták be Martin Scorsese Nagymenők című filmjét?",a:1990,unit:"",note:"Henry Hill valós történetén alapul."},
{cat:16,type:'tip',d:4,q:"Melyik évben mutatták be A dzsesszénekest, az első hangosfilmet?",a:1927,unit:"",note:"Főszereplője Al Jolson volt."},
{cat:16,type:'tip',d:5,q:"Hány epizódból áll a M*A*S*H című sorozat?",a:256,unit:"epizód",note:"Az 1983-as záróepizód sokáig minden idők legnézettebb tévéadása volt az USA-ban."},
{cat:16,type:'tip',d:5,q:"Melyik évben rendezték meg az első cannes-i filmfesztivált?",a:1946,unit:"",note:"Az 1939-re tervezett első kiírás a háború miatt elmaradt."},

