// KvízParty kérdésbázis – 1/5 darab (a build fűzi össze; kategóriák: 1–4)
// ============================================================
// KvízParty – kérdésbázis (1000 kérdés, 20 kategória)
// Nehézség (d): 1=nagyon könnyű, 2=könnyű, 3=közepes, 4=nehéz, 5=extra nehéz
// Eloszlás: 1★×100, 2★×200, 3★×400, 4★×200, 5★×100
// mc:  {cat, type, d, q, o:[4 opció], c:0 (a helyes mindig az első, a játék kever)}
// tip: {cat, type, d, q, a:szám, unit, note}
// ============================================================

const CATEGORIES = [
 {
  "id": 1,
  "name": "Magyar történelem",
  "icon": "🏰",
  "group": "Magyar általános műveltség"
 },
 {
  "id": 2,
  "name": "Magyar irodalom",
  "icon": "📜",
  "group": "Magyar általános műveltség"
 },
 {
  "id": 3,
  "name": "Magyarország földrajza",
  "icon": "🗺️",
  "group": "Magyar általános műveltség"
 },
 {
  "id": 4,
  "name": "Magyar tudósok és találmányok",
  "icon": "💡",
  "group": "Magyar általános műveltség"
 },
 {
  "id": 5,
  "name": "Magyar nyelv és szólások",
  "icon": "🗣️",
  "group": "Magyar általános műveltség"
 },
 {
  "id": 6,
  "name": "Világtörténelem",
  "icon": "⚔️",
  "group": "Nemzetközi általános műveltség"
 },
 {
  "id": 7,
  "name": "Világföldrajz",
  "icon": "🌍",
  "group": "Nemzetközi általános műveltség"
 },
 {
  "id": 8,
  "name": "Természettudomány",
  "icon": "🔬",
  "group": "Nemzetközi általános műveltség"
 },
 {
  "id": 9,
  "name": "Világirodalom és képzőművészet",
  "icon": "🎨",
  "group": "Nemzetközi általános műveltség"
 },
 {
  "id": 10,
  "name": "Technika, űrkutatás, informatika",
  "icon": "🚀",
  "group": "Nemzetközi általános műveltség"
 },
 {
  "id": 11,
  "name": "Magyar filmek és sorozatok",
  "icon": "🎬",
  "group": "Magyar popkultúra"
 },
 {
  "id": 12,
  "name": "Magyar zene és könnyűzene",
  "icon": "🎸",
  "group": "Magyar popkultúra"
 },
 {
  "id": 13,
  "name": "Magyar tévé és média",
  "icon": "📺",
  "group": "Magyar popkultúra"
 },
 {
  "id": 14,
  "name": "Magyar sport és sportolók",
  "icon": "🏅",
  "group": "Magyar popkultúra"
 },
 {
  "id": 15,
  "name": "Magyar gasztronómia és hungarikumok",
  "icon": "🌶️",
  "group": "Magyar popkultúra"
 },
 {
  "id": 16,
  "name": "Nemzetközi filmek és sorozatok",
  "icon": "🍿",
  "group": "Nemzetközi popkultúra"
 },
 {
  "id": 17,
  "name": "Nemzetközi zene és popsztárok",
  "icon": "🎤",
  "group": "Nemzetközi popkultúra"
 },
 {
  "id": 18,
  "name": "Mémek és internetkultúra",
  "icon": "😂",
  "group": "Nemzetközi popkultúra"
 },
 {
  "id": 19,
  "name": "Videójátékok és gaming",
  "icon": "🎮",
  "group": "Nemzetközi popkultúra"
 },
 {
  "id": 20,
  "name": "Nemzetközi sport",
  "icon": "⚽",
  "group": "Nemzetközi popkultúra"
 }
];

const QUESTIONS = [

// ---------- 1. Magyar történelem ----------
{cat:1,type:'mc',d:1,q:"A hagyomány szerint melyik évben történt a honfoglalás?",
 o:["895","1000","848","920"], c:0},
{cat:1,type:'mc',d:1,q:"Ki volt az első magyar király?",
 o:["I. (Szent) István","Géza fejedelem","I. (Szent) László","Könyves Kálmán"], c:0},
{cat:1,type:'mc',d:1,q:"Kit nevezünk a „legnagyobb magyarnak”?",
 o:["Széchenyi Istvánt","Kossuth Lajost","Deák Ferencet","Wesselényi Miklóst"], c:0},
{cat:1,type:'mc',d:2,q:"Melyik vár védői győzték le a török sereget 1552-ben, Dobó István vezetésével?",
 o:["Eger","Szigetvár","Kőszeg","Temesvár"], c:0},
{cat:1,type:'mc',d:2,q:"Ki volt az 1848–49-es szabadságharc idején Magyarország kormányzó-elnöke?",
 o:["Kossuth Lajos","Széchenyi István","Batthyány Lajos","Görgei Artúr"], c:0},
{cat:1,type:'mc',d:2,q:"Melyik évben kötötte meg Magyarország a kiegyezést a Habsburgokkal?",
 o:["1867","1848","1873","1859"], c:0},
{cat:1,type:'mc',d:2,q:"Melyik napon tört ki az 1956-os forradalom?",
 o:["Október 23-án","Március 15-én","Augusztus 20-án","Október 6-án"], c:0},
{cat:1,type:'mc',d:2,q:"Melyik magyar királyt emlegetik úgy, hogy „az Igazságos”?",
 o:["Mátyást","Nagy Lajost","Zsigmondot","IV. Bélát"], c:0},
{cat:1,type:'mc',d:2,q:"Hogyan nevezték a Rákóczi-szabadságharc harcosait?",
 o:["kurucoknak","labancoknak","hajdúknak","huszároknak"], c:0},
{cat:1,type:'mc',d:3,q:"Melyik magyar király adta ki az Aranybullát?",
 o:["II. András","IV. Béla","III. Béla","Könyves Kálmán"], c:0},
{cat:1,type:'mc',d:3,q:"Hol szenvedett döntő vereséget a magyar sereg a tatároktól 1241-ben?",
 o:["Muhinál","Mohácsnál","Rozgonynál","Pozsonynál"], c:0},
{cat:1,type:'mc',d:3,q:"Ki volt az utolsó Árpád-házi király?",
 o:["III. András","IV. (Kun) László","V. István","II. András"], c:0},
{cat:1,type:'mc',d:3,q:"Melyik magyar király hívta össze 1335-ben a visegrádi királytalálkozót?",
 o:["Károly Róbert","I. (Nagy) Lajos","Luxemburgi Zsigmond","IV. Béla"], c:0},
{cat:1,type:'mc',d:3,q:"Ki volt Szigetvár hős védője 1566-ban?",
 o:["Zrínyi Miklós","Jurisics Miklós","Losonczy István","Szondi György"], c:0},
{cat:1,type:'mc',d:3,q:"Melyik magyar király uralkodott perszonálunióban Lengyelország felett is 1370-től?",
 o:["I. (Nagy) Lajos","Károly Róbert","Luxemburgi Zsigmond","Hunyadi Mátyás"], c:0},
{cat:1,type:'mc',d:3,q:"Ki volt az első felelős magyar kormány miniszterelnöke 1848-ban?",
 o:["Batthyány Lajos","Szemere Bertalan","Deák Ferenc","Andrássy Gyula"], c:0},
{cat:1,type:'mc',d:3,q:"Melyik király uralkodott Magyarországon a tatárjárás idején?",
 o:["IV. Béla","II. András","V. István","Károly Róbert"], c:0},
{cat:1,type:'mc',d:3,q:"Ki volt az első magyar király, aki német-római császár is lett?",
 o:["Luxemburgi Zsigmond","Habsburg Albert","I. Ferdinánd","V. László"], c:0},
{cat:1,type:'mc',d:3,q:"Ki vezette az 1514-es parasztfelkelést?",
 o:["Dózsa György","Budai Nagy Antal","Esze Tamás","Károlyi Sándor"], c:0},
{cat:1,type:'mc',d:3,q:"Melyik oszmán szultán uralkodása alatt foglalták el a törökök Budát 1541-ben?",
 o:["I. (Nagy) Szulejmán","II. Mehmed","I. Szelim","IV. Murád"], c:0},
{cat:1,type:'mc',d:3,q:"Melyik erdélyi fejedelem 1613 és 1629 közötti uralkodását szokás Erdély aranykoraként emlegetni?",
 o:["Bethlen Gáborét","Bocskai Istvánét","Báthory Gáborét","I. Apafi Mihályét"], c:0},
{cat:1,type:'mc',d:4,q:"Melyik vár kapitányaként verte vissza Jurisics Miklós a török ostromot 1532-ben?",
 o:["Kőszeg","Eger","Szigetvár","Drégely"], c:0},
{cat:1,type:'mc',d:4,q:"Milyen országos főméltóságot töltött be Hunyadi János 1446-tól?",
 o:["kormányzó","nádor","esztergomi érsek","horvát bán"], c:0},
{cat:1,type:'mc',d:4,q:"Melyik erdélyi fejedelmet választották lengyel királlyá a 16. században?",
 o:["Báthory Istvánt","Bocskai Istvánt","Bethlen Gábort","János Zsigmondot"], c:0},
{cat:1,type:'mc',d:4,q:"Melyik békekötés zárta le a Rákóczi-szabadságharcot 1711-ben?",
 o:["a szatmári béke","a karlócai béke","a vasvári béke","a nikolsburgi béke"], c:0},
{cat:1,type:'mc',d:4,q:"Melyik város volt a Magyar Királyság koronázóvárosa a török hódoltság korában?",
 o:["Pozsony","Buda","Székesfehérvár","Esztergom"], c:0},
{cat:1,type:'mc',d:4,q:"Melyik lengyel származású tábornok vezette az 1848–49-es szabadságharc erdélyi hadseregét?",
 o:["Bem József","Dembinszky Henrik","Damjanich János","Klapka György"], c:0},
{cat:1,type:'mc',d:5,q:"Melyik magyar királyt koronázták meg 1440-ben, alig néhány hónapos csecsemőként?",
 o:["V. Lászlót","II. Lajost","III. Lászlót","IV. Istvánt"], c:0},
{cat:1,type:'mc',d:5,q:"Hol végezték ki 1795-ben Martinovics Ignácot és a magyar jakobinus mozgalom vezetőit?",
 o:["a budai Vérmezőn","a pesti Újépület udvarán","a Tabánban","a Városligetben"], c:0},
{cat:1,type:'mc',d:5,q:"Ki alapította 1635-ben a nagyszombati egyetemet, a mai ELTE elődjét?",
 o:["Pázmány Péter","Oláh Miklós","Esterházy Miklós","Lippay György"], c:0},
{cat:1,type:'tip',d:1,q:"Melyik évben volt a mohácsi csata?",a:1526,unit:"",note:"1526. augusztus 29."},
{cat:1,type:'tip',d:1,q:"Melyik évben tört ki a pesti forradalom, amelyre minden március 15-én emlékezünk?",a:1848,unit:"",note:"A forradalom a Pilvax kávéházból indult a márciusi ifjak vezetésével."},
{cat:1,type:'tip',d:2,q:"Melyik évben volt a nándorfehérvári diadal?",a:1456,unit:"",note:"Ennek emlékére szól a déli harangszó"},
{cat:1,type:'tip',d:2,q:"Hány honvédtisztet végeztek ki Aradon 1849. október 6-án?",a:13,unit:"fő",note:"Ugyanezen a napon Pesten kivégezték gróf Batthyány Lajos miniszterelnököt is."},
{cat:1,type:'tip',d:2,q:"Melyik évben írták alá a trianoni békeszerződést?",a:1920,unit:"",note:"1920. június 4-én, a versailles-i Nagy-Trianon-palotában került sor az aláírásra."},
{cat:1,type:'tip',d:2,q:"Melyik évben csatlakozott Magyarország az Európai Unióhoz?",a:2004,unit:"",note:"2004. május 1-jén kilenc másik országgal együtt lettünk EU-tagok."},
{cat:1,type:'tip',d:3,q:"Melyik évben foglalták vissza Budát a töröktől?",a:1686,unit:"",note:"145 évnyi hódoltság után"},
{cat:1,type:'tip',d:3,q:"Melyik évben halt meg Mátyás király?",a:1490,unit:"",note:"Bécsben halt meg"},
{cat:1,type:'tip',d:3,q:"Melyik évben halt meg I. (Szent) István király?",a:1038,unit:"",note:"Halála után évtizedekig tartó trónviszályok gyengítették az országot."},
{cat:1,type:'tip',d:3,q:"Melyik évben bontott zászlót a Rákóczi-szabadságharc?",a:1703,unit:"",note:"A felkelés jelszava: „Cum Deo pro Patria et Libertate” – Istennel a hazáért és a szabadságért."},
{cat:1,type:'tip',d:3,q:"Melyik évben egyesítették Pestet, Budát és Óbudát Budapest néven?",a:1873,unit:"",note:"Az egyesített főváros első főpolgármestere Ráth Károly volt."},
{cat:1,type:'tip',d:3,q:"Melyik évben vezették be a forintot a pengő helyett?",a:1946,unit:"",note:"A pengő az addigi történelem egyik legnagyobb hiperinflációjában értéktelenedett el."},
{cat:1,type:'tip',d:3,q:"Melyik évben tűnt el Petőfi Sándor a segesvári csatában?",a:1849,unit:"",note:"Holttestét sosem találták meg, eltűnését számos legenda övezi."},
{cat:1,type:'tip',d:3,q:"Hány évig uralkodott I. Ferenc József?",a:68,unit:"év",note:"1848 decemberétől 1916-os haláláig ült a trónon."},
{cat:1,type:'tip',d:4,q:"Melyik évben avatták szentté I. István királyt?",a:1083,unit:"",note:"Vele együtt fiát, Imre herceget és Gellért püspököt is szentté avatták."},
{cat:1,type:'tip',d:4,q:"Melyik évben nyílt meg az első magyar vasútvonal Pest és Vác között?",a:1846,unit:"",note:"Az ünnepélyes megnyitón a szerelvény alig egy óra alatt ért Vácra."},
{cat:1,type:'tip',d:4,q:"Hány évig töltötte be Horthy Miklós a kormányzói tisztséget?",a:24,unit:"év",note:"1920 márciusától 1944 októberéig volt Magyarország kormányzója."},
{cat:1,type:'tip',d:4,q:"Melyik évben zajlott a pozsonyi csata, amelyben a magyarok megsemmisítő győzelmet arattak a keleti frank haderő felett?",a:907,unit:"",note:"A győzelem hosszú időre megszilárdította a magyarok Kárpát-medencei uralmát."},
{cat:1,type:'tip',d:5,q:"Melyik évben tört ki a Vata-féle pogánylázadás?",a:1046,unit:"",note:"Ekkor szenvedett vértanúhalált Gellért püspök a később róla elnevezett budai hegynél."},
{cat:1,type:'tip',d:5,q:"Melyik évben végezték ki Zrínyi Pétert és Frangepán Ferenc Kristófot a Wesselényi-összeesküvés megtorlásaként?",a:1671,unit:"",note:"Bécsújhelyen fejezték le őket I. Lipót uralkodása alatt"},

// ---------- 2. Magyar irodalom ----------
{cat:2,type:'mc',d:1,q:"Ki írta a Toldit?",
 o:["Arany János","Petőfi Sándor","Vörösmarty Mihály","Jókai Mór"], c:0},
{cat:2,type:'mc',d:1,q:"Ki írta az Egri csillagokat?",
 o:["Gárdonyi Géza","Jókai Mór","Mikszáth Kálmán","Móricz Zsigmond"], c:0},
{cat:2,type:'mc',d:1,q:"Ki a Nemzeti dal költője?",
 o:["Petőfi Sándor","Arany János","Ady Endre","Kölcsey Ferenc"], c:0},
{cat:2,type:'mc',d:2,q:"Ki írta a Himnusz szövegét?",
 o:["Kölcsey Ferenc","Vörösmarty Mihály","Petőfi Sándor","Arany János"], c:0},
{cat:2,type:'mc',d:2,q:"Melyik magyar író kapott irodalmi Nobel-díjat?",
 o:["Kertész Imre","Márai Sándor","Esterházy Péter","Szabó Magda"], c:0},
{cat:2,type:'mc',d:2,q:"Ki írta A Pál utcai fiúkat?",
 o:["Molnár Ferenc","Móricz Zsigmond","Karinthy Frigyes","Kosztolányi Dezső"], c:0},
{cat:2,type:'mc',d:2,q:"Ki írta a Szózat című verset?",
 o:["Vörösmarty Mihály","Kölcsey Ferenc","Petőfi Sándor","Arany János"], c:0},
{cat:2,type:'mc',d:2,q:"Ki írta Az ember tragédiája című drámai költeményt?",
 o:["Madách Imre","Katona József","Vörösmarty Mihály","Jókai Mór"], c:0},
{cat:2,type:'mc',d:2,q:"Ki írta a Bánk bán című drámát?",
 o:["Katona József","Madách Imre","Kisfaludy Károly","Szigligeti Ede"], c:0},
{cat:2,type:'mc',d:3,q:"Móricz Zsigmond melyik regényének főhőse Nyilas Misi?",
 o:["Légy jó mindhalálig","Árvácska","Rokonok","Pillangó"], c:0},
{cat:2,type:'mc',d:3,q:"Ki írta az Abigél című regényt?",
 o:["Szabó Magda","Janikovszky Éva","Jókai Anna","Kaffka Margit"], c:0},
{cat:2,type:'mc',d:3,q:"Ki írta a Tiszta szívvel című verset?",
 o:["József Attila","Ady Endre","Radnóti Miklós","Juhász Gyula"], c:0},
{cat:2,type:'mc',d:3,q:"Ki írta a Tóték című tragikomédiát?",
 o:["Örkény István","Karinthy Frigyes","Németh László","Sarkadi Imre"], c:0},
{cat:2,type:'mc',d:3,q:"Ki írta A gyertyák csonkig égnek című regényt?",
 o:["Márai Sándor","Zilahy Lajos","Kosztolányi Dezső","Herczeg Ferenc"], c:0},
{cat:2,type:'mc',d:3,q:"Jókai Mór melyik regényében szerepel a Baradlay család?",
 o:["A kőszívű ember fiai","Az arany ember","Fekete gyémántok","Egy magyar nábob"], c:0},
{cat:2,type:'mc',d:3,q:"Ki írta az Édes Anna című regényt?",
 o:["Kosztolányi Dezső","Móricz Zsigmond","Babits Mihály","Karinthy Frigyes"], c:0},
{cat:2,type:'mc',d:3,q:"Ki írta A helység kalapácsa című vígeposzt?",
 o:["Petőfi Sándor","Arany János","Csokonai Vitéz Mihály","Garay János"], c:0},
{cat:2,type:'mc',d:3,q:"Ki írta a Szindbád-novellákat?",
 o:["Krúdy Gyula","Csáth Géza","Kosztolányi Dezső","Márai Sándor"], c:0},
{cat:2,type:'mc',d:3,q:"Melyik városban született Petőfi Sándor?",
 o:["Kiskőrös","Kiskunfélegyháza","Szabadszállás","Kecskemét"], c:0},
{cat:2,type:'mc',d:3,q:"Ki írta a Nem tudhatom... kezdetű verset?",
 o:["Radnóti Miklós","Illyés Gyula","Dsida Jenő","Pilinszky János"], c:0},
{cat:2,type:'mc',d:3,q:"Ki írta a Kincskereső kisködmön című regényt?",
 o:["Móra Ferenc","Gárdonyi Géza","Fekete István","Tamási Áron"], c:0},
{cat:2,type:'mc',d:4,q:"Ki írta a Fanni hagyományai című szentimentalista regényt?",
 o:["Kármán József","Kazinczy Ferenc","Batsányi János","Dayka Gábor"], c:0},
{cat:2,type:'mc',d:4,q:"Ki írta a Psyché című művet, egy kitalált költőnő verseivel és élettörténetével?",
 o:["Weöres Sándor","Pilinszky János","Nemes Nagy Ágnes","Vas István"], c:0},
{cat:2,type:'mc',d:4,q:"Melyik író volt Kosztolányi Dezső unokatestvére?",
 o:["Csáth Géza","Karinthy Frigyes","Füst Milán","Juhász Gyula"], c:0},
{cat:2,type:'mc',d:4,q:"Ki írta az Iskola a határon című regényt?",
 o:["Ottlik Géza","Mészöly Miklós","Mándy Iván","Szentkuthy Miklós"], c:0},
{cat:2,type:'mc',d:4,q:"Ki írta A közelítő tél című elégiát?",
 o:["Berzsenyi Dániel","Csokonai Vitéz Mihály","Kölcsey Ferenc","Kazinczy Ferenc"], c:0},
{cat:2,type:'mc',d:4,q:"Ki írta a Liliomfi című vígjátékot?",
 o:["Szigligeti Ede","Kisfaludy Károly","Csiky Gergely","Katona József"], c:0},
{cat:2,type:'mc',d:5,q:"Melyik vár ostrománál sebesült meg halálosan Balassi Bálint?",
 o:["Esztergom","Eger","Szigetvár","Kanizsa"], c:0},
{cat:2,type:'mc',d:5,q:"Melyik kódexben maradt fenn az Ómagyar Mária-siralom?",
 o:["Leuveni kódex","Jókai-kódex","Érdy-kódex","Pray-kódex"], c:0},
{cat:2,type:'mc',d:5,q:"Ki írta a Fekete kolostor című, első világháborús francia internálásról szóló művet?",
 o:["Kuncz Aladár","Markovits Rodion","Karácsony Benő","Bánffy Miklós"], c:0},
{cat:2,type:'tip',d:1,q:"Hány éves korában halt meg Petőfi Sándor?",a:26,unit:"év",note:"A segesvári csatában tűnt el, holttestét sosem találták meg."},
{cat:2,type:'tip',d:1,q:"Hányadik században született Jókai Mór?",a:19,unit:"század",note:"1825-ben született Komáromban."},
{cat:2,type:'tip',d:2,q:"Melyik évben kapta Kertész Imre az irodalmi Nobel-díjat?",a:2002,unit:"",note:"a Sorstalanságért"},
{cat:2,type:'tip',d:2,q:"Melyik évben halt meg József Attila?",a:1937,unit:"",note:"Balatonszárszón érte a halál."},
{cat:2,type:'tip',d:2,q:"Melyik évben halt meg Radnóti Miklós?",a:1944,unit:"",note:"Utolsó verseit a bori noteszbe írta."},
{cat:2,type:'tip',d:2,q:"Melyik évben született Petőfi Sándor?",a:1823,unit:"",note:"Január 1-jén született."},
{cat:2,type:'tip',d:3,q:"Melyik évben született Arany János?",a:1817,unit:"",note:"Nagyszalontán"},
{cat:2,type:'tip',d:3,q:"Hány énekből áll Arany János Toldija?",a:12,unit:"ének",note:""},
{cat:2,type:'tip',d:3,q:"Melyik évben írta Kölcsey Ferenc a Himnuszt?",a:1823,unit:"",note:"január 22-én fejezte be – ez ma a magyar kultúra napja"},
{cat:2,type:'tip',d:3,q:"Melyik évben indult a Nyugat folyóirat?",a:1908,unit:"",note:"Első főszerkesztője Ignotus volt."},
{cat:2,type:'tip',d:3,q:"Hány színből áll Az ember tragédiája?",a:15,unit:"szín",note:"Zárósora: \"Mondottam, ember: küzdj és bízva bízzál!\""},
{cat:2,type:'tip',d:3,q:"Melyik évben halt meg Arany János?",a:1882,unit:"",note:"Utolsó éveiben a Margitszigeten írta az Őszikék verseit."},
{cat:2,type:'tip',d:3,q:"Melyik évben halt meg Ady Endre?",a:1919,unit:"",note:"Január végén hunyt el Budapesten."},
{cat:2,type:'tip',d:3,q:"Melyik évben halt meg Kosztolányi Dezső?",a:1936,unit:"",note:"Hosszú betegség után hunyt el Budapesten."},
{cat:2,type:'tip',d:4,q:"Melyik évben született Móricz Zsigmond?",a:1879,unit:"",note:"A szatmári Tiszacsécsén született."},
{cat:2,type:'tip',d:4,q:"Melyik évben jelent meg a Vizsolyi Biblia, az első teljes magyar nyelvű nyomtatott bibliafordítás?",a:1590,unit:"",note:"Károli Gáspár fordítása."},
{cat:2,type:'tip',d:4,q:"Melyik évben született Szabó Magda?",a:1917,unit:"",note:"Debrecenben született."},
{cat:2,type:'tip',d:4,q:"Melyik évben halt meg Márai Sándor?",a:1989,unit:"",note:"Emigrációban, a kaliforniai San Diegóban hunyt el."},
{cat:2,type:'tip',d:5,q:"Melyik évben született Csokonai Vitéz Mihály?",a:1773,unit:"",note:"Debrecenben született, és ott is halt meg."},
{cat:2,type:'tip',d:5,q:"Melyik évben nyomtatták az első Magyarországon készült könyvet, a Budai krónikát?",a:1473,unit:"",note:"Hess András budai nyomdájában készült."},

// ---------- 3. Magyarország földrajza ----------
{cat:3,type:'mc',d:1,q:"Mi Magyarország legmagasabb pontja?",
 o:["Kékes","Galyatető","Dobogókő","Írott-kő"], c:0},
{cat:3,type:'mc',d:1,q:"Melyik folyó szeli ketté Szegedet?",
 o:["Tisza","Duna","Körös","Rába"], c:0},
{cat:3,type:'mc',d:1,q:"Melyik Magyarország második legnépesebb városa?",
 o:["Debrecen","Szeged","Miskolc","Pécs"], c:0},
{cat:3,type:'mc',d:1,q:"Melyik országgal NEM határos Magyarország?",
 o:["Csehország","Szlovénia","Ukrajna","Horvátország"], c:0},
{cat:3,type:'mc',d:2,q:"Melyik vármegye székhelye Kaposvár?",
 o:["Somogy","Baranya","Tolna","Zala"], c:0},
{cat:3,type:'mc',d:2,q:"Melyik nemzeti parkban található a Baradla-cseppkőbarlang?",
 o:["Aggteleki Nemzeti Park","Bükki Nemzeti Park","Hortobágyi Nemzeti Park","Duna–Ipoly Nemzeti Park"], c:0},
{cat:3,type:'mc',d:2,q:"Melyik tó Közép-Európa legnagyobb tava?",
 o:["Balaton","Fertő tó","Velencei-tó","Tisza-tó"], c:0},
{cat:3,type:'mc',d:2,q:"Melyik folyó szeli ketté Budapestet?",
 o:["Duna","Tisza","Dráva","Rába"], c:0},
{cat:3,type:'mc',d:2,q:"Melyik nagytájunkon található a Hortobágy?",
 o:["Alföld","Kisalföld","Dunántúli-dombság","Északi-középhegység"], c:0},
{cat:3,type:'mc',d:3,q:"Melyik vármegye székhelye Békéscsaba?",
 o:["Békés","Csongrád-Csanád","Hajdú-Bihar","Jász-Nagykun-Szolnok"], c:0},
{cat:3,type:'mc',d:3,q:"Melyik folyó partján fekszik Miskolc?",
 o:["Sajó","Hernád","Bodrog","Zagyva"], c:0},
{cat:3,type:'mc',d:3,q:"Hány nemzeti park található Magyarországon?",
 o:["10","7","13","16"], c:0},
{cat:3,type:'mc',d:3,q:"Melyik nemzeti park területén található a Szalajka-völgy?",
 o:["Bükki Nemzeti Park","Aggteleki Nemzeti Park","Hortobágyi Nemzeti Park","Duna-Ipoly Nemzeti Park"], c:0},
{cat:3,type:'mc',d:3,q:"Melyik vármegyében található Hollókő, a világörökség részét képező palóc falu?",
 o:["Nógrád","Heves","Borsod-Abaúj-Zemplén","Pest"], c:0},
{cat:3,type:'mc',d:3,q:"Melyik a Duna legnagyobb magyarországi szigete?",
 o:["Csepel-sziget","Szentendrei-sziget","Margit-sziget","Mohácsi-sziget"], c:0},
{cat:3,type:'mc',d:3,q:"Melyik vármegye székhelye Szombathely?",
 o:["Vas","Zala","Veszprém","Győr-Moson-Sopron"], c:0},
{cat:3,type:'mc',d:3,q:"Melyik vármegyében fekszik a Velencei-tó?",
 o:["Fejér","Pest","Veszprém","Komárom-Esztergom"], c:0},
{cat:3,type:'mc',d:3,q:"Melyik nemzeti parkhoz tartozik a bugaci puszta?",
 o:["Kiskunsági Nemzeti Park","Hortobágyi Nemzeti Park","Körös-Maros Nemzeti Park","Duna-Dráva Nemzeti Park"], c:0},
{cat:3,type:'mc',d:3,q:"Melyik város fekszik a Rába és a Mosoni-Duna találkozásánál?",
 o:["Győr","Szombathely","Sopron","Mosonmagyaróvár"], c:0},
{cat:3,type:'mc',d:3,q:"Melyik vármegyében fekszik Tokaj városa?",
 o:["Borsod-Abaúj-Zemplén","Szabolcs-Szatmár-Bereg","Heves","Hajdú-Bihar"], c:0},
{cat:3,type:'mc',d:3,q:"Melyik folyó torkollik a Balatonba?",
 o:["Zala","Kapos","Marcal","Sió"], c:0},
{cat:3,type:'mc',d:4,q:"Melyik hegység legmagasabb pontja az Írott-kő?",
 o:["Kőszegi-hegység","Soproni-hegység","Bakony","Mecsek"], c:0},
{cat:3,type:'mc',d:4,q:"Mi a Mecsek legmagasabb csúcsa?",
 o:["Zengő","Misina","Tubes","Jakab-hegy"], c:0},
{cat:3,type:'mc',d:4,q:"Melyik folyó partján fekszik Gyula városa?",
 o:["Fehér-Körös","Fekete-Körös","Sebes-Körös","Berettyó"], c:0},
{cat:3,type:'mc',d:4,q:"Melyik Magyarország legnagyobb területű vármegyéje?",
 o:["Bács-Kiskun","Pest","Borsod-Abaúj-Zemplén","Hajdú-Bihar"], c:0},
{cat:3,type:'mc',d:4,q:"Melyik hegység legmagasabb csúcsa a Csóványos?",
 o:["Börzsöny","Cserhát","Pilis","Visegrádi-hegység"], c:0},
{cat:3,type:'mc',d:4,q:"Melyik városban található a híres Tavasbarlang?",
 o:["Tapolca","Keszthely","Sümeg","Veszprém"], c:0},
{cat:3,type:'mc',d:5,q:"Melyik település határában található Magyarország legalacsonyabban fekvő pontja?",
 o:["Tiszasziget","Szeged","Mohács","Csongrád"], c:0},
{cat:3,type:'mc',d:5,q:"Melyik a leghosszabb, teljes hosszában Magyarországon folyó folyó?",
 o:["Zagyva","Sió","Zala","Ipoly"], c:0},
{cat:3,type:'mc',d:5,q:"Melyik Magyarország legkeletibb települése?",
 o:["Garbolc","Tiszabecs","Csenger","Záhony"], c:0},
{cat:3,type:'tip',d:1,q:"Hány országgal határos Magyarország?",a:7,unit:"db",note:"Ausztria, Szlovákia, Ukrajna, Románia, Szerbia, Horvátország és Szlovénia."},
{cat:3,type:'tip',d:1,q:"Hány kerülete van Budapestnek?",a:23,unit:"db",note:""},
{cat:3,type:'tip',d:2,q:"Hány méter magas a Kékes?",a:1014,unit:"m",note:""},
{cat:3,type:'tip',d:2,q:"Hány vármegyéje van Magyarországnak?",a:19,unit:"",note:"Budapest nélkül"},
{cat:3,type:'tip',d:2,q:"Hány négyzetkilométer Magyarország területe?",a:93030,unit:"km²",note:"kb. 93 030 km²"},
{cat:3,type:'tip',d:2,q:"Hány méter magas a budapesti Gellért-hegy?",a:235,unit:"m",note:"A tetején áll a Citadella."},
{cat:3,type:'tip',d:3,q:"Hány kilométer hosszú a Balaton?",a:77,unit:"km",note:"Európa legnagyobb sekély tava"},
{cat:3,type:'tip',d:3,q:"Milyen hosszú a Tisza magyarországi szakasza?",a:597,unit:"km",note:"A folyó teljes hossza 962 km."},
{cat:3,type:'tip',d:3,q:"Milyen hosszú a Duna magyarországi szakasza?",a:417,unit:"km",note:"Rajkától a déli országhatárig tart."},
{cat:3,type:'tip',d:3,q:"Mekkora a Balaton területe?",a:594,unit:"km²",note:"Átlagos mélysége mindössze kb. 3 méter."},
{cat:3,type:'tip',d:3,q:"Hány méter magas a mátrai Galyatető?",a:964,unit:"m",note:"A Mátra második legmagasabb csúcsa."},
{cat:3,type:'tip',d:3,q:"Hány méter magas a Bakony legmagasabb csúcsa, a Kőris-hegy?",a:709,unit:"m",note:""},
{cat:3,type:'tip',d:3,q:"Mekkora a Tisza-tó területe?",a:127,unit:"km²",note:"Mesterséges tározótó az Alföld északi részén."},
{cat:3,type:'tip',d:3,q:"Hány méter magas a Badacsony?",a:437,unit:"m",note:"A Balaton-felvidék jellegzetes tanúhegye."},
{cat:3,type:'tip',d:4,q:"Milyen hosszú a Sió-csatorna, amely a Balaton vizét a Dunába vezeti?",a:121,unit:"km",note:""},
{cat:3,type:'tip',d:4,q:"Hány méter mély a Hévízi-tó?",a:38,unit:"m",note:"Európa legnagyobb gyógyhatású termáltava."},
{cat:3,type:'tip',d:4,q:"Mekkora Budapest területe?",a:525,unit:"km²",note:""},
{cat:3,type:'tip',d:4,q:"Milyen hosszú a magyar–osztrák határszakasz?",a:356,unit:"km",note:""},
{cat:3,type:'tip',d:5,q:"Hány méter magas a lillafüredi Szinva-vízesés, Magyarország legmagasabb vízesése?",a:20,unit:"m",note:""},
{cat:3,type:'tip',d:5,q:"Hány méter hosszú a hortobágyi Kilenclyukú híd?",a:167,unit:"m",note:"Magyarország leghosszabb közúti kőhídja."},

// ---------- 4. Magyar tudósok és találmányok ----------
{cat:4,type:'mc',d:1,q:"Ki találta fel a golyóstollat?",
 o:["Bíró László József","Rubik Ernő","Jedlik Ányos","Kandó Kálmán"], c:0},
{cat:4,type:'mc',d:1,q:"Melyik magyar tudós izolálta a C-vitamint a szegedi paprikából?",
 o:["Szent-Györgyi Albert","Semmelweis Ignác","Békésy György","Hevesy György"], c:0},
{cat:4,type:'mc',d:1,q:"Kit nevezünk „az anyák megmentőjének”?",
 o:["Semmelweis Ignácot","Korányi Frigyest","Szent-Györgyi Albertet","Hőgyes Endrét"], c:0},
{cat:4,type:'mc',d:2,q:"Mi fűződik Jedlik Ányos nevéhez?",
 o:["A dinamó elve","A transzformátor","A telefonhírmondó","A helikopter"], c:0},
{cat:4,type:'mc',d:2,q:"Melyik magyar származású tudós nevéhez fűződik a modern számítógépek architektúrája?",
 o:["Neumann János","Kemény János","Gábor Dénes","Szilárd Leó"], c:0},
{cat:4,type:'mc',d:2,q:"Ki találta fel a zajtalanul és robbanás nélkül gyulladó gyufát?",
 o:["Irinyi János","Jedlik Ányos","Bánki Donát","Puskás Tivadar"], c:0},
{cat:4,type:'mc',d:2,q:"Melyik magyar mérnök volt a vasútvillamosítás úttörője, a fázisváltós villamos mozdony megalkotója?",
 o:["Kandó Kálmán","Bláthy Ottó","Csonka János","Mechwart András"], c:0},
{cat:4,type:'mc',d:2,q:"Melyik magyar biokémikus kapott Nobel-díjat az mRNS-alapú vakcinákat megalapozó felfedezéseiért?",
 o:["Karikó Katalin","Krausz Ferenc","Barabási Albert-László","Freund Tamás"], c:0},
{cat:4,type:'mc',d:2,q:"Melyik magyar tudós alkotta meg az első hazai szódavízgyártó berendezést, amivel a szikvíz atyja lett?",
 o:["Jedlik Ányos","Irinyi János","Than Károly","Kempelen Farkas"], c:0},
{cat:4,type:'mc',d:3,q:"Ki volt a Ford T-modell főkonstruktőre?",
 o:["Galamb József","Csonka János","Bánki Donát","Kandó Kálmán"], c:0},
{cat:4,type:'mc',d:3,q:"Milyen találmány fűződik Bánki Donát és Csonka János nevéhez?",
 o:["A porlasztó (karburátor)","A dízelmotor","A gyújtógyertya","A kétütemű motor"], c:0},
{cat:4,type:'mc',d:3,q:"Milyen világhírű mérőeszköz fűződik Eötvös Loránd nevéhez?",
 o:["A torziós inga","A szeizmográf","A higanyos barométer","A spektroszkóp"], c:0},
{cat:4,type:'mc',d:3,q:"Milyen eljárás feltalálásáért kapott fizikai Nobel-díjat Gábor Dénes?",
 o:["A holográfiáért","A lézerért","A tranzisztorért","A röntgenképalkotásért"], c:0},
{cat:4,type:'mc',d:3,q:"Melyik magyar fizikus ismerte fel elsőként a nukleáris láncreakció lehetőségét?",
 o:["Szilárd Leó","Teller Ede","Wigner Jenő","Bay Zoltán"], c:0},
{cat:4,type:'mc',d:3,q:"Melyik magyar származású fizikust nevezik a hidrogénbomba atyjának?",
 o:["Teller Ede","Szilárd Leó","Hevesy György","Lánczos Kornél"], c:0},
{cat:4,type:'mc',d:3,q:"Kik alkották meg a világ első zárt vasmagú transzformátorát a Ganz gyárban?",
 o:["Bláthy Ottó, Déri Miksa és Zipernowsky Károly","Kandó Kálmán, Bánki Donát és Csonka János","Jedlik Ányos, Irinyi János és Puskás Tivadar","Galamb József, Fonó Albert és Asbóth Oszkár"], c:0},
{cat:4,type:'mc',d:3,q:"Melyik magyar származású orvos dolgozta ki a stresszelméletet?",
 o:["Selye János","Szentágothai János","Békésy György","Semmelweis Ignác"], c:0},
{cat:4,type:'mc',d:3,q:"Melyik magyar származású programozó irányította a Microsoftnál a Word és az Excel fejlesztését?",
 o:["Simonyi Károly","Gróf András","Kemény János","Neumann János"], c:0},
{cat:4,type:'mc',d:3,q:"Melyik magyar matematikus alkotta meg a nemeuklideszi geometria egyik első rendszerét?",
 o:["Bolyai János","Bolyai Farkas","Erdős Pál","Fejér Lipót"], c:0},
{cat:4,type:'mc',d:3,q:"Melyik magyar származású matematikus volt a BASIC programozási nyelv egyik megalkotója?",
 o:["Kemény János","Kalmár László","Neumann János","Erdős Pál"], c:0},
{cat:4,type:'mc',d:3,q:"Kinek a nevéhez fűződik a Telefonhírmondó, a rádió elődjének tekinthető beszélő újság?",
 o:["Puskás Tivadar","Mihály Dénes","Bláthy Ottó","Csonka János"], c:0},
{cat:4,type:'mc',d:4,q:"Milyen eljárás kidolgozásáért kapott kémiai Nobel-díjat Hevesy György?",
 o:["A radioaktív nyomjelzésért","A kromatográfiáért","A polimerizáció felfedezéséért","Az elektrolízis törvényeinek leírásáért"], c:0},
{cat:4,type:'mc',d:4,q:"Milyen kutatásaiért kapott orvosi Nobel-díjat Békésy György?",
 o:["A belső fül csigájának működéséért","A szívritmus szabályozásáért","A látóideg működéséért","A vércsoportok felfedezéséért"], c:0},
{cat:4,type:'mc',d:4,q:"Melyik találmány fűződik Goldmark Péter Károly nevéhez?",
 o:["A mikrobarázdás LP hanglemez","A kompaktlemez (CD)","A magnókazetta","A sztereó fejhallgató"], c:0},
{cat:4,type:'mc',d:4,q:"Milyen kutatásaiért kapott kémiai Nobel-díjat Oláh György 1994-ben?",
 o:["A karbokationok vizsgálatáért","A fullerének felfedezéséért","Az ózonréteg kutatásáért","A DNS szerkezetének feltárásáért"], c:0},
{cat:4,type:'mc',d:4,q:"Melyik magyar származású fizikus kapott Nobel-díjat 1963-ban az atommagokra vonatkozó szimmetriaelvek kutatásáért?",
 o:["Wigner Jenő","Szilárd Leó","Gábor Dénes","Teller Ede"], c:0},
{cat:4,type:'mc',d:4,q:"Milyen légi járművel kísérletezett sikerrel Asbóth Oszkár az 1920-as években?",
 o:["Helikopterrel","Léghajóval","Sugárhajtású repülőgéppel","Hőlégballonnal"], c:0},
{cat:4,type:'mc',d:5,q:"Melyik magyar feltaláló töltéstárolásos szabadalmai alapozták meg a modern televíziós képfelvevő csöveket?",
 o:["Tihanyi Kálmán","Mihály Dénes","Okolicsányi Ferenc","Goldmark Péter"], c:0},
{cat:4,type:'mc',d:5,q:"Ki építette meg a világ első működő turbólégcsavaros repülőgép-hajtóművét?",
 o:["Jendrassik György","Fonó Albert","Kandó Kálmán","Asbóth Oszkár"], c:0},
{cat:4,type:'mc',d:5,q:"Melyik magyar származású kémikus kapott Nobel-díjat a kolloidkémiai kutatásaiért és az ultramikroszkóp kifejlesztéséért?",
 o:["Zsigmondy Richárd","Hevesy György","Polányi Mihály","Oláh György"], c:0},
{cat:4,type:'tip',d:1,q:"Hány különböző színt használ a klasszikus Rubik-kocka?",a:6,unit:"db",note:"Fehér, sárga, piros, narancs, kék és zöld."},
{cat:4,type:'tip',d:1,q:"Hány kis négyzet látható a klasszikus, 3×3-as Rubik-kocka egy oldalán?",a:9,unit:"db",note:"Egy oldalon 3×3-as elrendezésben."},
{cat:4,type:'tip',d:2,q:"Melyik évben kapott fizikai Nobel-díjat Krausz Ferenc az attoszekundumos fényimpulzusok kutatásáért?",a:2023,unit:"",note:"A díjon Pierre Agostinivel és Anne L'Huillier-vel osztozott."},
{cat:4,type:'tip',d:2,q:"Hány kilométeres magasságban húzódik a Kármán Tódorról elnevezett vonal, amelyet a világűr határának tekintenek?",a:100,unit:"km",note:"A magyar származású mérnök-fizikus a modern aerodinamika egyik atyja volt."},
{cat:4,type:'tip',d:2,q:"Melyik évben adták át Budapesten a kontinentális Európa első földalatti vasútját?",a:1896,unit:"",note:"A millenniumi ünnepségekre készült el a Millenniumi Földalatti."},
{cat:4,type:'tip',d:2,q:"Melyik évben jutott a világűrbe Farkas Bertalan, az első magyar űrhajós?",a:1980,unit:"",note:"A Szojuz–36 fedélzetén indult a Szaljut–6 űrállomásra."},
{cat:4,type:'tip',d:3,q:"Melyik évben találta fel Rubik Ernő a bűvös kockát?",a:1974,unit:"",note:""},
{cat:4,type:'tip',d:3,q:"Melyik évben kapta Szent-Györgyi Albert az orvosi Nobel-díjat?",a:1937,unit:"",note:""},
{cat:4,type:'tip',d:3,q:"Hány kis kockából (elemből) áll össze a klasszikus 3×3-as Rubik-kocka?",a:26,unit:"db",note:"8 sarok + 12 él + 6 középső elem"},
{cat:4,type:'tip',d:3,q:"Melyik évben alapította Richter Gedeon gyógyszerész a később világhírűvé vált gyógyszergyárát?",a:1901,unit:"",note:"A budapesti Sas patikában kezdte meg a gyógyszergyártást."},
{cat:4,type:'tip',d:3,q:"Melyik évben halt meg Semmelweis Ignác?",a:1865,unit:"",note:"Születésnapja, július 1. ma a magyar egészségügy napja."},
{cat:4,type:'tip',d:3,q:"Melyik évben mutatta be Kempelen Farkas a sakkozó törököt, a világhírű sakkautomatát?",a:1769,unit:"",note:"Mária Terézia udvarának készült; valójában egy elrejtett ember irányította"},
{cat:4,type:'tip',d:3,q:"Melyik évben adták át a Széchenyi lánchidat, Pest és Buda első állandó hídját?",a:1849,unit:"",note:"Korának egyik legnagyobb mérnöki teljesítménye volt."},
{cat:4,type:'tip',d:3,q:"Melyik évben indult el az első villamos Budapesten?",a:1887,unit:"",note:"Próbajáratként közlekedett a Nagykörúton."},
{cat:4,type:'tip',d:4,q:"Melyik évben született Neumann János?",a:1903,unit:"",note:"Budapesten"},
{cat:4,type:'tip',d:4,q:"Melyik évben fogta fel Bay Zoltán kutatócsoportja a Holdról visszavert radarjeleket?",a:1946,unit:"",note:"A világon az elsők között sikerült radarvisszhangot venni a Holdról."},
{cat:4,type:'tip',d:4,q:"Melyik évben kapott közgazdasági Nobel-díjat Harsányi János a játékelméleti munkásságáért?",a:1994,unit:"",note:"John Nash-sel és Reinhard Seltennel megosztva kapta a díjat."},
{cat:4,type:'tip',d:4,q:"Melyik évben kapott orvosi Nobel-díjat Bárány Róbert az egyensúlyszerv kutatásáért?",a:1914,unit:"",note:"A díj hírét orosz hadifogságban kapta meg."},
{cat:4,type:'tip',d:5,q:"Melyik évben kapta meg Lénárd Fülöp, az első magyar származású Nobel-díjas a fizikai Nobel-díjat?",a:1905,unit:"",note:"A katódsugarakkal kapcsolatos kutatásaiért tüntették ki."},
{cat:4,type:'tip',d:5,q:"Melyik évben kezdte meg működését az első telefonközpont Budapesten?",a:1881,unit:"",note:"Európa legelső telefonközpontjai között nyílt meg."},

