// KvízParty kérdésbázis – 3/5 darab (kategóriák: 9–12)
// ---------- 9. Világirodalom és képzőművészet ----------
{cat:9,type:'mc',d:1,q:"Ki festette a Mona Lisát?",
 o:["Leonardo da Vinci","Michelangelo","Raffaello","Botticelli"], c:0},
{cat:9,type:'mc',d:2,q:"Ki írta a Bűn és bűnhődést?",
 o:["Fjodor Dosztojevszkij","Lev Tolsztoj","Anton Csehov","Nyikolaj Gogol"], c:0},
{cat:9,type:'mc',d:2,q:"Ki festette a Csillagos éj című képet?",
 o:["Vincent van Gogh","Claude Monet","Pablo Picasso","Salvador Dalí"], c:0},
{cat:9,type:'mc',d:2,q:"Melyik művészeti irányzat fő képviselője volt Salvador Dalí?",
 o:["Szürrealizmus","Kubizmus","Impresszionizmus","Expresszionizmus"], c:0},
{cat:9,type:'mc',d:2,q:"Ki festette a Sixtus-kápolna mennyezetfreskóit?",
 o:["Michelangelo","Leonardo da Vinci","Raffaello","Botticelli"], c:0},
{cat:9,type:'mc',d:2,q:"Ki írta a Faust című drámai költeményt?",
 o:["Johann Wolfgang von Goethe","Friedrich Schiller","Heinrich Heine","Thomas Mann"], c:0},
{cat:9,type:'mc',d:2,q:"Ki írta A kis herceg című könyvet?",
 o:["Antoine de Saint-Exupéry","Albert Camus","Jules Verne","Romain Rolland"], c:0},
{cat:9,type:'mc',d:2,q:"Ki írta az Anna Karenina című regényt?",
 o:["Lev Tolsztoj","Fjodor Dosztojevszkij","Anton Csehov","Ivan Turgenyev"], c:0},
{cat:9,type:'mc',d:3,q:"Ki írta a Száz év magány című regényt?",
 o:["Gabriel García Márquez","Jorge Luis Borges","Mario Vargas Llosa","Pablo Neruda"], c:0},
{cat:9,type:'mc',d:3,q:"Melyik városban áll Michelangelo Dávid-szobra?",
 o:["Firenze","Róma","Velence","Milánó"], c:0},
{cat:9,type:'mc',d:3,q:"Ki festette a Guernica című képet?",
 o:["Pablo Picasso","Salvador Dalí","Joan Miró","Francisco Goya"], c:0},
{cat:9,type:'mc',d:3,q:"Ki írta az 1984 című regényt?",
 o:["George Orwell","Aldous Huxley","Ray Bradbury","Arthur Koestler"], c:0},
{cat:9,type:'mc',d:3,q:"Ki festette a Vénusz születése című képet?",
 o:["Sandro Botticelli","Tiziano","Raffaello","Caravaggio"], c:0},
{cat:9,type:'mc',d:3,q:"Ki írta Az öreg halász és a tenger című kisregényt?",
 o:["Ernest Hemingway","John Steinbeck","William Faulkner","F. Scott Fitzgerald"], c:0},
{cat:9,type:'mc',d:3,q:"Ki komponálta A négy évszak című hegedűverseny-sorozatot?",
 o:["Antonio Vivaldi","Johann Sebastian Bach","Georg Friedrich Händel","Arcangelo Corelli"], c:0},
{cat:9,type:'mc',d:3,q:"Ki festette a Sikoly című képet?",
 o:["Edvard Munch","Gustav Klimt","Egon Schiele","Vaszilij Kandinszkij"], c:0},
{cat:9,type:'mc',d:3,q:"Ki írta A nyomorultak című regényt?",
 o:["Victor Hugo","Émile Zola","Honoré de Balzac","Stendhal"], c:0},
{cat:9,type:'mc',d:3,q:"Melyik művészeti irányzat képviselője volt Claude Monet?",
 o:["impresszionizmus","expresszionizmus","kubizmus","szürrealizmus"], c:0},
{cat:9,type:'mc',d:3,q:"Ki írta a Don Quijote című regényt?",
 o:["Miguel de Cervantes","Lope de Vega","Calderón de la Barca","Federico García Lorca"], c:0},
{cat:9,type:'mc',d:3,q:"Ki festette az Éjjeli őrjárat című képet?",
 o:["Rembrandt","Jan Vermeer","Frans Hals","Peter Paul Rubens"], c:0},
{cat:9,type:'mc',d:3,q:"Ki írta a Twist Olivér című regényt?",
 o:["Charles Dickens","Mark Twain","Robert Louis Stevenson","Jonathan Swift"], c:0},
{cat:9,type:'mc',d:4,q:"Ki festette Az Arnolfini házaspár című képet?",
 o:["Jan van Eyck","Rogier van der Weyden","Hieronymus Bosch","Albrecht Dürer"], c:0},
{cat:9,type:'mc',d:4,q:"Ki írta az Ulysses című regényt?",
 o:["James Joyce","Virginia Woolf","Samuel Beckett","D. H. Lawrence"], c:0},
{cat:9,type:'mc',d:4,q:"Melyik szobrász alkotta az Apolló és Daphné című barokk szoborcsoportot?",
 o:["Gian Lorenzo Bernini","Antonio Canova","Donatello","Benvenuto Cellini"], c:0},
{cat:9,type:'mc',d:4,q:"Ki írta A Mester és Margarita című regényt?",
 o:["Mihail Bulgakov","Borisz Paszternak","Vlagyimir Nabokov","Mihail Solohov"], c:0},
{cat:9,type:'mc',d:4,q:"Ki írta Az eltűnt idő nyomában című regényfolyamot?",
 o:["Marcel Proust","André Gide","Anatole France","Paul Valéry"], c:0},
{cat:9,type:'mc',d:4,q:"Ki komponálta a Carmina Burana című kantátát?",
 o:["Carl Orff","Richard Strauss","Igor Stravinsky","Paul Hindemith"], c:0},
{cat:9,type:'mc',d:5,q:"Mi volt Michelangelo, a reneszánsz mester vezetékneve?",
 o:["Buonarroti","Vecellio","Sanzio","Merisi"], c:0},
{cat:9,type:'mc',d:5,q:"Ki festette a pipát ábrázoló, \"Ez nem pipa\" feliratú képet (A képek árulása)?",
 o:["René Magritte","Salvador Dalí","Max Ernst","Giorgio de Chirico"], c:0},
{cat:9,type:'mc',d:5,q:"Melyik művész állította ki Forrás címmel a művészettörténet leghíresebb piszoárját?",
 o:["Marcel Duchamp","Man Ray","Andy Warhol","Joseph Beuys"], c:0},
{cat:9,type:'tip',d:1,q:"Hány kötetből áll a Harry Potter-regénysorozat?",a:7,unit:"kötet",note:"Az utolsó kötet 2007-ben jelent meg."},
{cat:9,type:'tip',d:1,q:"Hány apostol szerepel Leonardo da Vinci Az utolsó vacsora című freskóján Jézus mellett?",a:12,unit:"fő",note:"A freskó a milánói Santa Maria delle Grazie kolostor falán látható."},
{cat:9,type:'tip',d:2,q:"Hány sorból áll egy klasszikus szonett?",a:14,unit:"sor",note:"A formát Petrarca tette világhírűvé."},
{cat:9,type:'tip',d:2,q:"Hány fő részből áll Dante Isteni színjátéka?",a:3,unit:"rész",note:"Pokol, Purgatórium, Paradicsom."},
{cat:9,type:'tip',d:2,q:"Hány szimfóniát fejezett be Beethoven?",a:9,unit:"db",note:"Az utolsó zárótétele az Örömóda."},
{cat:9,type:'tip',d:2,q:"Melyik évben égett le a párizsi Notre-Dame székesegyház tetőszerkezete?",a:2019,unit:"",note:"A huszártorony a lángok között omlott össze."},
{cat:9,type:'tip',d:3,q:"Melyik évben született William Shakespeare?",a:1564,unit:"",note:"Stratford-upon-Avonban"},
{cat:9,type:'tip',d:3,q:"Melyik évben kezdte el festeni Leonardo a Mona Lisát?",a:1503,unit:"",note:""},
{cat:9,type:'tip',d:3,q:"Melyik évben halt meg Vincent van Gogh?",a:1890,unit:"",note:"37 évesen"},
{cat:9,type:'tip',d:3,q:"Melyik évben született Leonardo da Vinci?",a:1452,unit:"",note:"A toszkánai Vinci település közelében született."},
{cat:9,type:'tip',d:3,q:"Melyik évben halt meg Pablo Picasso?",a:1973,unit:"",note:"91 évet élt."},
{cat:9,type:'tip',d:3,q:"Melyik évben halt meg Michelangelo?",a:1564,unit:"",note:"Rómában hunyt el, 88 évesen."},
{cat:9,type:'tip',d:3,q:"Melyik évben halt meg William Shakespeare?",a:1616,unit:"",note:"A hagyomány szerint április 23-án, épp a születésnapján hunyt el."},
{cat:9,type:'tip',d:3,q:"Melyik évben született Wolfgang Amadeus Mozart?",a:1756,unit:"",note:"Salzburgban született, január 27-én."},
{cat:9,type:'tip',d:4,q:"Hány szonettet írt Shakespeare?",a:154,unit:"db",note:""},
{cat:9,type:'tip',d:4,q:"Hány énekből áll Homérosz Odüsszeiája?",a:24,unit:"ének",note:"Az Iliász szintén 24 énekből áll."},
{cat:9,type:'tip',d:4,q:"Melyik évben nyílt meg múzeumként a párizsi Louvre?",a:1793,unit:"",note:"A francia forradalom idején nyitották meg a nagyközönség előtt."},
{cat:9,type:'tip',d:4,q:"Melyik évben kezdték építeni a barcelonai Sagrada Famíliát?",a:1882,unit:"",note:"Antoni Gaudí egy évvel később vette át a tervezést."},
{cat:9,type:'tip',d:5,q:"Melyik évben született Rembrandt?",a:1606,unit:"",note:"Leidenben született, egy molnár fiaként."},
{cat:9,type:'tip',d:5,q:"Melyik évben készült el a Gutenberg-biblia, az első nagy példányszámban nyomtatott európai könyv?",a:1455,unit:"",note:"Körülbelül 180 példány készült belőle."},

// ---------- 10. Technika, űrkutatás, informatika ----------
{cat:10,type:'mc',d:1,q:"Ki lépett először a Holdra?",
 o:["Neil Armstrong","Buzz Aldrin","Jurij Gagarin","Michael Collins"], c:0},
{cat:10,type:'mc',d:1,q:"Ki alapította a Microsoftot Paul Allennel közösen?",
 o:["Bill Gates","Steve Jobs","Elon Musk","Jeff Bezos"], c:0},
{cat:10,type:'mc',d:1,q:"Mit jelent a WWW rövidítés?",
 o:["World Wide Web","World Web Wire","Wide World Web","Web World Wide"], c:0},
{cat:10,type:'mc',d:1,q:"Melyik cég gyártja a Falcon 9 rakétát?",
 o:["SpaceX","NASA","Blue Origin","Boeing"], c:0},
{cat:10,type:'mc',d:2,q:"Ki volt az első ember a világűrben?",
 o:["Jurij Gagarin","Neil Armstrong","Valentyina Tyereskova","Alan Shepard"], c:0},
{cat:10,type:'mc',d:2,q:"Melyik céget alapította Steve Jobs és Steve Wozniak 1976-ban?",
 o:["Apple","Microsoft","IBM","Intel"], c:0},
{cat:10,type:'mc',d:2,q:"Melyik autógyártó modellje a Model S és a Model 3 elektromos autó?",
 o:["Tesla","BMW","Toyota","Volkswagen"], c:0},
{cat:10,type:'mc',d:2,q:"Ki alapította a SpaceX űrvállalatot?",
 o:["Elon Musk","Jeff Bezos","Richard Branson","Bill Gates"], c:0},
{cat:10,type:'mc',d:2,q:"Hogy hívják a Google által fejlesztett, okostelefonokon futó operációs rendszert?",
 o:["Android","iOS","Windows Phone","Symbian"], c:0},
{cat:10,type:'mc',d:3,q:"Mi volt az első magyar fejlesztésű műhold neve?",
 o:["Masat-1","Hunity-1","MagSat","Puli-1"], c:0},
{cat:10,type:'mc',d:3,q:"Ki volt az első nő, aki a világűrbe jutott?",
 o:["Valentyina Tyereskova","Sally Ride","Szvetlana Szavickaja","Mae Jemison"], c:0},
{cat:10,type:'mc',d:3,q:"Mi volt az Apollo–11 holdkompjának a neve?",
 o:["Eagle","Intrepid","Falcon","Aquarius"], c:0},
{cat:10,type:'mc',d:3,q:"Mi volt az első űrsikló neve, amely 1981-ben űrrepülést hajtott végre?",
 o:["Columbia","Challenger","Discovery","Enterprise"], c:0},
{cat:10,type:'mc',d:3,q:"Ki dolgozta ki a World Wide Web alapjait 1989-ben a CERN-ben?",
 o:["Tim Berners-Lee","Vint Cerf","Bill Gates","Linus Torvalds"], c:0},
{cat:10,type:'mc',d:3,q:"Melyik égitest holdja a Phobos?",
 o:["A Marsé","A Jupiteré","A Szaturnuszé","A Neptunuszé"], c:0},
{cat:10,type:'mc',d:3,q:"Melyik bolygót és holdjait vizsgálta közelről a Cassini űrszonda?",
 o:["Szaturnusz","Jupiter","Mars","Neptunusz"], c:0},
{cat:10,type:'mc',d:3,q:"Melyik városban nyílt meg a világ első földalatti vasútja 1863-ban?",
 o:["London","Párizs","New York","Berlin"], c:0},
{cat:10,type:'mc',d:3,q:"Ki vezette be elsőként a futószalagos tömeggyártást az autóiparban?",
 o:["Henry Ford","Karl Benz","Gottlieb Daimler","André Citroën"], c:0},
{cat:10,type:'mc',d:3,q:"Melyik cég fejlesztette ki a PDF fájlformátumot?",
 o:["Adobe","Microsoft","Apple","Xerox"], c:0},
{cat:10,type:'mc',d:3,q:"Melyik űrszonda jutott a legtávolabbra a Földtől az ember alkotta eszközök közül?",
 o:["Voyager–1","Voyager–2","Pioneer–10","New Horizons"], c:0},
{cat:10,type:'mc',d:3,q:"Ki szabadalmaztatta a telefont 1876-ban?",
 o:["Alexander Graham Bell","Thomas Edison","Guglielmo Marconi","Nikola Tesla"], c:0},
{cat:10,type:'mc',d:4,q:"Min hajtott végre leszállást a Rosetta űrszonda Philae leszállóegysége 2014-ben?",
 o:["Egy üstökösön","Egy kisbolygón","A Mars egyik holdján","A Merkúron"], c:0},
{cat:10,type:'mc',d:4,q:"Mi volt a világ első űrállomásának a neve, amelyet 1971-ben bocsátottak fel?",
 o:["Szaljut–1","Mir","Skylab","Almaz"], c:0},
{cat:10,type:'mc',d:4,q:"Melyik cég dobta piacra 1971-ben a világ első kereskedelmi forgalomba került mikroprocesszorát, a 4004-est?",
 o:["Intel","IBM","Motorola","Texas Instruments"], c:0},
{cat:10,type:'mc',d:4,q:"Mi volt a neve a Szovjetunió űrrepülőgépének, amely 1988-ban egyetlen űrrepülést hajtott végre?",
 o:["Burán","Vosztok","Szojuz","Proton"], c:0},
{cat:10,type:'mc',d:4,q:"Ki alkotta meg a Python programozási nyelvet?",
 o:["Guido van Rossum","James Gosling","Dennis Ritchie","Bjarne Stroustrup"], c:0},
{cat:10,type:'mc',d:4,q:"Ki hajtotta végre a történelem első űrsétáját 1965-ben?",
 o:["Alekszej Leonov","Edward White","German Tyitov","Michael Collins"], c:0},
{cat:10,type:'mc',d:5,q:"Ki volt az első amerikai űrhajós, aki Föld körüli pályán megkerülte a bolygót?",
 o:["John Glenn","Alan Shepard","Gus Grissom","Scott Carpenter"], c:0},
{cat:10,type:'mc',d:5,q:"Mi volt a világ első, 1992-ben elküldött SMS-ének a szövege?",
 o:["Merry Christmas","Hello World","Happy New Year","Test message"], c:0},
{cat:10,type:'mc',d:5,q:"Melyik ország űrszondája hajtotta végre az első sikeres leszállást a Vénusz felszínén?",
 o:["Szovjetunió","Egyesült Államok","Japán","Kína"], c:0},
{cat:10,type:'tip',d:1,q:"Melyik évben lépett az első ember a Holdra?",a:1969,unit:"",note:"július 20-án"},
{cat:10,type:'tip',d:1,q:"Melyik évben jelent meg a Windows 95 operációs rendszer?",a:1995,unit:"",note:"A nevében is szereplő évben, 1995 augusztusában került a boltokba."},
{cat:10,type:'tip',d:2,q:"Melyik évben állt Föld körüli pályára a Szputnyik–1, az első műhold?",a:1957,unit:"",note:""},
{cat:10,type:'tip',d:2,q:"Hány perc alatt ér a napfény a Földre?",a:8,unit:"perc",note:"pontosabban kb. 8 perc 20 mp"},
{cat:10,type:'tip',d:2,q:"Melyik évben mutatták be az első iPhone-t?",a:2007,unit:"",note:""},
{cat:10,type:'tip',d:2,q:"Hány bit alkot egy bájtot?",a:8,unit:"bit",note:"A bájt a digitális adattárolás egyik alapegysége."},
{cat:10,type:'tip',d:3,q:"Melyik évben hajtotta végre a Wright fivérek gépe az első sikeres motoros repülést?",a:1903,unit:"",note:"Az észak-karolinai Kitty Hawk közelében emelkedett a levegőbe."},
{cat:10,type:'tip',d:3,q:"Melyik évben alapította Larry Page és Sergey Brin a Google-t?",a:1998,unit:"",note:"A cég egy kaliforniai garázsból indult."},
{cat:10,type:'tip',d:3,q:"Melyik évben került piacra az első kereskedelmi CD-lejátszó?",a:1982,unit:"",note:"A Sony és a Philips közös szabványa alapján készült"},
{cat:10,type:'tip',d:3,q:"Melyik évben állították Föld körüli pályára a Hubble űrtávcsövet?",a:1990,unit:"",note:"A Discovery űrrepülőgép fedélzetén jutott a világűrbe."},
{cat:10,type:'tip',d:3,q:"Melyik évben indult el a YouTube videómegosztó?",a:2005,unit:"",note:"Az első feltöltött videó címe: Me at the zoo."},
{cat:10,type:'tip',d:3,q:"Körülbelül hány kilométer magasan kering a Nemzetközi Űrállomás a Föld felszíne felett?",a:400,unit:"km",note:"Nagyjából másfél óránként kerüli meg a Földet."},
{cat:10,type:'tip',d:3,q:"Melyik évben nyílt meg a La Manche csatorna alatti Csalagút?",a:1994,unit:"",note:"Nagy-Britanniát és Franciaországot köti össze a tenger alatt."},
{cat:10,type:'tip',d:3,q:"Melyik évben süllyedt el a Titanic óceánjáró?",a:1912,unit:"",note:"Első útján ütközött jéghegynek az Atlanti-óceánon."},
{cat:10,type:'tip',d:4,q:"Hány percig tartott Jurij Gagarin történelmi űrrepülése?",a:108,unit:"perc",note:"Egyetlen kört tett meg a Föld körül a Vosztok–1 fedélzetén."},
{cat:10,type:'tip',d:4,q:"Melyik évben küldte el Ray Tomlinson a világ első e-mailjét?",a:1971,unit:"",note:"Ő választotta a @ jelet a címek elválasztására."},
{cat:10,type:'tip',d:4,q:"Melyik évben mutatták be az ENIAC-ot, az egyik első elektronikus, általános célú számítógépet?",a:1946,unit:"",note:"Körülbelül 18 ezer elektroncsőből épült, és egy egész termet megtöltött."},
{cat:10,type:'tip',d:4,q:"Hány ember járt a Hold felszínén az Apollo-program során?",a:12,unit:"fő",note:"Hat sikeres Holdra szállás során, kettesével léptek a felszínre."},
{cat:10,type:'tip',d:5,q:"Melyik évben találták fel a tranzisztort a Bell Laboratóriumban?",a:1947,unit:"",note:"Feltalálói később fizikai Nobel-díjat kaptak érte."},
{cat:10,type:'tip',d:5,q:"Melyik évben mutatta be az IBM a világ első merevlemezes tárolóegységét?",a:1956,unit:"",note:"A szekrény méretű RAMAC alig 5 megabájtnyi adatot tárolt."},

// ---------- 11. Magyar filmek és sorozatok ----------
{cat:11,type:'mc',d:1,q:"Melyik magyar film nyerte el 2016-ban a legjobb idegen nyelvű filmnek járó Oscar-díjat?",
 o:["Saul fia","Testről és lélekről","Kontroll","Mindenki"], c:0},
{cat:11,type:'mc',d:1,q:"Melyik csatornán futott a Barátok közt?",
 o:["RTL Klub","TV2","M1","Viasat3"], c:0},
{cat:11,type:'mc',d:2,q:"Ki alakította Ötvös Csöpit a balatoni akció-vígjátékokban?",
 o:["Bujtor István","Kern András","Koltai Róbert","Garas Dezső"], c:0},
{cat:11,type:'mc',d:2,q:"Milyen állat dr. Bubó, a Kérem a következőt! című rajzfilmsorozat doktora?",
 o:["Bagoly","Medve","Róka","Nyúl"], c:0},
{cat:11,type:'mc',d:2,q:"Ki a Macskafogó című rajzfilm szuperügynök egér főhőse?",
 o:["Grabowski","Safranek","Fritz Teufel","Lusta Dick"], c:0},
{cat:11,type:'mc',d:2,q:"Melyik magyar sorozat középpontjában áll a Berényi család?",
 o:["Barátok közt","Szomszédok","Jóban Rosszban","Éjjel-nappal Budapest"], c:0},
{cat:11,type:'mc',d:2,q:"Melyik magyar rajzfilm címszereplője egy kisróka?",
 o:["Vuk","Misi mókus kalandjai","Frakk, a macskák réme","Szaffi"], c:0},
{cat:11,type:'mc',d:2,q:"Melyik rajzfilmsorozat két főhőse a nagyot mondó horgász és Főkukac?",
 o:["A nagy ho-ho-horgász","Vízipók-csodapók","Pom Pom meséi","Mekk Elek, az ezermester"], c:0},
{cat:11,type:'mc',d:2,q:"Milyen állat Kántor, a klasszikus magyar bűnügyi tévésorozat címszereplője?",
 o:["Nyomozókutya","Rendőrló","Postagalamb","Idomított sólyom"], c:0},
{cat:11,type:'mc',d:3,q:"Ki rendezte a Kontroll című filmet?",
 o:["Antal Nimród","Nemes Jeles László","Enyedi Ildikó","Goda Krisztina"], c:0},
{cat:11,type:'mc',d:3,q:"Ki alakította Pelikán Józsefet A tanú című filmben?",
 o:["Kállai Ferenc","Őze Lajos","Sinkovits Imre","Garas Dezső"], c:0},
{cat:11,type:'mc',d:3,q:"Ki rendezte a Testről és lélekről című, Oscar-jelölt filmet?",
 o:["Enyedi Ildikó","Mundruczó Kornél","Szabó István","Tarr Béla"], c:0},
{cat:11,type:'mc',d:3,q:"Ki játszotta a címszerepet Huszárik Zoltán Szindbád című, 1971-es filmjében?",
 o:["Latinovits Zoltán","Darvas Iván","Gábor Miklós","Mensáros László"], c:0},
{cat:11,type:'mc',d:3,q:"Ki rendezte az Oscar-díjas Mephisto című filmet?",
 o:["Szabó István","Jancsó Miklós","Makk Károly","Fábri Zoltán"], c:0},
{cat:11,type:'mc',d:3,q:"Ki rendezte A tanú című legendás szatírát?",
 o:["Bacsó Péter","Sándor Pál","Gothár Péter","Jancsó Miklós"], c:0},
{cat:11,type:'mc',d:3,q:"Ki volt Bud Spencer legendás magyar szinkronhangja?",
 o:["Bujtor István","Gáti Oszkár","Reviczky Gábor","Helyey László"], c:0},
{cat:11,type:'mc',d:3,q:"Ki volt Terence Hill állandó magyar szinkronhangja a legtöbb filmjében?",
 o:["Ujréti László","Csernák János","Sörös Sándor","Szakácsi Sándor"], c:0},
{cat:11,type:'mc',d:3,q:"Ki alakította a címszerepet a Linda című, nagy sikerű magyar tévésorozatban?",
 o:["Görbe Nóra","Esztergalyos Cecília","Pápai Erika","Bánsági Ildikó"], c:0},
{cat:11,type:'mc',d:3,q:"Ki rendezte A Pál utcai fiúk 1969-es, Oscar-jelölt filmváltozatát?",
 o:["Fábri Zoltán","Várkonyi Zoltán","Keleti Márton","Ranódy László"], c:0},
{cat:11,type:'mc',d:3,q:"Ki alakította Molnár tizedest A tizedes meg a többiek című filmben?",
 o:["Sinkovits Imre","Darvas Iván","Márkus László","Garas Dezső"], c:0},
{cat:11,type:'mc',d:3,q:"Ki rendezte és játszotta a főszerepet a Sose halunk meg című filmben?",
 o:["Koltai Róbert","Kern András","Garas Dezső","Eperjes Károly"], c:0},
{cat:11,type:'mc',d:4,q:"Ki alakította Hyppolitot, a lakájt az 1931-es klasszikus vígjátékban?",
 o:["Csortos Gyula","Kabos Gyula","Jávor Pál","Páger Antal"], c:0},
{cat:11,type:'mc',d:4,q:"Melyik filmben hangzik el Minarik Ede híres mondata: „Kell egy csapat!”?",
 o:["Régi idők focija","Két félidő a pokolban","6:3, avagy játszd újra Tutti","A miniszter félrelép"], c:0},
{cat:11,type:'mc',d:4,q:"Ki rendezte a Csinibaba című zenés vígjátékot?",
 o:["Tímár Péter","Herendi Gábor","Goda Krisztina","Kern András"], c:0},
{cat:11,type:'mc',d:4,q:"Ki játszotta a címszerepet a Liza, a rókatündér című filmben?",
 o:["Balsai Móni","Borbély Alexandra","Tenki Réka","Dobó Kata"], c:0},
{cat:11,type:'mc',d:4,q:"Ki rendezte a Kincsem című, 2017-es filmet?",
 o:["Herendi Gábor","Goda Krisztina","Ujj Mészáros Károly","Antal Nimród"], c:0},
{cat:11,type:'mc',d:4,q:"Ki játszotta a címszerepet az 1949-es Mágnás Miska című filmben?",
 o:["Latabár Kálmán","Feleki Kamill","Rátonyi Róbert","Kazal László"], c:0},
{cat:11,type:'mc',d:5,q:"Ki szerezte a Vuk című rajzfilm emblematikus zenéjét?",
 o:["Wolf Péter","Vukán György","Presser Gábor","Deák Tamás"], c:0},
{cat:11,type:'mc',d:5,q:"Ki volt a Szomszédok című teleregeny kitalálója és rendezője?",
 o:["Horváth Ádám","Szinetár Miklós","Sas Tamás","Mihályfy Sándor"], c:0},
{cat:11,type:'mc',d:5,q:"Ki alakította Bornemissza Gergelyt az Egri csillagok 1968-as filmváltozatában?",
 o:["Kovács István","Koncz Gábor","Balázsovits Lajos","Oszter Sándor"], c:0},
{cat:11,type:'tip',d:1,q:"Hány feje van Süsünek, a bábfilmsorozat sárkányának?",a:1,unit:"fej",note:"Süsü épp attól különleges, hogy egyfejű sárkány."},
{cat:11,type:'tip',d:1,q:"Hány gyerek van a Mézga családban?",a:2,unit:"gyerek",note:"Kriszta és Aladár."},
{cat:11,type:'tip',d:2,q:"Melyik évben indult a Barátok közt?",a:1998,unit:"",note:""},
{cat:11,type:'tip',d:2,q:"Hány része készült az Üvegtigris című filmsorozatnak?",a:3,unit:"rész",note:"2001-ben, 2006-ban és 2010-ben mutatták be a részeket."},
{cat:11,type:'tip',d:2,q:"Hány macskával él egy fedél alatt Frakk, a macskák réme?",a:2,unit:"macska",note:"Lukréciával és Szerénkével."},
{cat:11,type:'tip',d:2,q:"Melyik évben mutatták be a Macskafogó című rajzfilmet?",a:1986,unit:"",note:"Ternovszky Béla rendezte."},
{cat:11,type:'tip',d:3,q:"Melyik évben nyert Oscar-díjat Szabó István filmje, a Mephisto?",a:1982,unit:"",note:""},
{cat:11,type:'tip',d:3,q:"Melyik évben mutatták be a Valami Amerika című vígjátékot?",a:2002,unit:"",note:"Az évtized egyik legnagyobb magyar mozisikere lett."},
{cat:11,type:'tip',d:3,q:"Hány részből áll A Tenkes kapitánya című tévésorozat?",a:13,unit:"rész",note:"Eke Mátét Zenthe Ferenc alakította."},
{cat:11,type:'tip',d:3,q:"Melyik évben mutatták be A miniszter félrelép című vígjátékot?",a:1997,unit:"",note:"Ray Cooney színd arabjából készült."},
{cat:11,type:'tip',d:3,q:"Melyik évben mutatták be A Pogány Madonna című filmet?",a:1981,unit:"",note:"Bujtor István és Kern András főszereplésével; a forgatás 1980-ban zajlott"},
{cat:11,type:'tip',d:3,q:"Melyik évben mutatták be A kőszívű ember fiai című filmet?",a:1965,unit:"",note:"Várkonyi Zoltán rendezte Jókai regényéből."},
{cat:11,type:'tip',d:3,q:"2025 végéig hány magyar film nyerte el a legjobb idegen nyelvű (nemzetközi) film Oscar-díját?",a:2,unit:"film",note:"A Mephisto és a Saul fia."},
{cat:11,type:'tip',d:3,q:"Melyik évben mutatták be a Kontroll című filmet?",a:2003,unit:"",note:"A film teljes egészében a budapesti metróban játszódik."},
{cat:11,type:'tip',d:4,q:"Melyik évben készült A tanú című film?",a:1969,unit:"",note:"éveken át dobozban maradt, csak később mutathatták be"},
{cat:11,type:'tip',d:4,q:"Hány részből állt a Szomszédok teleregeny?",a:331,unit:"rész",note:"1987 és 1999 között"},
{cat:11,type:'tip',d:4,q:"Melyik évben mutatták be a Halálos tavasz című filmet?",a:1939,unit:"",note:"Karády Katalin ezzel a filmmel debütált."},
{cat:11,type:'tip',d:4,q:"Melyik évben nyert Oscar-díjat a Mindenki című magyar rövidfilm?",a:2017,unit:"",note:"Deák Kristóf kórusos története a legjobb élőszereplős rövidfilm lett."},
{cat:11,type:'tip',d:5,q:"Hány epizódból áll a Magyar népmesék klasszikus, 2011-ig készült szériája?",a:100,unit:"epizód",note:"A sorozat 1980-ban indult; 2024-ben új epizódok készítését is bejelentették"},
{cat:11,type:'tip',d:5,q:"Melyik évben mutatták be a János vitézt, az első egész estés magyar rajzfilmet?",a:1973,unit:"",note:"Jankovics Marcell rendezte."},

// ---------- 12. Magyar zene és könnyűzene ----------
{cat:12,type:'mc',d:1,q:"Ki volt az Omega együttes legendás frontembere?",
 o:["Kóbor János","Presser Gábor","Demjén Ferenc","Zorán"], c:0},
{cat:12,type:'mc',d:1,q:"Ki szerezte a Himnusz zenéjét?",
 o:["Erkel Ferenc","Liszt Ferenc","Kodály Zoltán","Bartók Béla"], c:0},
{cat:12,type:'mc',d:2,q:"Melyik együttes slágere a Gyöngyhajú lány?",
 o:["Omega","Illés","Metró","LGT"], c:0},
{cat:12,type:'mc',d:2,q:"Melyik zenekar billentyűse és dalszerzője volt Presser Gábor az 1970-es évektől?",
 o:["LGT (Locomotiv GT)","Piramis","Edda","Neoton Família"], c:0},
{cat:12,type:'mc',d:2,q:"Kinek a slágere az Azért vannak a jóbarátok?",
 o:["Demjén Ferenc","Zorán","Koncz Zsuzsa","Máté Péter"], c:0},
{cat:12,type:'mc',d:2,q:"Ki a Tankcsapda frontembere?",
 o:["Lukács László","Ganxsta Zolee","Kiss Tibor","Nagy Feró"], c:0},
{cat:12,type:'mc',d:2,q:"Melyik együttes eredeti dala a „Most múlik pontosan”?",
 o:["Quimby","Csík zenekar","Magna Cum Laude","Kispál és a Borz"], c:0},
{cat:12,type:'mc',d:2,q:"Melyik együttes slágere a „Szállj el, kismadár”?",
 o:["Republic","Bikini","Piramis","Bojtorján"], c:0},
{cat:12,type:'mc',d:2,q:"Milyen becenéven vált ismertté Zámbó Jimmy?",
 o:["A Király","A Herceg","A Császár","A Bárd"], c:0},
{cat:12,type:'mc',d:3,q:"Ki írta az Illés együttes legtöbb slágerének szövegét?",
 o:["Bródy János","Szörényi Levente","Adamis Anna","S. Nagy István"], c:0},
{cat:12,type:'mc',d:3,q:"Ki volt a Piramis együttes énekese?",
 o:["Révész Sándor","Vikidál Gyula","Deák Bill Gyula","D. Nagy Lajos"], c:0},
{cat:12,type:'mc',d:3,q:"Ki énekelte az „Add már, uram, az esőt!” című dalt?",
 o:["Kovács Kati","Koncz Zsuzsa","Zalatnay Sarolta","Harangozó Teri"], c:0},
{cat:12,type:'mc',d:3,q:"Melyik együttes énekeseként vált ismertté Zorán az 1960-as években?",
 o:["Metró","Illés","Omega","Hungária"], c:0},
{cat:12,type:'mc',d:3,q:"Melyik zenekar slágere a „Nyolc óra munka”?",
 o:["Beatrice","P. Mobil","Hobo Blues Band","Edda Művek"], c:0},
{cat:12,type:'mc',d:3,q:"Ki énekli a „Ha én rózsa volnék” című dalt?",
 o:["Koncz Zsuzsa","Kovács Kati","Halász Judit","Katona Klári"], c:0},
{cat:12,type:'mc',d:3,q:"Melyik együttes slágere a „Közeli helyeken”?",
 o:["Bikini","Republic","Piramis","Korál"], c:0},
{cat:12,type:'mc',d:3,q:"Melyik együttes dala az „Afrika”?",
 o:["KFT","Első Emelet","Dolly Roll","Neoton Família"], c:0},
{cat:12,type:'mc',d:3,q:"Melyik együttes frontembere volt Fenyő Miklós?",
 o:["Hungária","Dolly Roll","Első Emelet","R-GO"], c:0},
{cat:12,type:'mc',d:3,q:"Melyik városból származik Majka, azaz Majoros Péter?",
 o:["Ózd","Miskolc","Salgótarján","Kazincbarcika"], c:0},
{cat:12,type:'mc',d:3,q:"Melyik zenekar frontembere volt Lovasi András az 1990-es években?",
 o:["Kispál és a Borz","Quimby","Sziámi","Pál Utcai Fiúk"], c:0},
{cat:12,type:'mc',d:3,q:"Melyik formációban kezdte pályafutását L.L. Junior?",
 o:["Fekete Vonat","Animal Cannibals","Hip Hop Boyz","Bëlga"], c:0},
{cat:12,type:'mc',d:4,q:"Ki volt a Locomotiv GT alapító dobosa?",
 o:["Laux József","Solti János","Debreczeni Ferenc","Brunner Győző"], c:0},
{cat:12,type:'mc',d:4,q:"Mi a beceneve Molnár Györgynek, az Omega gitárosának?",
 o:["Elefánt","Medve","Bölény","Mamut"], c:0},
{cat:12,type:'mc',d:4,q:"Ki alapította 1973-ban a Skorpió együttest?",
 o:["Frenreisz Károly","Som Lajos","Balázs Fecó","Radics Béla"], c:0},
{cat:12,type:'mc',d:4,q:"Ki volt a P. Mobil énekese az 1970-es évek végén, aki később a Dinamit frontembere lett?",
 o:["Vikidál Gyula","Tunyogi Péter","Nagy Feró","Deák Bill Gyula"], c:0},
{cat:12,type:'mc',d:4,q:"Ki lett a Bikini együttes énekese 1985-ben?",
 o:["D. Nagy Lajos","Vikidál Gyula","Nagy Feró","Charlie (Horváth Károly)"], c:0},
{cat:12,type:'mc',d:4,q:"Melyik városban alakult meg az Edda Művek?",
 o:["Miskolc","Debrecen","Győr","Pécs"], c:0},
{cat:12,type:'mc',d:5,q:"Melyik világhírű együttes dolgozta fel „White Dove” címmel az Omega „Gyöngyhajú lány” című dalát?",
 o:["Scorpions","Deep Purple","Uriah Heep","Nazareth"], c:0},
{cat:12,type:'mc',d:5,q:"Milyen néven jelentek meg külföldön a Neoton Família lemezei?",
 o:["Newton Family","Neon Family","Hungarian Family","New Tone Group"], c:0},
{cat:12,type:'mc',d:5,q:"Melyik együttes frontembereként kezdte pályafutását Ákos, azaz Kovács Ákos?",
 o:["Bonanza Banzai","Napoleon Boulevard","Első Emelet","Rapülők"], c:0},
{cat:12,type:'tip',d:1,q:"Hány tagja van a Bon-Bon együttesnek?",a:2,unit:"tag",note:"A duót Szolnoki Péter és Török Tamás alkotja."},
{cat:12,type:'tip',d:1,q:"Hány tagú volt az Illés együttes klasszikus felállása?",a:5,unit:"tag",note:"Illés Lajos, Szörényi Levente, Szörényi Szabolcs, Bródy János és Pásztory Zoltán."},
{cat:12,type:'tip',d:2,q:"Melyik évben hunyt el Bódi László „Cipő”, a Republic énekese?",a:2013,unit:"",note:"A zenekar frontembere 47 évesen távozott."},
{cat:12,type:'tip',d:2,q:"Hány tagja van a Tankcsapdának?",a:3,unit:"tag",note:"A debreceni zenekar megalakulása óta trióként működik."},
{cat:12,type:'tip',d:2,q:"Melyik évben hunyt el Kóbor János, az Omega énekese?",a:2021,unit:"",note:"78 éves korában érte a halál."},
{cat:12,type:'tip',d:2,q:"Melyik évben hunyt el Balázs Fecó, a Korál énekese?",a:2020,unit:"",note:"A „Homok a szélben” előadója a koronavírus-járvány áldozata lett."},
{cat:12,type:'tip',d:3,q:"Melyik évben rendezték meg az első Sziget Fesztivált (akkor még Diáksziget néven)?",a:1993,unit:"",note:""},
{cat:12,type:'tip',d:3,q:"Melyik évben mutatták be az István, a király rockoperát?",a:1983,unit:"",note:"Az ősbemutatót a városligeti Királydombon tartották."},
{cat:12,type:'tip',d:3,q:"Melyik évben rendezték meg az első Táncdalfesztivált?",a:1966,unit:"",note:"A tévés dalverseny egy csapásra sztárokat teremtett."},
{cat:12,type:'tip',d:3,q:"Melyik évben alakult meg a Locomotiv GT?",a:1971,unit:"",note:"Presser Gábor, Frenreisz Károly, Barta Tamás és Laux József alapította."},
{cat:12,type:'tip',d:3,q:"Melyik évben rendezték meg az első Balaton Sound fesztivált?",a:2007,unit:"",note:"A zamárdi fesztivál az elektronikus zene hazai fellegvára lett."},
{cat:12,type:'tip',d:3,q:"Melyik évben hunyt el Cserháti Zsuzsa?",a:2003,unit:"",note:"Az „Édes kisfiam” énekesnője 55 évesen távozott."},
{cat:12,type:'tip',d:3,q:"Melyik évben mutatták be A padlás című musicalt a Vígszínházban?",a:1988,unit:"",note:"Presser Gábor és Sztevanovity Dusán közös műve máig műsoron van."},
{cat:12,type:'tip',d:3,q:"Melyik évben hunyt el Zámbó Jimmy?",a:2001,unit:"",note:"A Király mindössze 42 évesen, tragikus körülmények között hunyt el."},
{cat:12,type:'tip',d:4,q:"Melyik évben alakult meg az Omega együttes?",a:1962,unit:"",note:""},
{cat:12,type:'tip',d:4,q:"Melyik évben született Liszt Ferenc?",a:1811,unit:"",note:"Doborjánban"},
{cat:12,type:'tip',d:4,q:"Hány évesen hunyt el Máté Péter?",a:37,unit:"évesen",note:"1947–1984"},
{cat:12,type:'tip',d:4,q:"Melyik évben szerepelt először Magyarország az Eurovíziós Dalfesztivál döntőjében?",a:1994,unit:"",note:"Friderika a „Kinek mondjam el vétkeimet?” című dallal a 4. helyen végzett."},
{cat:12,type:'tip',d:5,q:"Melyik évben adott legendás koncertet a Queen a budapesti Népstadionban?",a:1986,unit:"",note:"Freddie Mercury a „Tavaszi szél vizet áraszt” című népdalt is elénekelte."},
{cat:12,type:'tip',d:5,q:"Melyik évben mutatták be az Ezek a fiatalok című zenés filmet?",a:1967,unit:"",note:"A filmben az Illés, Koncz Zsuzsa és Zalatnay Sarolta is szerepelt."},

