// KvízParty kérdésbázis – 2/5 darab (kategóriák: 5–8)
// ---------- 5. Magyar nyelv és szólások ----------
{cat:5,type:'mc',d:1,q:"Mit jelent a szólás: „Egyik kutya, másik eb”?",
 o:["Mindkettő ugyanolyan (rossz)","Nagyon különböznek egymástól","Halálosan összevesztek","Elválaszthatatlan jó barátok"], c:0},
{cat:5,type:'mc',d:1,q:"Hogyan folytatódik a közmondás? „Aki másnak vermet ás...”",
 o:["...maga esik bele","...az nagyot esik","...annak nem lesz nyugta","...az aranyat talál"], c:0},
{cat:5,type:'mc',d:1,q:"Melyik a helyes írásmód?",
 o:["muszáj","muszály","musszáj","musszály"], c:0},
{cat:5,type:'mc',d:2,q:"Mit jelent, ha valaki „kivágja a rezet”?",
 o:["Kiválóan helytáll","Elszökik a munka elől","Dühbe gurul","Elszórja a pénzét"], c:0},
{cat:5,type:'mc',d:2,q:"Mit jelent a szólás: „Vaj van a fején”?",
 o:["Van takargatnivalója, bűnös","Nagyon gazdag","Kissé buta","Szerencsés ember"], c:0},
{cat:5,type:'mc',d:2,q:"Hogyan folytatódik a közmondás: „Ki korán kel...”?",
 o:["...aranyat lel","...sokra megy","...messzire jut","...nagyot alkot"], c:0},
{cat:5,type:'mc',d:2,q:"Mit jelent a közmondás: „Nem esik messze az alma a fájától”?",
 o:["A gyermek tulajdonságaiban a szüleire hasonlít","A gyümölcsöt érdemes frissen leszedni","Aki keveset utazik, keveset tapasztal","Ami közel van, azt könnyű megszerezni"], c:0},
{cat:5,type:'mc',d:2,q:"Melyik írásmód helyes?",
 o:["kisebb","kissebb","kisseb","kiseb"], c:0},
{cat:5,type:'mc',d:2,q:"Melyik nyelvcsaládba tartozik a magyar nyelv?",
 o:["uráli (finnugor)","indoeurópai","türk","sémi"], c:0},
{cat:5,type:'mc',d:3,q:"Az alábbi szavak közül melyik török eredetű jövevényszó?",
 o:["papucs","ablak","asztal","iskola"], c:0},
{cat:5,type:'mc',d:3,q:"Mit jelent a szólás: „köti az ebet a karóhoz”?",
 o:["Makacsul ragaszkodik az állításához","Felelőtlenül ígérget","Szándékosan félrevezet másokat","Erőn felül vállalkozik valamire"], c:0},
{cat:5,type:'mc',d:3,q:"Mit jelent a közmondás: „Fejétől bűzlik a hal”?",
 o:["A bajok forrása többnyire a vezetőknél keresendő","A romlott ételt messziről megérezni","A hibát mindig ott keresd, ahol keletkezett","A rossz hír gyorsan terjed"], c:0},
{cat:5,type:'mc',d:3,q:"Mit jelent, ha „kenyértörésre kerül a sor”?",
 o:["Végleges szakításra, döntő összecsapásra kerül sor","Megegyezés születik a felek között","Kibékülnek a haragosok","Szűkös időszak köszönt be"], c:0},
{cat:5,type:'mc',d:3,q:"Mit jelent a szólás: „kibújik a szög a zsákból”?",
 o:["Kiderül valakinek a titkolt szándéka, igazi természete","Előkerül egy rég elveszett tárgy","Váratlan segítség érkezik","Apró hibából nagy baj lesz"], c:0},
{cat:5,type:'mc',d:3,q:"Melyik magyar település nevéből ered a „kocsi” szavunk, amely számos idegen nyelvbe is átkerült?",
 o:["Kocs","Tata","Mór","Paks"], c:0},
{cat:5,type:'mc',d:3,q:"Melyik a legkorábbi ismert, összefüggő magyar nyelvű szövegemlék?",
 o:["Halotti beszéd és könyörgés","Ómagyar Mária-siralom","Tihanyi apátság alapítólevele","Margit-legenda"], c:0},
{cat:5,type:'mc',d:3,q:"Mit jelent a szólás: „kutyaharapást szőrével”?",
 o:["A bajt azzal orvosoljuk, ami okozta","A sérelmet nem szabad elfelejteni","Kis sebből is lehet nagy baj","A támadásra támadás a válasz"], c:0},
{cat:5,type:'mc',d:3,q:"Mit jelent a régies „kelme” szó?",
 o:["Szövet, textília","Cserépedény","Fejfedő","Kéziszerszám"], c:0},
{cat:5,type:'mc',d:3,q:"Melyik írásmód helyes abban a jelentésben, hogy 'naponta'?",
 o:["mindennap (egybeírva)","minden nap (különírva)","minden-nap (kötőjellel)","mindenap (egy n-nel)"], c:0},
{cat:5,type:'mc',d:3,q:"Melyik a „hisz” ige helyes felszólító módú alakja alanyi ragozásban (te)?",
 o:["higgy","higyj","hidj","higgyj"], c:0},
{cat:5,type:'mc',d:3,q:"Mit jelent a mondás: „Több nap, mint kolbász”?",
 o:["Be kell osztani a javakat, mert nem jut mindennap a jóból","Az idő minden sebet begyógyít","A várakozás meghozza gyümölcsét","Aki sokat ígér, keveset ad"], c:0},
{cat:5,type:'mc',d:4,q:"A 2015-ös akadémiai helyesírási szabályzat (12. kiadás) szerint melyik a helyes írásmód?",
 o:["észszerű","ésszerű","észerű","ész-szerű"], c:0},
{cat:5,type:'mc',d:4,q:"Melyik szavunk szláv eredetű jövevényszó?",
 o:["király","kéz","ház","hal"], c:0},
{cat:5,type:'mc',d:4,q:"Mit jelent a „hűbelebalázs módjára” kifejezés?",
 o:["Meggondolatlanul, elhamarkodottan","Alaposan, körültekintően","Titokban, lopakodva","Nagy zajjal, feltűnően"], c:0},
{cat:5,type:'mc',d:4,q:"Mi volt eredetileg a „csízió”, amelyre az „érti a csíziót” szólás utal?",
 o:["Verses öröknaptár (kalendárium)","Titkosírás","Kártyajáték","Céhszabályzat"], c:0},
{cat:5,type:'mc',d:4,q:"Mit tanácsol a régi mondás: „Suba subához, guba gubához”?",
 o:["Mindenki a maga társadalmi rangjából válasszon párt","A ruhát alkalomhoz illően kell viselni","A hasonló munkákat egyszerre végezzük","Télen két réteg ruha is elkél"], c:0},
{cat:5,type:'mc',d:4,q:"Kire mondták régen, hogy „hétszilvafás nemes”?",
 o:["Elszegényedett, kevés birtokú kisnemesre","Nagy gyümölcsösöket birtokló főúrra","Hét falut birtokló várúrra","Nemesi címét pénzen vevő polgárra"], c:0},
{cat:5,type:'mc',d:5,q:"Mit jelentett eredetileg a „féreg” szó az „ordít, mint a fába szorult féreg” szólásban?",
 o:["Farkast","Kukacot","Kígyót","Egeret"], c:0},
{cat:5,type:'mc',d:5,q:"Mit jelentett eredetileg az „ildomos” szó a régi magyar nyelvben?",
 o:["Okosat, eszélyeset","Illedelmeset","Gyorsat","Bőkezűt"], c:0},
{cat:5,type:'mc',d:5,q:"Mit jelentett a régi magyar nyelvben a „pest” szó, amely Pest városnevében is fennmaradt?",
 o:["Kemencét","Révátkelőt","Vásárteret","Mocsarat"], c:0},
{cat:5,type:'tip',d:1,q:"Hány írásjegyből áll a magyar ábécé „cs” betűje?",a:2,unit:"db",note:"A cs kétjegyű betű: a c és az s írásjegyekből áll."},
{cat:5,type:'tip',d:1,q:"Hány szótagból áll a „kikelet” szó?",a:3,unit:"db",note:"Ki-ke-let; a kikelet a tavasz régies, költői neve."},
{cat:5,type:'tip',d:2,q:"Hány betűből áll a magyar ábécé?",a:44,unit:"betű",note:"a kétjegyű és háromjegyű betűkkel együtt"},
{cat:5,type:'tip',d:2,q:"Hány magánhangzó van a magyar ábécében?",a:14,unit:"",note:"a–á, e–é, i–í, o–ó, ö–ő, u–ú, ü–ű"},
{cat:5,type:'tip',d:2,q:"Hány millió ember beszéli a magyart anyanyelvként?",a:13,unit:"millió fő",note:"kb. 13 millió világszerte"},
{cat:5,type:'tip',d:2,q:"Hányféle magánhangzót szabad használni az eszperente nyelvi játékban?",a:1,unit:"db",note:"Csak az „e” magánhangzó megengedett."},
{cat:5,type:'tip',d:3,q:"Melyik évben kelt a tihanyi apátság alapítólevele, a legkorábbi eredetiben fennmaradt magyar szórványemlékünk?",a:1055,unit:"",note:"I. András adta ki; magyar szavakat is őriz, pl. „feheruuaru rea meneh hodu utu rea”."},
{cat:5,type:'tip',d:3,q:"Melyik évben jelent meg a magyar helyesírási szabályzat jelenleg érvényes, 12. kiadása?",a:2015,unit:"",note:"Ekkor lett például az „ésszerű” helyett „észszerű” a helyes alak."},
{cat:5,type:'tip',d:3,q:"Hány többjegyű betű van a magyar ábécében?",a:9,unit:"db",note:"cs, dz, dzs, gy, ly, ny, sz, ty, zs — közülük a dzs háromjegyű."},
{cat:5,type:'tip',d:3,q:"Hány betűhelyből (karakterből) áll a leghosszabb közismert magyar szó: „megszentségteleníthetetlenségeskedéseitekért”?",a:44,unit:"db",note:"Gyakran emlegetett példa a magyar szóképzés lehetőségeire."},
{cat:5,type:'tip',d:3,q:"November hányadikán ünnepeljük a magyar nyelv napját?",a:13,unit:"",note:"1844. november 13-án fogadták el a magyart államnyelvvé tevő törvényt."},
{cat:5,type:'tip',d:3,q:"Melyik évtől hivatalos nyelve a magyar az Európai Uniónak?",a:2004,unit:"",note:"Magyarország uniós csatlakozásával vált hivatalos EU-nyelvvé."},
{cat:5,type:'tip',d:3,q:"Melyik évben ajánlotta fel Széchenyi István birtokainak egyévi jövedelmét a magyar nyelvet művelő tudós társaság megalapítására?",a:1825,unit:"",note:"Ebből született meg a Magyar Tudományos Akadémia elődje."},
{cat:5,type:'tip',d:3,q:"Február hányadikán van az anyanyelv nemzetközi napja?",a:21,unit:"",note:"Az UNESCO 1999-ben nyilvánította február 21-ét az anyanyelv nemzetközi napjává."},
{cat:5,type:'tip',d:4,q:"Melyik évben jelent meg az első teljes egészében magyar nyelvű nyomtatott könyv (Sylvester János Újtestamentuma)?",a:1541,unit:"",note:"Sárvár-Újszigeten nyomtatták"},
{cat:5,type:'tip',d:4,q:"Melyik évben adta ki a Magyar Tudós Társaság az első akadémiai helyesírási szabályzatot?",a:1832,unit:"",note:"Címe: A magyar helyesírás és szóragasztás főbb szabályai."},
{cat:5,type:'tip',d:4,q:"Melyik évben fedezték fel a Leuveni kódexben az Ómagyar Mária-siralmat, az első ismert magyar nyelvű verset?",a:1922,unit:"",note:"Gragger Róbert azonosította; a kódex 1982-ben került Magyarországra."},
{cat:5,type:'tip',d:4,q:"Melyik évben indult a Magyar Nyelvőr című nyelvművelő folyóirat?",a:1872,unit:"",note:"Szarvas Gábor alapította, és máig megjelenik."},
{cat:5,type:'tip',d:5,q:"Melyik évben született Kazinczy Ferenc, a nyelvújítás vezéralakja?",a:1759,unit:"",note:"Születésnapja, október 27. előtt tisztelegve Széphalmon áll a Magyar Nyelv Múzeuma."},
{cat:5,type:'tip',d:5,q:"Hány kötetben jelent meg a 19. században a Czuczor–Fogarasi-féle „A magyar nyelv szótára”?",a:6,unit:"db",note:"1862 és 1874 között adták ki; máig a legnagyobb ilyen vállalkozások egyike."},

// ---------- 6. Világtörténelem ----------
{cat:6,type:'mc',d:1,q:"Ki volt az Amerikai Egyesült Államok első elnöke?",
 o:["George Washington","Thomas Jefferson","Abraham Lincoln","Benjamin Franklin"], c:0},
{cat:6,type:'mc',d:1,q:"Ki koronáztatta magát Franciaország császárává 1804-ben?",
 o:["Bonaparte Napóleon","XIV. Lajos","III. Napóleon","Robespierre"], c:0},
{cat:6,type:'mc',d:1,q:"Ki vezette a Szovjetuniót a második világháború idején?",
 o:["Sztálin","Lenin","Hruscsov","Brezsnyev"], c:0},
{cat:6,type:'mc',d:2,q:"Melyik ország uralkodója volt VIII. Henrik, a hat feleségéről is híres király?",
 o:["Anglia","Franciaország","Spanyolország","Skócia"], c:0},
{cat:6,type:'mc',d:2,q:"Hol szállt partra a szövetséges haderő 1944. június 6-án, a D-napon?",
 o:["Normandiában","Szicíliában","Provence-ban","Hollandiában"], c:0},
{cat:6,type:'mc',d:2,q:"Melyik városban gyilkolták meg Ferenc Ferdinánd trónörököst 1914-ben?",
 o:["Szarajevóban","Belgrádban","Bécsben","Zágrábban"], c:0},
{cat:6,type:'mc',d:2,q:"Melyik ország uralkodója volt XIV. Lajos, a „Napkirály”?",
 o:["Franciaország","Spanyolország","Anglia","Ausztria"], c:0},
{cat:6,type:'mc',d:2,q:"Melyik egyiptomi királynő volt Julius Caesar, majd Marcus Antonius szövetségese?",
 o:["VII. Kleopátra","Nofertiti","Hatsepszut","Nefertari"], c:0},
{cat:6,type:'mc',d:2,q:"Melyik római hadvezér mondta állítólag a Rubicon átlépésekor: „A kocka el van vetve”?",
 o:["Julius Caesar","Augustus","Pompeius","Marcus Antonius"], c:0},
{cat:6,type:'mc',d:3,q:"Melyik csatában szenvedett végső vereséget Napóleon 1815-ben?",
 o:["a waterlooi csatában","az austerlitzi csatában","a lipcsei csatában","a borogyinói csatában"], c:0},
{cat:6,type:'mc',d:3,q:"Melyik ókori városban voltak a világ hét csodája közé sorolt függőkertek?",
 o:["Babilonban","Alexandriában","Epheszoszban","Rodoszon"], c:0},
{cat:6,type:'mc',d:3,q:"Ki ült Anglia trónján a spanyol Armada 1588-as legyőzésekor?",
 o:["I. Erzsébet","Viktória","I. (Véres) Mária","Stuart Mária"], c:0},
{cat:6,type:'mc',d:3,q:"Kinek a nevéhez kötik elsősorban a jakobinus terrort a francia forradalomban?",
 o:["Robespierre-éhez","Dantonéhoz","Marat-éhoz","Mirabeau-éhoz"], c:0},
{cat:6,type:'mc',d:3,q:"Melyik indián birodalmat igázta le Hernán Cortés?",
 o:["az aztékot","az inkát","a maját","a toltéket"], c:0},
{cat:6,type:'mc',d:3,q:"Melyik karthágói hadvezér kelt át i. e. 218-ban elefántjaival az Alpokon, hogy megtámadja Rómát?",
 o:["Hannibál","Hasdrubal","Hamilkar Barkasz","Mago"], c:0},
{cat:6,type:'mc',d:3,q:"Melyik szovjet vezető mondta el 1956-ban a Sztálin bűneit feltáró „titkos beszédet”?",
 o:["Hruscsov","Brezsnyev","Malenkov","Bulganyin"], c:0},
{cat:6,type:'mc',d:3,q:"Melyik országban vívták a rózsák háborúját a 15. században?",
 o:["Angliában","Franciaországban","Spanyolországban","Skóciában"], c:0},
{cat:6,type:'mc',d:3,q:"Ki volt az Egyesült Államok elnöke az amerikai polgárháború idején?",
 o:["Abraham Lincoln","Ulysses S. Grant","Andrew Jackson","Thomas Jefferson"], c:0},
{cat:6,type:'mc',d:3,q:"Melyik békeszerződés zárta le az első világháborút a győztesek és Németország között?",
 o:["a versailles-i béke","a saint-germaini béke","a sèvres-i béke","a breszt-litovszki béke"], c:0},
{cat:6,type:'mc',d:3,q:"Melyik orosz uralkodó alapította Szentpétervárt?",
 o:["I. (Nagy) Péter","Rettegett Iván","II. (Nagy) Katalin","I. Sándor"], c:0},
{cat:6,type:'mc',d:3,q:"Melyik hajós érte el elsőként tengeri úton Indiát Afrika megkerülésével?",
 o:["Vasco da Gama","Bartolomeu Dias","Kolumbusz Kristóf","Amerigo Vespucci"], c:0},
{cat:6,type:'mc',d:4,q:"Ki volt Kína első császára, aki egyesítette az országot és megkezdte a Nagy Fal kiépítését?",
 o:["Csin Si Huang-ti","Kubiláj kán","Liu Pang","Han Vu-ti"], c:0},
{cat:6,type:'mc',d:4,q:"Melyik államférfi nevéhez kötődik az athéni demokrácia fénykora az i. e. 5. században?",
 o:["Periklész","Szolón","Themisztoklész","Kleiszthenész"], c:0},
{cat:6,type:'mc',d:4,q:"Melyik szerződésben osztotta fel egymás között Spanyolország és Portugália az Európán kívüli világot 1494-ben?",
 o:["a tordesillasi szerződésben","a zaragozai szerződésben","az utrechti békében","a cateau-cambrésis-i békében"], c:0},
{cat:6,type:'mc',d:4,q:"Ki volt a Nyugatrómai Birodalom utolsó császára?",
 o:["Romulus Augustulus","Honorius","III. Valentinianus","Theodosius"], c:0},
{cat:6,type:'mc',d:4,q:"Melyik uralkodóházból származott XVI. Lajos, a francia forradalom idején kivégzett király?",
 o:["a Bourbon-házból","a Valois-házból","az Orléans-i házból","a Habsburg-házból"], c:0},
{cat:6,type:'mc',d:4,q:"Melyik dinasztia utolsó uralkodója volt II. Miklós orosz cár?",
 o:["a Romanov-dinasztiáé","a Rurik-dinasztiáé","a Godunov-dinasztiáé","a Jagelló-dinasztiáé"], c:0},
{cat:6,type:'mc',d:5,q:"Melyik amerikai elnök hivatali ideje alatt vásárolta meg az USA Alaszkát Oroszországtól?",
 o:["Andrew Johnson","Abraham Lincoln","Ulysses S. Grant","James Buchanan"], c:0},
{cat:6,type:'mc',d:5,q:"Melyik pápa hirdette meg az első keresztes hadjáratot 1095-ben?",
 o:["II. Orbán","VII. Gergely","III. Ince","II. Paszkál"], c:0},
{cat:6,type:'mc',d:5,q:"Mi volt a neve a Hirosimára atombombát ledobó amerikai bombázónak?",
 o:["Enola Gay","Bockscar","Memphis Belle","Spirit of St. Louis"], c:0},
{cat:6,type:'tip',d:1,q:"Melyik évben fedezte fel Kolumbusz Amerikát?",a:1492,unit:"",note:""},
{cat:6,type:'tip',d:1,q:"Melyik évben ért véget a második világháború?",a:1945,unit:"",note:"Európában májusban, Ázsiában szeptemberben fejeződtek be a harcok."},
{cat:6,type:'tip',d:2,q:"Melyik évben omlott le a berlini fal?",a:1989,unit:"",note:"november 9-én"},
{cat:6,type:'tip',d:2,q:"Melyik évben tört ki az első világháború?",a:1914,unit:"",note:"A négyéves háború végére négy birodalom omlott össze."},
{cat:6,type:'tip',d:2,q:"Melyik évben lépett először ember a Holdra?",a:1969,unit:"",note:"Neil Armstrong az Apollo–11 küldetés parancsnokaként lépett a Hold felszínére."},
{cat:6,type:'tip',d:2,q:"Melyik évben süllyedt el a Titanic?",a:1912,unit:"",note:"Az óceánjáró az első útján, jéghegynek ütközve süllyedt el az Atlanti-óceánon."},
{cat:6,type:'tip',d:3,q:"Melyik évben koronázták császárrá Nagy Károlyt Rómában?",a:800,unit:"",note:"karácsony napján"},
{cat:6,type:'tip',d:3,q:"Melyik évben foglalták el az oszmánok Konstantinápolyt?",a:1453,unit:"",note:"Az eseményt sok történész a középkor végének egyik jelképes dátumaként tartja számon."},
{cat:6,type:'tip',d:3,q:"Melyik évben emelkedett először a levegőbe a Wright fivérek motoros repülőgépe?",a:1903,unit:"",note:"Az első repülés mindössze 12 másodpercig tartott."},
{cat:6,type:'tip',d:3,q:"Hány éves korában halt meg Nagy Sándor?",a:32,unit:"év",note:"Babilonban érte a halál i. e. 323-ban, birodalma hamarosan felbomlott."},
{cat:6,type:'tip',d:3,q:"Melyik évben ragadták magukhoz a hatalmat a bolsevikok Oroszországban?",a:1917,unit:"",note:"A régi orosz naptár szerint októberi forradalomként emlegetik, bár a Gergely-naptár szerint novemberben történt."},
{cat:6,type:'tip',d:3,q:"Melyik évben győzött Hódító Vilmos a hastingsi csatában?",a:1066,unit:"",note:"A normann hódítás alapjaiban formálta át Angliát és az angol nyelvet."},
{cat:6,type:'tip',d:3,q:"Melyik évben nyitották meg a Szuezi-csatornát?",a:1869,unit:"",note:"A csatorna több ezer kilométerrel rövidítette le az Európa és Ázsia közötti hajóutat."},
{cat:6,type:'tip',d:3,q:"Melyik évben fogadták el az amerikai Függetlenségi nyilatkozatot?",a:1776,unit:"",note:"Július 4-e azóta az Egyesült Államok nemzeti ünnepe."},
{cat:6,type:'tip',d:4,q:"Valójában hány évig tartott a „százéves háború”?",a:116,unit:"év",note:"1337–1453"},
{cat:6,type:'tip',d:4,q:"Melyik évben kezdődött a harmincéves háború?",a:1618,unit:"",note:"A prágai defenesztráció, vagyis a királyi helytartók ablakon való kihajítása robbantotta ki."},
{cat:6,type:'tip',d:4,q:"Hány napig tartott 1962-ben a kubai rakétaválság?",a:13,unit:"nap",note:"A hidegháború alatt ekkor állt a világ a legközelebb az atomháborúhoz."},
{cat:6,type:'tip',d:4,q:"Hány évig uralkodott Viktória brit királynő?",a:63,unit:"év",note:"1837-től 1901-ig ült a trónon; uralkodása alatt lett Nagy-Britannia a világ vezető nagyhatalma."},
{cat:6,type:'tip',d:5,q:"Melyik évben indult el Magellán flottája az első Föld körüli hajóútra?",a:1519,unit:"",note:"Magellán maga nem élte túl az utat; a Victoria nevű hajó 1522-ben tért vissza Spanyolországba."},
{cat:6,type:'tip',d:5,q:"Melyik évben zajlottak a salemi boszorkányperek Új-Angliában?",a:1692,unit:"",note:"A vádaskodási hullámnak húsz halálos áldozata volt."},

// ---------- 7. Világföldrajz ----------
{cat:7,type:'mc',d:1,q:"Melyik a Föld legnagyobb óceánja?",
 o:["Csendes-óceán","Atlanti-óceán","Indiai-óceán","Jeges-tenger"], c:0},
{cat:7,type:'mc',d:1,q:"Melyik a világ legnagyobb területű országa?",
 o:["Oroszország","Kanada","Kína","Amerikai Egyesült Államok"], c:0},
{cat:7,type:'mc',d:1,q:"Melyik a világ legnagyobb forró sivataga?",
 o:["Szahara","Góbi","Kalahári","Atacama"], c:0},
{cat:7,type:'mc',d:1,q:"Mely kontinensek határán fekszik Isztambul?",
 o:["Európa és Ázsia","Ázsia és Afrika","Európa és Afrika","Egyik határán sem"], c:0},
{cat:7,type:'mc',d:2,q:"Melyik ország fővárosa Canberra?",
 o:["Ausztrália","Kanada","Új-Zéland","Ausztria"], c:0},
{cat:7,type:'mc',d:2,q:"Melyik kontinensen folyik az Amazonas?",
 o:["Dél-Amerika","Afrika","Ázsia","Észak-Amerika"], c:0},
{cat:7,type:'mc',d:2,q:"Melyik országban található a Vezúv?",
 o:["Olaszország","Görögország","Spanyolország","Törökország"], c:0},
{cat:7,type:'mc',d:2,q:"Melyik óceán választja el Európát Észak-Amerikától?",
 o:["Atlanti-óceán","Csendes-óceán","Indiai-óceán","Jeges-tenger"], c:0},
{cat:7,type:'mc',d:2,q:"Melyik folyó folyik keresztül Párizson?",
 o:["Szajna","Loire","Rajna","Temze"], c:0},
{cat:7,type:'mc',d:3,q:"Melyik országban található a Kilimandzsáró?",
 o:["Tanzánia","Kenya","Etiópia","Uganda"], c:0},
{cat:7,type:'mc',d:3,q:"Melyik ország fővárosa Ottawa?",
 o:["Kanada","Ausztrália","Új-Zéland","Dél-afrikai Köztársaság"], c:0},
{cat:7,type:'mc',d:3,q:"Melyik a Föld legmélyebb tava?",
 o:["Bajkál-tó","Tanganyika-tó","Kaszpi-tenger","Felső-tó"], c:0},
{cat:7,type:'mc',d:3,q:"Melyik hegység alkotja a hagyományos határt Európa és Ázsia között?",
 o:["Urál","Himalája","Altaj","Tien-san"], c:0},
{cat:7,type:'mc',d:3,q:"Melyik országban ered a Duna?",
 o:["Németország","Ausztria","Svájc","Csehország"], c:0},
{cat:7,type:'mc',d:3,q:"Melyik tengerszoros választja el Európát Afrikától?",
 o:["Gibraltári-szoros","Boszporusz","Dardanellák","Messinai-szoros"], c:0},
{cat:7,type:'mc',d:3,q:"Melyik ország fővárosa Wellington?",
 o:["Új-Zéland","Ausztrália","Fidzsi","Pápua Új-Guinea"], c:0},
{cat:7,type:'mc',d:3,q:"Melyik országban található az Atacama-sivatag?",
 o:["Chile","Peru","Argentína","Mexikó"], c:0},
{cat:7,type:'mc',d:3,q:"Melyik folyó vájta ki a Grand Canyont?",
 o:["Colorado","Mississippi","Rio Grande","Columbia"], c:0},
{cat:7,type:'mc',d:3,q:"Melyik országhoz tartozik Grönland?",
 o:["Dánia","Norvégia","Kanada","Izland"], c:0},
{cat:7,type:'mc',d:3,q:"Melyik országban található a Machu Picchu?",
 o:["Peru","Bolívia","Ecuador","Mexikó"], c:0},
{cat:7,type:'mc',d:3,q:"Melyik tengerbe torkollik a Nílus?",
 o:["Földközi-tenger","Vörös-tenger","Fekete-tenger","Arab-tenger"], c:0},
{cat:7,type:'mc',d:4,q:"Melyik ország fővárosa Najpjidó (Naypyidaw)?",
 o:["Mianmar","Laosz","Kambodzsa","Banglades"], c:0},
{cat:7,type:'mc',d:4,q:"Melyik két ország határán fekszik a Titicaca-tó?",
 o:["Peru és Bolívia","Chile és Argentína","Ecuador és Kolumbia","Brazília és Paraguay"], c:0},
{cat:7,type:'mc',d:4,q:"Mi Ausztrália szárazföldjének legmagasabb csúcsa?",
 o:["Mount Kosciuszko","Mount Bogong","Uluru","Mount Cook"], c:0},
{cat:7,type:'mc',d:4,q:"Melyik a világ legmagasabb vízesése?",
 o:["Angel-vízesés","Viktória-vízesés","Niagara-vízesés","Iguazú-vízesés"], c:0},
{cat:7,type:'mc',d:4,q:"Melyik országban emelkedik az Atlasz-hegység legmagasabb csúcsa, a Toubkal?",
 o:["Marokkó","Algéria","Tunézia","Egyiptom"], c:0},
{cat:7,type:'mc',d:4,q:"Melyik tó partvidéke a Föld legalacsonyabban fekvő szárazföldi területe?",
 o:["Holt-tenger","Kaszpi-tenger","Asszál-tó","Aral-tó"], c:0},
{cat:7,type:'mc',d:5,q:"Melyik a Föld második legnagyobb szigete?",
 o:["Új-Guinea","Borneó","Madagaszkár","Baffin-sziget"], c:0},
{cat:7,type:'mc',d:5,q:"Mi Kanada legmagasabb hegycsúcsa?",
 o:["Mount Logan","Denali","Mount Robson","Mount Columbia"], c:0},
{cat:7,type:'mc',d:5,q:"Melyik nagy folyó szeli át kétszer is az Egyenlítőt?",
 o:["Kongó","Nílus","Amazonas","Niger"], c:0},
{cat:7,type:'tip',d:1,q:"Hány tagállamból áll az Amerikai Egyesült Államok?",a:50,unit:"db",note:""},
{cat:7,type:'tip',d:1,q:"Hány tagországa maradt az Európai Uniónak az Egyesült Királyság 2020-as kilépése (brexit) után?",a:27,unit:"db",note:"Az Egyesült Királyság 2020-as kilépése óta."},
{cat:7,type:'tip',d:2,q:"Hány méter magas a Mount Everest?",a:8849,unit:"m",note:"a 2020-as hivatalos mérés szerint 8848,86 m"},
{cat:7,type:'tip',d:2,q:"Hány független ország található Dél-Amerikában?",a:12,unit:"db",note:"Francia Guyana nem önálló állam, hanem Franciaország tengerentúli megyéje."},
{cat:7,type:'tip',d:2,q:"Milyen széles a La Manche csatorna a legkeskenyebb pontján?",a:34,unit:"km",note:"A Doveri-szorosnál, Dover és Calais között."},
{cat:7,type:'tip',d:2,q:"Hány országgal határos Németország?",a:9,unit:"db",note:"Ezzel az európai élmezőnybe tartozik."},
{cat:7,type:'tip',d:3,q:"Hány ország található Afrikában?",a:54,unit:"",note:""},
{cat:7,type:'tip',d:3,q:"Hány kilométer hosszú az Egyenlítő?",a:40075,unit:"km",note:"kb. 40 075 km"},
{cat:7,type:'tip',d:3,q:"Hány időzóna van Oroszországban?",a:11,unit:"",note:""},
{cat:7,type:'tip',d:3,q:"Milyen hosszú a Nílus?",a:6650,unit:"km",note:""},
{cat:7,type:'tip',d:3,q:"Hány méter magas a Mont Blanc?",a:4808,unit:"m",note:"A csúcs jégsapkája miatt a hivatalos érték néhány métert ingadozik."},
{cat:7,type:'tip',d:3,q:"Mekkora Ausztrália területe?",a:7692000,unit:"km²",note:"A Föld hatodik legnagyobb országa."},
{cat:7,type:'tip',d:3,q:"Hány méter magas a Kilimandzsáró?",a:5895,unit:"m",note:"Afrika legmagasabb hegye."},
{cat:7,type:'tip',d:3,q:"Hány méter magas a Fudzsi, Japán legmagasabb hegye?",a:3776,unit:"m",note:""},
{cat:7,type:'tip',d:4,q:"Hány méter mély az óceánok legmélyebb pontja, a Mariana-árokban található Challenger-szakadék?",a:10935,unit:"m",note:"A modern mérések 10 900 méter körüli értékeket adnak."},
{cat:7,type:'tip',d:4,q:"Milyen hosszú a Volga?",a:3531,unit:"km",note:"Európa leghosszabb folyója."},
{cat:7,type:'tip',d:4,q:"Mekkora a Kaszpi-tenger területe?",a:371000,unit:"km²",note:"A Föld legnagyobb tava, bár tengernek nevezik."},
{cat:7,type:'tip',d:4,q:"Hány méter magas az Aconcagua, Dél-Amerika legmagasabb csúcsa?",a:6961,unit:"m",note:"Egyben a legmagasabb Ázsián kívüli hegycsúcs."},
{cat:7,type:'tip',d:5,q:"Hány méter mély a Tanganyika-tó legmélyebb pontja?",a:1470,unit:"m",note:"Afrika legmélyebb tava."},
{cat:7,type:'tip',d:5,q:"Hány méter magas az Angel-vízesés, a világ legmagasabb vízesése?",a:979,unit:"m",note:"Venezuelában, a Canaima Nemzeti Parkban zuhog alá"},

// ---------- 8. Természettudomány ----------
{cat:8,type:'mc',d:1,q:"Mi a víz kémiai képlete?",
 o:["H₂O","CO₂","O₂","NaCl"], c:0},
{cat:8,type:'mc',d:1,q:"Melyik a Naprendszer legnagyobb bolygója?",
 o:["Jupiter","Szaturnusz","Neptunusz","Föld"], c:0},
{cat:8,type:'mc',d:1,q:"Ki írta A fajok eredete című művet?",
 o:["Charles Darwin","Gregor Mendel","Isaac Newton","Sigmund Freud"], c:0},
{cat:8,type:'mc',d:2,q:"Mi az emberi test legnagyobb szerve?",
 o:["A bőr","A máj","A tüdő","A vastagbél"], c:0},
{cat:8,type:'mc',d:2,q:"Melyik elem vegyjele az Au?",
 o:["Arany","Ezüst","Alumínium","Argon"], c:0},
{cat:8,type:'mc',d:2,q:"Melyik gáz alkotja a földi levegő legnagyobb részét?",
 o:["Nitrogén","Oxigén","Szén-dioxid","Argon"], c:0},
{cat:8,type:'mc',d:2,q:"Melyik bolygót nevezik vörös bolygónak?",
 o:["A Marsot","A Vénuszt","A Jupitert","A Merkúrt"], c:0},
{cat:8,type:'mc',d:2,q:"Melyik gázt termelik a növények a fotoszintézis során?",
 o:["Oxigént","Szén-dioxidot","Nitrogént","Hidrogént"], c:0},
{cat:8,type:'mc',d:2,q:"Melyik bolygónak van a legszembetűnőbb gyűrűrendszere?",
 o:["A Szaturnusznak","A Marsnak","A Vénusznak","A Merkúrnak"], c:0},
{cat:8,type:'mc',d:3,q:"Mi a vas vegyjele?",
 o:["Fe","Va","Vs","Ir"], c:0},
{cat:8,type:'mc',d:3,q:"Melyik a leggyakoribb kémiai elem a világegyetemben?",
 o:["A hidrogén","A hélium","Az oxigén","A vas"], c:0},
{cat:8,type:'mc',d:3,q:"Melyik a leggyorsabb szárazföldi állat?",
 o:["A gepárd","A villásszarvú antilop","Az agár","Az oroszlán"], c:0},
{cat:8,type:'mc',d:3,q:"Melyik gázból tartalmaz sokkal többet a kilélegzett levegő, mint a belélegzett?",
 o:["Szén-dioxidból","Oxigénből","Nitrogénből","Héliumból"], c:0},
{cat:8,type:'mc',d:3,q:"Melyik az egyetlen aktív repülésre képes emlős?",
 o:["A denevér","A repülőmókus","A kaguán","A nagy pele"], c:0},
{cat:8,type:'mc',d:3,q:"Melyik vércsoportú vér adható szükséghelyzetben szinte bárkinek?",
 o:["0 negatív","AB pozitív","A pozitív","B pozitív"], c:0},
{cat:8,type:'mc',d:3,q:"Melyik szerv termeli az inzulint?",
 o:["A hasnyálmirigy","A máj","A vese","A pajzsmirigy"], c:0},
{cat:8,type:'mc',d:3,q:"Melyik bolygó felszíne a legforróbb a Naprendszerben?",
 o:["A Vénuszé","A Merkúré","A Marsé","A Jupiteré"], c:0},
{cat:8,type:'mc',d:3,q:"Mi a konyhasó kémiai neve?",
 o:["Nátrium-klorid","Kálium-klorid","Nátrium-karbonát","Kalcium-szulfát"], c:0},
{cat:8,type:'mc',d:3,q:"Melyik fém folyékony halmazállapotú szobahőmérsékleten?",
 o:["A higany","Az ólom","Az alumínium","A cink"], c:0},
{cat:8,type:'mc',d:3,q:"Mit mérnek a Richter-skálával?",
 o:["A földrengés erősségét","A szél erősségét","A vulkánkitörés hevességét","Az árvíz magasságát"], c:0},
{cat:8,type:'mc',d:3,q:"Melyik égitest tömegvonzása okozza elsősorban a tengeri árapályt?",
 o:["A Holdé","A Napé","A Vénuszé","A Jupiteré"], c:0},
{cat:8,type:'mc',d:4,q:"Melyik bolygó forog gyakorlatilag az oldalára dőlve, csaknem 98 fokos tengelyferdeséggel?",
 o:["Az Uránusz","A Neptunusz","A Szaturnusz","A Mars"], c:0},
{cat:8,type:'mc',d:4,q:"Melyik fémnek van a legmagasabb olvadáspontja?",
 o:["A volfrámnak","A platinának","A titánnak","A vasnak"], c:0},
{cat:8,type:'mc',d:4,q:"Hogyan nevezzük a sejt energiatermelő központjaként működő sejtszervecskét?",
 o:["Mitokondrium","Riboszóma","Lizoszóma","Sejtmag"], c:0},
{cat:8,type:'mc',d:4,q:"Ki fedezte fel az AB0-vércsoportrendszert?",
 o:["Karl Landsteiner","Louis Pasteur","Robert Koch","Alexander Fleming"], c:0},
{cat:8,type:'mc',d:4,q:"Melyik madár éri el a legnagyobb sebességet zuhanórepülésben?",
 o:["A vándorsólyom","A szirti sas","A sarlósfecske","A héja"], c:0},
{cat:8,type:'mc',d:4,q:"Mi az emberi test legkeményebb anyaga?",
 o:["A fogzománc","A koponyacsont","A combcsont","A porc"], c:0},
{cat:8,type:'mc',d:5,q:"Milyen kvarkokból épül fel a proton?",
 o:["Két up- és egy down-kvarkból","Egy up- és két down-kvarkból","Három up-kvarkból","Két charm- és egy top-kvarkból"], c:0},
{cat:8,type:'mc',d:5,q:"A kacsacsőrű emlős mellett melyik másik emlős rak tojást?",
 o:["A hangyászsün","A tatu","Az oposszum","A vombat"], c:0},
{cat:8,type:'mc',d:5,q:"Melyik állatra jellemző, hogy alvás közben egyszerre csak az egyik agyféltekéje pihen?",
 o:["A palackorrú delfin","A csimpánz","Az afrikai elefánt","A jegesmedve"], c:0},
{cat:8,type:'tip',d:1,q:"Hány lába van a póknak?",a:8,unit:"db",note:"A rovaroknak ezzel szemben hat lábuk van."},
{cat:8,type:'tip',d:1,q:"Hány bolygó kering a Naprendszerben?",a:8,unit:"db",note:"A Plútót 2006-ban törpebolygóvá minősítették át."},
{cat:8,type:'tip',d:2,q:"Hány csontja van egy felnőtt embernek?",a:206,unit:"db",note:""},
{cat:8,type:'tip',d:2,q:"Hány km/s a fény sebessége vákuumban?",a:299792,unit:"km/s",note:"kb. 300 000 km/s"},
{cat:8,type:'tip',d:2,q:"A felnőtt emberi test hány százaléka víz körülbelül?",a:60,unit:"%",note:""},
{cat:8,type:'tip',d:2,q:"Hány fogból áll a felnőtt ember teljes fogazata a bölcsességfogakkal együtt?",a:32,unit:"db",note:"A tejfogazat ezzel szemben csak 20 fogból áll."},
{cat:8,type:'tip',d:3,q:"Hány elemet tartalmaz jelenleg a periódusos rendszer?",a:118,unit:"",note:"az utolsó az oganeszon"},
{cat:8,type:'tip',d:3,q:"Hány pár bordája van az embernek?",a:12,unit:"pár",note:"Az alsó két pár az úgynevezett lengőborda."},
{cat:8,type:'tip',d:3,q:"Hány kromoszóma található az ember testi sejtjeiben?",a:46,unit:"db",note:"23 párba rendeződnek."},
{cat:8,type:'tip',d:3,q:"Hány perc alatt ér a napfény a Napból a Földre?",a:8,unit:"perc",note:"Pontosabban körülbelül 8 perc 20 másodperc alatt."},
{cat:8,type:'tip',d:3,q:"Hány nap alatt kerüli meg a Hold a Földet?",a:27,unit:"nap",note:"Pontosabban 27,3 nap a sziderikus keringési idő."},
{cat:8,type:'tip',d:3,q:"A Föld felszínének hány százalékát borítja víz?",a:71,unit:"%",note:"Ezért nevezik a Földet kék bolygónak."},
{cat:8,type:'tip',d:3,q:"Hány szíve van a polipnak?",a:3,unit:"db",note:"Kettő a kopoltyúkba, egy a test többi részébe pumpálja a vért."},
{cat:8,type:'tip',d:3,q:"Hány proton található a szénatom magjában?",a:6,unit:"db",note:"A protonok száma adja meg az elem rendszámát."},
{cat:8,type:'tip',d:4,q:"Hány Celsius-fok az abszolút nulla, az elérhető legalacsonyabb hőmérséklet?",a:-273,unit:"°C",note:"Pontosan −273,15 °C, ami 0 kelvinnek felel meg."},
{cat:8,type:'tip',d:4,q:"Hány km/s a szökési sebesség a Föld felszínén?",a:11,unit:"km/s",note:"Pontosabban kb. 11,2 km/s kell a Föld vonzásának elhagyásához."},
{cat:8,type:'tip',d:4,q:"Hány év a Halley-üstökös keringési ideje?",a:76,unit:"év",note:"Legutóbb 1986-ban járt a Föld közelében, legközelebb 2061-ben tér vissza."},
{cat:8,type:'tip',d:4,q:"Hány km/s sebességgel kering a Föld a Nap körül?",a:30,unit:"km/s",note:"Pontosabban átlagosan kb. 29,8 km/s-mal."},
{cat:8,type:'tip',d:5,q:"Hány Celsius-fok a Nap felszínének (fotoszférájának) hőmérséklete?",a:5500,unit:"°C",note:"A Nap magjában ezzel szemben sok millió fok uralkodik."},
{cat:8,type:'tip',d:5,q:"Hány Celsius-fokon forr a nitrogén, vagyis milyen hőmérsékletű a folyékony nitrogén?",a:-196,unit:"°C",note:"Ezért használják mélyfagyasztásra és hűtésre."},

