// KvízParty kérdésbázis – 5/5 darab (kategóriák: 17–20)
// ---------- 17. Nemzetközi zene és popsztárok ----------
{cat:17,type:'mc',d:1,q:"Melyik együttes frontembere volt Freddie Mercury?",
 o:["Queen","The Rolling Stones","Led Zeppelin","Pink Floyd"], c:0},
{cat:17,type:'mc',d:1,q:"Kit neveznek a pop királyának?",
 o:["Michael Jacksont","Elvis Presleyt","Prince-t","Freddie Mercuryt"], c:0},
{cat:17,type:'mc',d:1,q:"Melyik országból származik az ABBA?",
 o:["Svédország","Norvégia","Dánia","Hollandia"], c:0},
{cat:17,type:'mc',d:1,q:"Ki énekli a Shape of You című világslágert?",
 o:["Ed Sheeran","Justin Bieber","Shawn Mendes","Harry Styles"], c:0},
{cat:17,type:'mc',d:2,q:"Melyik városból indult a Beatles?",
 o:["Liverpool","London","Manchester","Birmingham"], c:0},
{cat:17,type:'mc',d:2,q:"Melyik énekesnő albumai a 21 és a 25?",
 o:["Adele","Beyoncé","Taylor Swift","Rihanna"], c:0},
{cat:17,type:'mc',d:2,q:"Ki énekli a „...Baby One More Time” című dalt?",
 o:["Britney Spears","Christina Aguilera","Jessica Simpson","Katy Perry"], c:0},
{cat:17,type:'mc',d:2,q:"Melyik együttes dala a „Smells Like Teen Spirit”?",
 o:["Nirvana","Pearl Jam","Green Day","Red Hot Chili Peppers"], c:0},
{cat:17,type:'mc',d:2,q:"Melyik országból származik a Rammstein együttes?",
 o:["Németország","Ausztria","Svájc","Dánia"], c:0},
{cat:17,type:'mc',d:3,q:"Melyik együttes albuma a „The Dark Side of the Moon”?",
 o:["Pink Floyd","Led Zeppelin","Genesis","Deep Purple"], c:0},
{cat:17,type:'mc',d:3,q:"Ki énekelte a „Purple Rain” című dalt?",
 o:["Prince","Stevie Wonder","Lionel Richie","George Michael"], c:0},
{cat:17,type:'mc',d:3,q:"Melyik együttes frontembere Bono?",
 o:["U2","Simple Minds","INXS","The Police"], c:0},
{cat:17,type:'mc',d:3,q:"Melyik együttes slágere a „Hotel California”?",
 o:["Eagles","Fleetwood Mac","The Doors","Dire Straits"], c:0},
{cat:17,type:'mc',d:3,q:"Melyik együttes dala a „Wonderwall”?",
 o:["Oasis","Blur","Radiohead","Coldplay"], c:0},
{cat:17,type:'mc',d:3,q:"Melyik együttes slágere az „Eye of the Tiger” a Rocky III. című filmből?",
 o:["Survivor","Europe","Foreigner","Toto"], c:0},
{cat:17,type:'mc',d:3,q:"Melyik énekesnő albuma a „Like a Virgin”?",
 o:["Madonna","Cyndi Lauper","Janet Jackson","Whitney Houston"], c:0},
{cat:17,type:'mc',d:3,q:"Melyik együttes frontembere volt Jim Morrison?",
 o:["The Doors","The Animals","Jefferson Airplane","The Byrds"], c:0},
{cat:17,type:'mc',d:3,q:"Ki énekelte az „I Will Always Love You” című dalt a Több mint testőr című filmben?",
 o:["Whitney Houston","Mariah Carey","Céline Dion","Toni Braxton"], c:0},
{cat:17,type:'mc',d:3,q:"Melyik együttes slágere a „Losing My Religion”?",
 o:["R.E.M.","Pearl Jam","The Cure","Simple Minds"], c:0},
{cat:17,type:'mc',d:3,q:"Melyik országból származik az AC/DC együttes?",
 o:["Ausztrália","Egyesült Királyság","Egyesült Államok","Új-Zéland"], c:0},
{cat:17,type:'mc',d:3,q:"Ki a Depeche Mode frontembere, fő énekese?",
 o:["Dave Gahan","Martin Gore","Andy Fletcher","Alan Wilder"], c:0},
{cat:17,type:'mc',d:4,q:"Melyik együttes slágere a „Sunshine of Your Love”?",
 o:["Cream","The Yardbirds","The Jimi Hendrix Experience","Deep Purple"], c:0},
{cat:17,type:'mc',d:4,q:"Ki lett a Genesis énekese Peter Gabriel távozása után?",
 o:["Phil Collins","Mike Rutherford","Tony Banks","Steve Hackett"], c:0},
{cat:17,type:'mc',d:4,q:"Melyik együttes 1977-es albuma a „Rumours”?",
 o:["Fleetwood Mac","Eagles","Bee Gees","Chicago"], c:0},
{cat:17,type:'mc',d:4,q:"Ki énekli a „Space Oddity” című dalt?",
 o:["David Bowie","Elton John","Lou Reed","Rod Stewart"], c:0},
{cat:17,type:'mc',d:4,q:"Ki volt a Led Zeppelin gitárosa?",
 o:["Jimmy Page","Robert Plant","John Paul Jones","Jeff Beck"], c:0},
{cat:17,type:'mc',d:4,q:"Melyik együttes énekesnője Debbie Harry?",
 o:["Blondie","The Pretenders","Eurythmics","Roxette"], c:0},
{cat:17,type:'mc',d:5,q:"Melyik híres gitáros játszotta a szólót Michael Jackson „Beat It” című dalában?",
 o:["Eddie Van Halen","Slash","Steve Vai","Joe Satriani"], c:0},
{cat:17,type:'mc',d:5,q:"Ki volt a Beatles dobosa Ringo Starr előtt?",
 o:["Pete Best","Stuart Sutcliffe","Billy Preston","Tony Sheridan"], c:0},
{cat:17,type:'mc',d:5,q:"Mi Elton John születési neve?",
 o:["Reginald Kenneth Dwight","Richard Anthony Hopkins","Raymond George Davies","Ronald Peter Whitfield"], c:0},
{cat:17,type:'tip',d:1,q:"Hány tagja volt a Beatlesnek a klasszikus felállásban?",a:4,unit:"tag",note:"John, Paul, George és Ringo."},
{cat:17,type:'tip',d:1,q:"Hány tagja volt a Spice Girls lánycsapatnak?",a:5,unit:"tag",note:"Posh, Scary, Sporty, Baby és Ginger Spice."},
{cat:17,type:'tip',d:2,q:"Melyik évben rendezték meg a legendás Woodstock fesztivált?",a:1969,unit:"",note:""},
{cat:17,type:'tip',d:2,q:"Melyik évben hunyt el Michael Jackson?",a:2009,unit:"",note:"A This Is It koncertsorozatára készült, amikor 50 évesen elhunyt."},
{cat:17,type:'tip',d:2,q:"Melyik évben gyilkolták meg John Lennont New Yorkban?",a:1980,unit:"",note:"A Dakota-ház előtt érte a végzetes lövés december 8-án."},
{cat:17,type:'tip',d:2,q:"Melyik évben hunyt el Amy Winehouse?",a:2011,unit:"",note:"A „Back to Black” énekesnője mindössze 27 éves volt."},
{cat:17,type:'tip',d:3,q:"Melyik évben hunyt el Freddie Mercury?",a:1991,unit:"",note:""},
{cat:17,type:'tip',d:3,q:"Hány évesen halt meg Elvis Presley?",a:42,unit:"évesen",note:"1935–1977"},
{cat:17,type:'tip',d:3,q:"Melyik évben nyerte meg az ABBA az Eurovíziót a Waterloo-val?",a:1974,unit:"",note:""},
{cat:17,type:'tip',d:3,q:"Melyik évben rendezték meg a Live Aid segélykoncertet?",a:1985,unit:"",note:"Londonban és Philadelphiában egyszerre zajlott a gigakoncert."},
{cat:17,type:'tip',d:3,q:"Hány évesen hunyt el Kurt Cobain, a Nirvana frontembere?",a:27,unit:"év",note:"A hírhedt „27-esek klubjának” tagja lett."},
{cat:17,type:'tip',d:3,q:"Melyik évben hunyt el Bob Marley?",a:1981,unit:"",note:"A reggae királya mindössze 36 évet élt."},
{cat:17,type:'tip',d:3,q:"Melyik évben alakult meg a Rolling Stones?",a:1962,unit:"",note:"Első koncertjüket a londoni Marquee Clubban adták."},
{cat:17,type:'tip',d:3,q:"Melyik évben hunyt el Jimi Hendrix?",a:1970,unit:"",note:"A gitárvirtuóz Londonban vesztette életét."},
{cat:17,type:'tip',d:4,q:"Melyik évben nyerte meg Céline Dion az Eurovíziós Dalfesztivált Svájc színeiben?",a:1988,unit:"",note:"A „Ne partez pas sans moi” című dallal győzött."},
{cat:17,type:'tip',d:4,q:"Melyik évben jelent meg a Guns N’ Roses „Appetite for Destruction” című albuma?",a:1987,unit:"",note:"Minden idők egyik legsikeresebb debütáló albuma lett."},
{cat:17,type:'tip',d:4,q:"Melyik évben alakult meg a Metallica?",a:1981,unit:"",note:"Los Angelesben alapította Lars Ulrich és James Hetfield."},
{cat:17,type:'tip',d:4,q:"Melyik évben jelent meg Eminem „The Slim Shady LP” című nagylemeze?",a:1999,unit:"",note:"Ez az album hozta meg számára a világhírt."},
{cat:17,type:'tip',d:5,q:"Melyik évben született Cher?",a:1946,unit:"",note:"A „Believe” című slágerével 52 évesen is listavezető volt."},
{cat:17,type:'tip',d:5,q:"Hány hétig vezette a Billboard Hot 100-at Lil Nas X „Old Town Road” című dala 2019-ben?",a:19,unit:"hét",note:"Ezzel megdöntötte a lista addigi rekordját."},

// ---------- 18. Mémek és internetkultúra ----------
{cat:18,type:'mc',d:1,q:"Melyik kutyafajta a Doge mém sztárja?",
 o:["Shiba inu","Akita","Corgi","Husky"], c:0},
{cat:18,type:'mc',d:1,q:"Mi történik, ha valakit „rickrollolnak”?",
 o:["Rick Astley Never Gonna Give You Up klipjére irányítják át","Egy macskás videót kap","Hamis hibaüzenetet lát","Végtelen betöltőképernyőre kerül"], c:0},
{cat:18,type:'mc',d:1,q:"Mit jelent a LOL rövidítés?",
 o:["Laughing out loud","Lots of love","Loud online laugh","League of Laughs"], c:0},
{cat:18,type:'mc',d:2,q:"Melyik platformon terjedt el 2013-ban a Harlem Shake őrület?",
 o:["YouTube","TikTok","Vine","Instagram"], c:0},
{cat:18,type:'mc',d:2,q:"Melyik mémen néz hátra egy férfi egy másik nő után, miközben a barátnője felháborodik?",
 o:["Distracted Boyfriend","Hide the Pain Harold","Success Kid","Drakeposting"], c:0},
{cat:18,type:'mc',d:2,q:"Ki a Hide the Pain Harold mém magyar arca?",
 o:["Arató András","Pataky Attila","Szikora Róbert","Németh Lajos"], c:0},
{cat:18,type:'mc',d:2,q:"Milyen sütemény alkotja Nyan Cat, a szivárványcsíkot húzó pixelmacska testét?",
 o:["Pop-Tart (töltött keksz)","Muffin","Gofri","Fánk"], c:0},
{cat:18,type:'mc',d:2,q:"Milyen figura látható a Snapchat sárga logójában?",
 o:["Egy fehér szellem","Egy fehér madár","Egy fehér macska","Egy fehér villám"], c:0},
{cat:18,type:'mc',d:2,q:"Melyik alkalmazásban jelzi a jobbra húzás, hogy tetszik nekünk valaki?",
 o:["Tinder","Messenger","TikTok","Spotify"], c:0},
{cat:18,type:'mc',d:3,q:"Mit csinál a Success Kid mém kisfiúja a tengerparti fotón?",
 o:["Elszántan ökölbe szorítja a kezét","Tátott szájjal sír","Fagylaltot ejt a homokba","Homokvárat rombol le"], c:0},
{cat:18,type:'mc',d:3,q:"Milyen hangszeren „játszik” a Keyboard Cat a legendás videóban?",
 o:["Billentyűs hangszeren","Dobon","Gitáron","Xilofonon"], c:0},
{cat:18,type:'mc',d:3,q:"Mit csinál a kis Charlie a Charlie bit my finger című híres videóban?",
 o:["Megharapja a bátyja ujját","Elneveti magát alvás közben","Először mond ki egy szót","Arcon csapja az apukáját"], c:0},
{cat:18,type:'mc',d:3,q:"Melyik betegség kutatását támogatta a 2014-es jeges vödrös kihívás, az Ice Bucket Challenge?",
 o:["Az ALS-t (egy idegrendszeri betegséget)","A cukorbetegséget","A maláriát","A szívritmuszavart"], c:0},
{cat:18,type:'mc',d:3,q:"Milyen szolgáltatás volt a 2000-es évek nagy magyar internetes sikere, az iWiW?",
 o:["Közösségi oldal","Videómegosztó","Apróhirdetési oldal","Online rádió"], c:0},
{cat:18,type:'mc',d:3,q:"Mit jelent az AFK rövidítés az online játékosok nyelvében?",
 o:["Nincs a gép előtt (away from keyboard)","Azonnal visszajön","Új kört indít","Segítséget kér a csapattól"], c:0},
{cat:18,type:'mc',d:3,q:"Mit jelent a TL;DR internetes rövidítés?",
 o:["Túl hosszú volt, nem olvastam el","Ne válaszolj erre az üzenetre","A téma lezárva, ne folytasd","Később visszatérek rá"], c:0},
{cat:18,type:'mc',d:3,q:"Mi veszi körül a kalapos kutyát a This is fine feliratú mémképen?",
 o:["Lángoló szoba","Elárasztott pince","Hóvihar","Méhraj"], c:0},
{cat:18,type:'mc',d:3,q:"Hogy nevezik a Reddit tematikus részfórumait?",
 o:["Subreddit","Subthread","Redditroom","Miniboard"], c:0},
{cat:18,type:'mc',d:3,q:"Melyik alkalmazást olvasztotta magába a TikTok 2018-ban?",
 o:["Musical.ly","Dubsmash","Triller","Byte"], c:0},
{cat:18,type:'mc',d:3,q:"Melyik egyetem kollégiumi szobájában indította útjára Mark Zuckerberg a Facebookot?",
 o:["Harvard","Stanford","MIT","Yale"], c:0},
{cat:18,type:'mc',d:3,q:"Mit jelent a FOMO kifejezés?",
 o:["Félelem attól, hogy kimaradunk valamiből","Fotó megosztása engedély nélkül","Folyamatos mobilhasználat","Fórumokon való névtelen kommentelés"], c:0},
{cat:18,type:'mc',d:4,q:"Ki alkotta meg a „mém” kifejezést 1976-ban, Az önző gén című könyvében?",
 o:["Richard Dawkins","Stephen Hawking","Carl Sagan","Desmond Morris"], c:0},
{cat:18,type:'mc',d:4,q:"Melyik online játékhoz kötődik a legendás „Leeroy Jenkins!” csatakiáltás?",
 o:["World of Warcraft","Counter-Strike","League of Legends","EverQuest"], c:0},
{cat:18,type:'mc',d:4,q:"Melyik együttes dala a Dragostea din tei, amelyből a Numa Numa internetes őrület lett?",
 o:["O-Zone","Eiffel 65","Aqua","Vengaboys"], c:0},
{cat:18,type:'mc',d:4,q:"Ki volt automatikusan minden új MySpace-felhasználó első ismerőse?",
 o:["Tom, az oldal alapítója","Jack, a fejlesztő","Kevin, a befektető","Chad, a moderátor"], c:0},
{cat:18,type:'mc',d:4,q:"Melyik videójátékból ered a „Press F to pay respects” mém?",
 o:["Call of Duty: Advanced Warfare","Battlefield 4","Medal of Honor: Warfighter","Halo 4"], c:0},
{cat:18,type:'mc',d:4,q:"Melyik fesztiválon készült utcai interjúval vált országosan ismert mémfigurává Pumped Gabo 2015-ben?",
 o:["Balaton Sound","Sziget Fesztivál","VOLT Fesztivál","EFOTT"], c:0},
{cat:18,type:'mc',d:5,q:"Mi volt a mogorva arcáról elhíresült Grumpy Cat valódi neve?",
 o:["Tardar Sauce","Marshmallow","Peanut Butter","Cinnamon Roll"], c:0},
{cat:18,type:'mc',d:5,q:"Hogy hívták a Doge mémről világhírűvé vált shiba inu kutyát?",
 o:["Kabosu","Yuzu","Sudachi","Hachi"], c:0},
{cat:18,type:'mc',d:5,q:"Melyik programban rajzolta meg alkotója a vigyorgó Trollface-t 2008-ban?",
 o:["MS Paint","Photoshop","GIMP","Flash"], c:0},
{cat:18,type:'tip',d:1,q:"Hány óra elteltével tűnik el automatikusan egy sztori a közösségi oldalakon?",a:24,unit:"óra",note:"A formátumot a Snapchat vezette be elsőként."},
{cat:18,type:'tip',d:1,q:"Hány W betű szerepel a webcímek elején álló www rövidítésben?",a:3,unit:"db",note:"World Wide Web, azaz világháló."},
{cat:18,type:'tip',d:2,q:"Melyik évben töltötték fel az első YouTube-videót (Me at the zoo)?",a:2005,unit:"",note:""},
{cat:18,type:'tip',d:2,q:"Melyik évben jelent meg a Gangnam Style?",a:2012,unit:"",note:"az első videó, amely elérte az 1 milliárd megtekintést"},
{cat:18,type:'tip',d:2,q:"Melyik évben indult el a Facebook?",a:2004,unit:"",note:"eredetileg csak harvardi diákoknak"},
{cat:18,type:'tip',d:2,q:"Hány éves kortól engedélyezett a regisztráció a legtöbb nagy közösségi oldalon?",a:13,unit:"év",note:"A korhatár egy amerikai gyermekvédelmi törvényre vezethető vissza."},
{cat:18,type:'tip',d:3,q:"Hány másodperc lehetett maximum egy Vine-videó?",a:6,unit:"mp",note:""},
{cat:18,type:'tip',d:3,q:"Melyik évben indult el a Wikipédia?",a:2001,unit:"",note:"A magyar nyelvű változat 2003-ban követte az angolt."},
{cat:18,type:'tip',d:3,q:"Melyik évben indult el a Reddit?",a:2005,unit:"",note:"Mára az internet egyik legnagyobb fórumközössége, a mémek egyik fő forrása"},
{cat:18,type:'tip',d:3,q:"Eredetileg legfeljebb hány karakter hosszú lehetett egy tweet a Twitteren?",a:140,unit:"karakter",note:"A limitet 2017-ben emelték a duplájára."},
{cat:18,type:'tip',d:3,q:"Melyik évben osztotta meg az internetet „a ruha” (#TheDress), amelyet ki kék-feketének, ki fehér-aranynak látott?",a:2015,unit:"",note:"A ruha a valóságban kék-fekete volt."},
{cat:18,type:'tip',d:3,q:"Melyik évben indult el az Instagram?",a:2010,unit:"",note:"Az első verzió csak iPhone-ra jelent meg."},
{cat:18,type:'tip',d:3,q:"Melyik évben jelent meg a WhatsApp üzenetküldő alkalmazás?",a:2009,unit:"",note:"Két korábbi Yahoo-alkalmazott fejlesztette."},
{cat:18,type:'tip',d:3,q:"Melyik évben indult el a Twitch videójáték-közvetítő platform?",a:2011,unit:"",note:"A Justin.tv játékokra szakosodott ágából nőtt ki."},
{cat:18,type:'tip',d:4,q:"Melyik évben szűnt meg végleg az iWiW?",a:2014,unit:"",note:"A Facebook térhódítása pecsételte meg a sorsát."},
{cat:18,type:'tip',d:4,q:"Melyik évben vásárolta fel a Google a YouTube-ot?",a:2006,unit:"",note:"Az ár 1,65 milliárd dollár volt."},
{cat:18,type:'tip',d:4,q:"Melyik évben indult el a Skype internetes telefonálószolgáltatás?",a:2003,unit:"",note:"Észt fejlesztők munkája nyomán született."},
{cat:18,type:'tip',d:4,q:"Melyik évben indult el az eBay online aukciós oldal?",a:1995,unit:"",note:"Az egyik első eladott tárgy egy törött lézermutató volt."},
{cat:18,type:'tip',d:5,q:"Melyik évben javasolta Scott Fahlman professzor a :-) hangulatjel használatát egy egyetemi üzenőfalon?",a:1982,unit:"",note:"A Carnegie Mellon Egyetem fórumán született az első smiley."},
{cat:18,type:'tip',d:5,q:"Melyik évben küldték el a történelem első e-mailjét?",a:1971,unit:"",note:"Ray Tomlinson küldte, és ő emelte be a címekbe a @ jelet."},

// ---------- 19. Videójátékok és gaming ----------
{cat:19,type:'mc',d:1,q:"Melyik cég alkotta meg Super Mariót?",
 o:["Nintendo","Sega","Sony","Atari"], c:0},
{cat:19,type:'mc',d:1,q:"Melyik játékban építkezünk kockákból egy nyitott világban?",
 o:["Minecraft","Roblox","Terraria","LEGO Worlds"], c:0},
{cat:19,type:'mc',d:2,q:"Melyik kitalált városban játszódik a GTA V?",
 o:["Los Santos","Vice City","Liberty City","San Fierro"], c:0},
{cat:19,type:'mc',d:2,q:"Ki a The Witcher játékok főhőse?",
 o:["Ríviai Geralt","Ezio Auditore","Kratos","Arthas"], c:0},
{cat:19,type:'mc',d:2,q:"Az alábbiak közül melyik játék MOBA műfajú?",
 o:["League of Legends","Counter-Strike","FIFA","Fortnite"], c:0},
{cat:19,type:'mc',d:2,q:"Melyik országban született meg a Tetris?",
 o:["Szovjetunió","Japán","Amerikai Egyesült Államok","Németország"], c:0},
{cat:19,type:'mc',d:2,q:"Hogy hívják Mario testvérét, a zöld ruhás vízvezeték-szerelőt?",
 o:["Luigi","Wario","Toad","Yoshi"], c:0},
{cat:19,type:'mc',d:2,q:"Melyik cég gyártja a PlayStation konzolokat?",
 o:["Sony","Microsoft","Sega","Panasonic"], c:0},
{cat:19,type:'mc',d:2,q:"Hogy hívják a Pokémon-világ ikonikus, sárga, elektromos képességű lényét?",
 o:["Pikachu","Charmander","Bulbasaur","Squirtle"], c:0},
{cat:19,type:'mc',d:3,q:"Melyik cég gyártja az Xbox konzolokat?",
 o:["Microsoft","Sony","Nintendo","Atari"], c:0},
{cat:19,type:'mc',d:3,q:"Hogy hívják a The Legend of Zelda játékok kardforgató hősét, akit a játékos irányít?",
 o:["Link","Zelda","Ganon","Epona"], c:0},
{cat:19,type:'mc',d:3,q:"Melyik cég fejlesztette a World of Warcraft online szerepjátékot?",
 o:["Blizzard","Valve","BioWare","Bethesda"], c:0},
{cat:19,type:'mc',d:3,q:"Melyik cég kabalafigurája Sonic, a kék sündisznó?",
 o:["Sega","Nintendo","Capcom","Namco"], c:0},
{cat:19,type:'mc',d:3,q:"Melyik játéksorozat főhőse Lara Croft régésznő?",
 o:["Tomb Raider","Uncharted","Far Cry","Resident Evil"], c:0},
{cat:19,type:'mc',d:3,q:"Melyik cég fejlesztette a Counter-Strike: Global Offensive lövöldözős játékot?",
 o:["Valve","Activision","Ubisoft","Epic Games"], c:0},
{cat:19,type:'mc',d:3,q:"Melyik cég fejleszti az Assassin's Creed sorozatot?",
 o:["Ubisoft","Electronic Arts","Rockstar Games","Square Enix"], c:0},
{cat:19,type:'mc',d:3,q:"Melyik kiadó jelentette meg hosszú éveken át a FIFA futballjáték-sorozatot?",
 o:["Electronic Arts","Konami","2K Games","THQ"], c:0},
{cat:19,type:'mc',d:3,q:"Melyik játéksorozat része a Skyrim?",
 o:["The Elder Scrolls","Dark Souls","Dragon Age","Fallout"], c:0},
{cat:19,type:'mc',d:3,q:"Melyik lengyel stúdió fejlesztette a The Witcher játékokat?",
 o:["CD Projekt Red","Techland","People Can Fly","11 bit studios"], c:0},
{cat:19,type:'mc',d:3,q:"Melyik országból származik az Angry Birds fejlesztője, a Rovio?",
 o:["Finnország","Svédország","Dánia","Hollandia"], c:0},
{cat:19,type:'mc',d:3,q:"Hogy hívják a Halo sorozat páncélos főhősét?",
 o:["Master Chief","Marcus Fenix","Commander Shepard","Doomguy"], c:0},
{cat:19,type:'mc',d:4,q:"Melyik japán cég fejlesztette a Tekken verekedős játéksorozatot?",
 o:["Namco","Capcom","SNK","Konami"], c:0},
{cat:19,type:'mc',d:4,q:"Melyik japán cég alkotta meg a Final Fantasy sorozatot?",
 o:["Square","Capcom","Sega","Enix"], c:0},
{cat:19,type:'mc',d:4,q:"Melyik stúdió készítette az 1993-as DOOM lövöldözős játékot?",
 o:["id Software","3D Realms","Epic MegaGames","Raven Software"], c:0},
{cat:19,type:'mc',d:4,q:"Ki a Metal Gear játéksorozat megalkotója?",
 o:["Hideo Kojima","Shigeru Miyamoto","Hidetaka Miyazaki","Yu Suzuki"], c:0},
{cat:19,type:'mc',d:4,q:"Melyik cég fejlesztette a Street Fighter verekedős sorozatot?",
 o:["Capcom","Namco","Sega","Midway"], c:0},
{cat:19,type:'mc',d:4,q:"Melyik konzolra jelent meg eredetileg a GoldenEye 007 lövöldözős játék 1997-ben?",
 o:["Nintendo 64","PlayStation","Sega Saturn","Game Boy"], c:0},
{cat:19,type:'mc',d:5,q:"Ki alapította az Atari céget 1972-ben Ted Dabney-vel közösen?",
 o:["Nolan Bushnell","Ralph Baer","Steve Jobs","Gabe Newell"], c:0},
{cat:19,type:'mc',d:5,q:"Milyen néven szerepelt Mario az 1981-es Donkey Kong játékban?",
 o:["Jumpman","Mr. Video","Plumber Joe","Super Guy"], c:0},
{cat:19,type:'mc',d:5,q:"Melyik japán cég fejlesztette az 1978-as Space Invaders játékot?",
 o:["Taito","Namco","Nintendo","Irem"], c:0},
{cat:19,type:'tip',d:1,q:"Hány éves kortól ajánlott egy PEGI 18-as besorolású videójáték?",a:18,unit:"év",note:"A PEGI az európai korhatár-besorolási rendszer."},
{cat:19,type:'tip',d:1,q:"Hány billentyűből áll a PC-s játékokban mozgásra használt WASD kombináció?",a:4,unit:"db",note:"A W, A, S és D billentyűk az előre, balra, hátra és jobbra mozgást adják."},
{cat:19,type:'tip',d:2,q:"Maximum hány játékos ugrik ki a buszból egy Fortnite battle royale meccsen?",a:100,unit:"fő",note:""},
{cat:19,type:'tip',d:2,q:"Hány játékos játszhatta egyszerre a klasszikus Pong ütögetős játékot?",a:2,unit:"fő",note:"A Pong az egyik legelső kereskedelmileg sikeres videójáték volt."},
{cat:19,type:'tip',d:2,q:"Melyik évben került a boltokba a Nintendo Wii konzol?",a:2006,unit:"",note:"Mozgásérzékelős kontrollerével családok millióit hódította meg."},
{cat:19,type:'tip',d:2,q:"Melyik évben jelent meg a Pac-Man a játéktermekben?",a:1980,unit:"",note:"Eredeti japán neve Puckman volt."},
{cat:19,type:'tip',d:3,q:"Melyik évben jelent meg a Minecraft teljes (1.0) verziója?",a:2011,unit:"",note:""},
{cat:19,type:'tip',d:3,q:"Melyik évben dobta piacra a Sony az első PlayStationt Japánban?",a:1994,unit:"",note:""},
{cat:19,type:'tip',d:3,q:"Melyik évben született meg a Tetris?",a:1984,unit:"",note:"Alekszej Pazsitnov alkotása"},
{cat:19,type:'tip',d:3,q:"Melyik évben jelent meg a The Sims életszimulátor első része?",a:2000,unit:"",note:"Minden idők egyik legkelendőbb PC-s játéka lett."},
{cat:19,type:'tip',d:3,q:"Melyik évben jelent meg a Candy Crush Saga?",a:2012,unit:"",note:"Eredetileg Facebook-játékként indult, csak később lett mobilsiker."},
{cat:19,type:'tip',d:3,q:"Melyik évben jelent meg az Among Us, az árulós űrhajós játék?",a:2018,unit:"",note:"Csak két évvel a megjelenése után vált világsikerré."},
{cat:19,type:'tip',d:3,q:"Hány fős egy csapat a Rocket League szabványos, versenyszerű meccsein?",a:3,unit:"fő",note:"A játékban rakétahajtású autókkal fociznak a játékosok."},
{cat:19,type:'tip',d:3,q:"Melyik évben indult el a Twitch, a játékközvetítéseiről ismert streamingoldal?",a:2011,unit:"",note:"A Justin.tv oldalból vált ki, később az Amazon vásárolta fel."},
{cat:19,type:'tip',d:4,q:"Melyik évben alapították a Nintendo vállalatot?",a:1889,unit:"",note:"Eredetileg hanafuda játékkártyákat gyártott Kiotóban."},
{cat:19,type:'tip',d:4,q:"Melyik évben jelent meg a Call of Duty sorozat első része?",a:2003,unit:"",note:"Az első részek a második világháborúban játszódtak."},
{cat:19,type:'tip',d:4,q:"Melyik évben rendezték meg először a The International nevű Dota 2-világbajnokságot?",a:2011,unit:"",note:"Már az első torna összdíjazása elérte az egymillió dollárt."},
{cat:19,type:'tip',d:4,q:"Melyik évben jelent meg a Prince of Persia legelső része?",a:1989,unit:"",note:"Az élethű animációkhoz a fejlesztő a saját öccse mozgását filmezte le."},
{cat:19,type:'tip',d:5,q:"Melyik évben készült el a Spacewar!, az egyik legelső számítógépes játék?",a:1962,unit:"",note:"MIT-s hallgatók írták egy PDP–1 számítógépre."},
{cat:19,type:'tip',d:5,q:"Melyik évben jelent meg a Magnavox Odyssey, a világ első otthoni videójáték-konzolja?",a:1972,unit:"",note:"Ralph Baer tervezte; a tévéképernyőre színes fóliát kellett ragasztani hozzá."},

// ---------- 20. Nemzetközi sport ----------
{cat:20,type:'mc',d:1,q:"Hány játékos van egy labdarúgócsapatban a pályán?",
 o:["11","10","12","9"], c:0},
{cat:20,type:'mc',d:1,q:"Melyik országban született Lionel Messi?",
 o:["Argentína","Brazília","Spanyolország","Uruguay"], c:0},
{cat:20,type:'mc',d:1,q:"Melyik sportágban lett legenda Usain Bolt?",
 o:["Atlétika (sprint)","Úszás","Kosárlabda","Tenisz"], c:0},
{cat:20,type:'mc',d:1,q:"Melyik város rendezte a 2024-es nyári olimpiát?",
 o:["Párizs","Los Angeles","Tokió","London"], c:0},
{cat:20,type:'mc',d:2,q:"Melyik tenisztornát játsszák salakpályán?",
 o:["Roland Garros","Wimbledon","US Open","Australian Open"], c:0},
{cat:20,type:'mc',d:2,q:"Melyik csapat nyerte a legtöbb BEK/Bajnokok Ligája trófeát?",
 o:["Real Madrid","AC Milan","Bayern München","Liverpool"], c:0},
{cat:20,type:'mc',d:2,q:"Melyik országban rendezik a wimbledoni teniszbajnokságot?",
 o:["Anglia","Franciaország","Egyesült Államok","Ausztrália"], c:0},
{cat:20,type:'mc',d:2,q:"Milyen színű trikót visel a Tour de France összetett versenyének éllovasa?",
 o:["sárga","zöld","fehér","piros pöttyös"], c:0},
{cat:20,type:'mc',d:2,q:"Melyik sportágban lett világsztár Michael Jordan?",
 o:["kosárlabda","baseball","amerikai futball","jégkorong"], c:0},
{cat:20,type:'mc',d:2,q:"Melyik ország teniszezője Roger Federer?",
 o:["Svájc","Svédország","Németország","Ausztria"], c:0},
{cat:20,type:'mc',d:3,q:"Melyik ország nyerte meg az első labdarúgó-világbajnokságot 1930-ban?",
 o:["Uruguay","Brazília","Argentína","Olaszország"], c:0},
{cat:20,type:'mc',d:3,q:"Melyik válogatott nyerte meg a 2006-os labdarúgó-világbajnokságot?",
 o:["Olaszország","Franciaország","Németország","Portugália"], c:0},
{cat:20,type:'mc',d:3,q:"Ki minden idők legeredményesebb olimpikonja 23 aranyéremmel?",
 o:["Michael Phelps","Mark Spitz","Usain Bolt","Carl Lewis"], c:0},
{cat:20,type:'mc',d:3,q:"Milyen néven született Muhammad Ali, a legendás nehézsúlyú bokszoló?",
 o:["Cassius Clay","Sonny Liston","Floyd Patterson","Archie Moore"], c:0},
{cat:20,type:'mc',d:3,q:"Melyik ország rendezte 2010-ben az első afrikai labdarúgó-világbajnokságot?",
 o:["Dél-afrikai Köztársaság","Marokkó","Egyiptom","Nigéria"], c:0},
{cat:20,type:'mc',d:3,q:"Melyik ország tornásza volt Nadia Comăneci, aki elsőként kapott tökéletes tízest az olimpián?",
 o:["Románia","Szovjetunió","Bulgária","Csehszlovákia"], c:0},
{cat:20,type:'mc',d:3,q:"Melyik sportág bajnokcsapata kapja a Vince Lombardi-trófeát?",
 o:["amerikai futball","baseball","jégkorong","rögbi"], c:0},
{cat:20,type:'mc',d:3,q:"Melyik válogatott ellen szerezte Diego Maradona az \"Isten keze\" gólt az 1986-os világbajnokságon?",
 o:["Anglia","Belgium","NSZK","Olaszország"], c:0},
{cat:20,type:'mc',d:3,q:"Melyik csapatban nyert három NBA-bajnoki címet együtt Kobe Bryant és Shaquille O'Neal?",
 o:["Los Angeles Lakers","Chicago Bulls","Boston Celtics","San Antonio Spurs"], c:0},
{cat:20,type:'mc',d:3,q:"Melyik olimpián nyert négy aranyérmet Jesse Owens?",
 o:["1936, Berlin","1932, Los Angeles","1948, London","1928, Amszterdam"], c:0},
{cat:20,type:'mc',d:3,q:"Melyik válogatott nyerte meg óriási meglepetésre a 2004-es labdarúgó-Európa-bajnokságot?",
 o:["Görögország","Portugália","Csehország","Hollandia"], c:0},
{cat:20,type:'mc',d:4,q:"Ki futotta le elsőként 10 másodpercen belül a 100 métert hivatalos, elektromos időmérésű versenyen?",
 o:["Jim Hines","Carl Lewis","Bob Hayes","Tommie Smith"], c:0},
{cat:20,type:'mc',d:4,q:"Ki nyerte meg az első Formula–1-es világbajnokságot 1950-ben?",
 o:["Giuseppe Farina","Juan Manuel Fangio","Alberto Ascari","Stirling Moss"], c:0},
{cat:20,type:'mc',d:4,q:"Melyik országot képviselte Emil Zátopek, aki az 1952-es olimpián három futószámban is aranyat nyert?",
 o:["Csehszlovákia","Lengyelország","Szovjetunió","Jugoszlávia"], c:0},
{cat:20,type:'mc',d:4,q:"Melyik város rendezte az első téli olimpiai játékokat 1924-ben?",
 o:["Chamonix","St. Moritz","Garmisch-Partenkirchen","Oslo"], c:0},
{cat:20,type:'mc',d:4,q:"Melyik válogatottat győzte le az amerikai jégkorongcsapat az 1980-as \"Miracle on Ice\" mérkőzésen?",
 o:["Szovjetunió","Kanada","Svédország","Finnország"], c:0},
{cat:20,type:'mc',d:4,q:"Ki teljesítette elsőként a 6 méteres magasságot rúdugrásban?",
 o:["Szergej Bubka","Renaud Lavillenie","Thierry Vigneron","Armand Duplantis"], c:0},
{cat:20,type:'mc',d:5,q:"Melyik városban ugrotta Bob Beamon a 8,90 méteres távolugró világcsúcsát 1968-ban?",
 o:["Mexikóváros","Tokió","München","Róma"], c:0},
{cat:20,type:'mc',d:5,q:"Ki nyerte meg a legelső Tour de France-t 1903-ban?",
 o:["Maurice Garin","Eddy Merckx","Jacques Anquetil","Fausto Coppi"], c:0},
{cat:20,type:'mc',d:5,q:"Melyik NBA-játékos dobott 100 pontot egyetlen mérkőzésen 1962-ben?",
 o:["Wilt Chamberlain","Bill Russell","Oscar Robertson","Elgin Baylor"], c:0},
{cat:20,type:'tip',d:1,q:"Hány karika van az olimpiai zászlón?",a:5,unit:"db",note:"Az öt karika az öt kontinenst jelképezi."},
{cat:20,type:'tip',d:1,q:"Hány perces egy félidő a labdarúgásban?",a:45,unit:"perc",note:"Hosszabbítás nélkül, a rendes játékidőben."},
{cat:20,type:'tip',d:2,q:"Hány kilométer a maratoni táv (egész kilométerre kerekítve)?",a:42,unit:"km",note:"pontosan 42,195 km"},
{cat:20,type:'tip',d:2,q:"Hány méter hosszú egy olimpiai úszómedence?",a:50,unit:"m",note:""},
{cat:20,type:'tip',d:2,q:"Hány játékos lehet a pályán egyszerre egy kosárlabdacsapatból?",a:5,unit:"fő",note:""},
{cat:20,type:'tip',d:2,q:"Hány lyukból áll egy szabványos golfpálya?",a:18,unit:"db",note:""},
{cat:20,type:'tip',d:3,q:"Hány perc egy jégkorongmeccs tiszta játékideje?",a:60,unit:"perc",note:"3×20 perc"},
{cat:20,type:'tip',d:3,q:"Melyik évben rendezték az első újkori olimpiát Athénban?",a:1896,unit:"",note:""},
{cat:20,type:'tip',d:3,q:"Hány Formula–1-es világbajnoki címet nyert Ayrton Senna?",a:3,unit:"db",note:"1988-ban, 1990-ben és 1991-ben, mindhármat a McLarennel."},
{cat:20,type:'tip',d:3,q:"Hány aranyérmet nyert Mark Spitz az 1972-es müncheni olimpián?",a:7,unit:"db",note:"Mindegyik számában világcsúcsot úszott."},
{cat:20,type:'tip',d:3,q:"Hányszor nyerte meg Rafael Nadal a Roland Garrost egyesben?",a:14,unit:"db",note:"Minden idők rekordja ez egyetlen Grand Slam-tornán."},
{cat:20,type:'tip',d:3,q:"Melyik évben rendeztek először olimpiát Ázsiában?",a:1964,unit:"",note:"Tokió volt a házigazda."},
{cat:20,type:'tip',d:3,q:"Hány olimpiai aranyérmet nyert Usain Bolt?",a:8,unit:"db",note:"Kilenc lett volna, de a 2008-as váltóaranyat egy csapattársa doppingvétsége miatt elvették."},
{cat:20,type:'tip',d:3,q:"Hány Formula–1-es világbajnoki címet szerzett Michael Schumacher?",a:7,unit:"db",note:"Ötöt zsinórban nyert a Ferrarival 2000 és 2004 között."},
{cat:20,type:'tip',d:4,q:"Hány Grand Slam-tornát nyert egyesben Serena Williams?",a:23,unit:"db",note:"A nőknél ez a nyílt éra rekordja."},
{cat:20,type:'tip',d:4,q:"Melyik évben rendezték meg az első Super Bowlt?",a:1967,unit:"",note:"Az első két Super Bowlt a Green Bay Packers nyerte."},
{cat:20,type:'tip',d:4,q:"Melyik évben futotta Roger Bannister elsőként 4 percen belül az egy angol mérföldet?",a:1954,unit:"",note:"Oxfordban 3:59.4-es időt ért el."},
{cat:20,type:'tip',d:4,q:"Hány gólt szerzett Just Fontaine az 1958-as labdarúgó-világbajnokságon?",a:13,unit:"gól",note:"Máig ez az egyetlen világbajnokságon szerzett gólok rekordja."},
{cat:20,type:'tip',d:5,q:"Hány győztes mérkőzéssel, veretlenül vonult vissza Rocky Marciano nehézsúlyú világbajnok?",a:49,unit:"mérkőzés",note:"A 49–0-s mérleget a nehézsúlyban azóta sem érte el senki."},
{cat:20,type:'tip',d:5,q:"Hány Grand Slam-egyest nyert pályafutása során Margaret Court?",a:24,unit:"db",note:"Az ausztrál klasszis győzelmei az amatőr és a nyílt érából együtt jönnek ki ennyire."},
];
